(function(){function C(e){var w=!1,g,A,x,y,v,C=function(){w=!0;x=[0,1,2,4,8,16,32,64,128,27,54];for(var b=Array(256),d=0;128>d;++d)b[d]=d<<1,b[d+128]=d+128<<1^283;g=Array(256);A=Array(256);y=Array(4);v=Array(4);for(d=0;4>d;++d)y[d]=Array(256),v[d]=Array(256);for(var l=0,c=0,e,k,q,f,t,d=0;256>d;++d){f=c^c<<1^c<<2^c<<3^c<<4;f=f>>8^f&255^99;g[l]=f;A[f]=l;t=b[f];e=b[l];k=b[e];q=b[k];t^=t<<24^f<<16^f<<8^f;k=(e^k^q)<<24^(l^q)<<16^(l^k^q)<<8^l^e^q;for(var h=0;4>h;++h)y[h][l]=t,v[h][f]=k,t=t<<24|t>>>8,k=
k<<24|k>>>8;0===l?l=c=1:(l=e^b[b[b[e^q]]],c^=b[b[c]])}},E=function(b,d){for(var l=b.slice(0),c,e=1,k=l.length,q=4*(k+6+1),f=k;f<q;++f)c=l[f-1],0===f%k?(c=g[c>>>16&255]<<24^g[c>>>8&255]<<16^g[c&255]<<8^g[c>>>24]^x[e]<<24,e++):6<k&&4===f%k&&(c=g[c>>>24]<<24^g[c>>>16&255]<<16^g[c>>>8&255]<<8^g[c&255]),l[f]=l[f-k]^c;if(d){for(var e=v[0],k=v[1],t=v[2],h=v[3],m=l.slice(0),q=l.length,f=0,n=q-4;f<q;f+=4,n-=4)if(0===f||f===q-4)m[f]=l[n],m[f+1]=l[n+3],m[f+2]=l[n+2],m[f+3]=l[n+1];else for(var p=0;4>p;++p)c=
l[n+p],m[f+(3&-p)]=e[g[c>>>24]]^k[g[c>>>16&255]]^t[g[c>>>8&255]]^h[g[c&255]];l=m}return l},D=function(b,d,e,c){var I=b.length/4-1,k,q,f,t,h;c?(k=v[0],q=v[1],f=v[2],t=v[3],h=A):(k=y[0],q=y[1],f=y[2],t=y[3],h=g);var m,n,p,w,G,u;m=d[0]^b[0];n=d[c?3:1]^b[1];p=d[2]^b[2];d=d[c?1:3]^b[3];for(var r=3,s=1;s<I;++s)w=k[m>>>24]^q[n>>>16&255]^f[p>>>8&255]^t[d&255]^b[++r],G=k[n>>>24]^q[p>>>16&255]^f[d>>>8&255]^t[m&255]^b[++r],u=k[p>>>24]^q[d>>>16&255]^f[m>>>8&255]^t[n&255]^b[++r],d=k[d>>>24]^q[m>>>16&255]^f[n>>>
8&255]^t[p&255]^b[++r],m=w,n=G,p=u;e[0]=h[m>>>24]<<24^h[n>>>16&255]<<16^h[p>>>8&255]<<8^h[d&255]^b[++r];e[c?3:1]=h[n>>>24]<<24^h[p>>>16&255]<<16^h[d>>>8&255]<<8^h[m&255]^b[++r];e[2]=h[p>>>24]<<24^h[d>>>16&255]<<16^h[m>>>8&255]<<8^h[n&255]^b[++r];e[c?1:3]=h[d>>>24]<<24^h[m>>>16&255]<<16^h[n>>>8&255]<<8^h[p&255]^b[++r]},F=function(b,d,l,c,g){function k(){if(c)for(var a=0;4>a;++a)s[a]=u.getInt32();else for(a=0;4>a;++a)s[a]=B[a]^u.getInt32();D(y,s,z,c);if(c){for(a=0;4>a;++a)r.putInt32(B[a]^z[a]);B=s.slice(0)}else{for(a=
0;4>a;++a)r.putInt32(z[a]);B=z}}function q(){D(y,s,z,!1);for(var a=0;4>a;++a)s[a]=u.getInt32();for(a=0;4>a;++a){var b=s[a]^z[a];c||(s[a]=b);r.putInt32(b)}}function f(){D(y,s,z,!1);for(var a=0;4>a;++a)s[a]=u.getInt32();for(a=0;4>a;++a)r.putInt32(s[a]^z[a]),s[a]=z[a]}function t(){D(y,s,z,!1);for(var a=3;0<=a;--a)if(4294967295===s[a])s[a]=0;else{++s[a];break}for(a=0;4>a;++a)r.putInt32(u.getInt32()^z[a])}var h=null;w||C();g=(g||"CBC").toUpperCase();if("string"===typeof b&&(16===b.length||24===b.length||
32===b.length))b=e.util.createBuffer(b);else if(e.util.isArray(b)&&(16===b.length||24===b.length||32===b.length)){var m=b;b=e.util.createBuffer();for(var n=0;n<m.length;++n)b.putByte(m[n])}if(!e.util.isArray(b)){m=b;b=[];var p=m.length();if(16===p||24===p||32===p)for(p>>>=2,n=0;n<p;++n)b.push(m.getInt32())}if(!e.util.isArray(b)||4!==b.length&&6!==b.length&&8!==b.length)return h;var m=-1!==["CFB","OFB","CTR"].indexOf(g),v="CBC"===g,y=E(b,c&&!m),u,r,s,z,B,A,x,h={output:null};if("CBC"===g)x=k;else if("CFB"===
g)x=q;else if("OFB"===g)x=f;else if("CTR"===g)x=t;else throw{message:'Unsupported block cipher mode of operation: "'+g+'"'};h.update=function(a){for(A||u.putBuffer(a);16<=u.length()||0<u.length()&&A;)x()};h.finish=function(a){var b=!0,d=u.length()%16;if(!c)if(a)b=a(16,u,c);else if(v){var e=16===u.length()?16:16-u.length();u.fillWithByte(e,e)}b&&(A=!0,h.update());c&&(v&&(b=0===d),b&&(a?b=a(16,r,c):v&&(e=r.length(),e=r.at(e-1),16<e?b=!1:r.truncate(e))));!v&&!a&&0<d&&r.truncate(16-d);return b};h.start=
function(a,b){null===a&&(a=B.slice(0));if("string"===typeof a&&16===a.length)a=e.util.createBuffer(a);else if(e.util.isArray(a)&&16===a.length){var d=a;a=e.util.createBuffer();for(var c=0;16>c;++c)a.putByte(d[c])}e.util.isArray(a)||(d=a,a=Array(4),a[0]=d.getInt32(),a[1]=d.getInt32(),a[2]=d.getInt32(),a[3]=d.getInt32());u=e.util.createBuffer();r=b||e.util.createBuffer();B=a.slice(0);s=Array(4);z=Array(4);A=!1;h.output=r;if(-1!==["CFB","OFB","CTR"].indexOf(g)){for(c=0;4>c;++c)s[c]=B[c];B=null}};null!==
d&&h.start(d,l);return h};e.aes=e.aes||{};e.aes.startEncrypting=function(b,d,e,c){return F(b,d,e,!1,c)};e.aes.createEncryptionCipher=function(b,d){return F(b,null,null,!1,d)};e.aes.startDecrypting=function(b,d,e,c){return F(b,d,e,!0,c)};e.aes.createDecryptionCipher=function(b,d){return F(b,null,null,!0,d)};e.aes._expandKey=function(b,d){w||C();return E(b,d)};e.aes._updateBlock=D}if("function"!==typeof define)if("object"===typeof module&&module.exports){var J=!0;define=function(e,w){w(require,module)}}else return"undefined"===
typeof forge&&(forge={}),C(forge);var E,K=function(e,w){w.exports=function(g){var w=E.map(function(g){return e(g)}).concat(C);g=g||{};g.defined=g.defined||{};if(g.defined.aes)return g.aes;g.defined.aes=!0;for(var x=0;x<w.length;++x)w[x](g);return g.aes}},H=define;define=function(e,w){E="string"===typeof e?w.slice(2):e.slice(2);if(J)return delete define,H.apply(null,Array.prototype.slice.call(arguments,0));define=H;return define.apply(null,Array.prototype.slice.call(arguments,0))};define(["require",
"module","./util"],function(){K.apply(null,Array.prototype.slice.call(arguments,0))})})();
