(function(){function r(h){var c=h.asn1=h.asn1||{};c.Class={UNIVERSAL:0,APPLICATION:64,CONTEXT_SPECIFIC:128,PRIVATE:192};c.Type={NONE:0,BOOLEAN:1,INTEGER:2,BITSTRING:3,OCTETSTRING:4,NULL:5,OID:6,ODESC:7,EXTERNAL:8,REAL:9,ENUMERATED:10,EMBEDDED:11,UTF8:12,ROID:13,SEQUENCE:16,SET:17,PRINTABLESTRING:19,IA5STRING:22,UTCTIME:23,GENERALIZEDTIME:24,BMPSTRING:30};c.create=function(a,d,c,b){if(h.util.isArray(b)){for(var e=[],f=0;f<b.length;++f)void 0!==b[f]&&e.push(b[f]);b=e}return{tagClass:a,type:d,constructed:c,
composed:c||h.util.isArray(b),value:b}};var n=function(a){var d=a.getByte();return 128===d?void 0:d&128?a.getInt((d&127)<<3):d};c.fromDer=function(a,d){void 0===d&&(d=!0);"string"===typeof a&&(a=h.util.createBuffer(a));if(2>a.length())throw{message:"Too few bytes to parse DER.",bytes:a.length()};var k=a.getByte(),b=k&192,e=k&31,f=n(a);if(a.length()<f){if(d)throw{message:"Too few bytes to read ASN.1 value.",detail:a.length()+" < "+f};f=a.length()}var g,s=32===(k&32);g=s;if(!g&&b===c.Class.UNIVERSAL&&
e===c.Type.BITSTRING&&1<f){var l=a.read;if(0===a.getByte()&&(k=a.getByte(),k&=192,k===c.Class.UNIVERSAL||k===c.Class.CONTEXT_SPECIFIC))try{if(g=n(a)===f-(a.read-l))++l,--f}catch(m){}a.read=l}if(g)if(g=[],void 0===f)for(;;){if(a.bytes(2)===String.fromCharCode(0,0)){a.getBytes(2);break}g.push(c.fromDer(a,d))}else for(l=a.length();0<f;)g.push(c.fromDer(a,d)),f-=l-a.length(),l=a.length();else{if(void 0===f){if(d)throw{message:"Non-constructed ASN.1 object of indefinite length."};f=a.length()}if(e===c.Type.BMPSTRING)for(g=
"",l=0;l<f;l+=2)g+=String.fromCharCode(a.getInt16());else g=a.getBytes(f)}return c.create(b,e,s,g)};c.toDer=function(a){var d=h.util.createBuffer(),k=a.tagClass|a.type,b=h.util.createBuffer();if(a.composed){a.constructed?k|=32:b.putByte(0);for(var e=0;e<a.value.length;++e)void 0!==a.value[e]&&b.putBuffer(c.toDer(a.value[e]))}else if(a.type===c.Type.BMPSTRING)for(e=0;e<a.value.length;++e)b.putInt16(a.value.charCodeAt(e));else b.putBytes(a.value);d.putByte(k);if(127>=b.length())d.putByte(b.length()&
127);else{e=b.length();a="";do a+=String.fromCharCode(e&255),e>>>=8;while(0<e);d.putByte(a.length|128);for(e=a.length-1;0<=e;--e)d.putByte(a.charCodeAt(e))}d.putBuffer(b);return d};c.oidToDer=function(a){a=a.split(".");var d=h.util.createBuffer();d.putByte(40*parseInt(a[0],10)+parseInt(a[1],10));for(var c,b,e,f,g=2;g<a.length;++g){c=!0;b=[];e=parseInt(a[g],10);do f=e&127,e>>>=7,c||(f|=128),b.push(f),c=!1;while(0<e);for(c=b.length-1;0<=c;--c)d.putByte(b[c])}return d};c.derToOid=function(a){var d;"string"===
typeof a&&(a=h.util.createBuffer(a));var c=a.getByte();d=Math.floor(c/40)+"."+c%40;for(var b=0;0<a.length();)c=a.getByte(),b<<=7,c&128?b+=c&127:(d+="."+(b+c),b=0);return d};c.utcTimeToDate=function(a){var d=new Date,c=parseInt(a.substr(0,2),10),c=50<=c?1900+c:2E3+c,b=parseInt(a.substr(2,2),10)-1,e=parseInt(a.substr(4,2),10),f=parseInt(a.substr(6,2),10),g=parseInt(a.substr(8,2),10),h=0;if(11<a.length){var l=a.charAt(10),m=10;"+"!==l&&"-"!==l&&(h=parseInt(a.substr(10,2),10),m+=2)}d.setUTCFullYear(c,
b,e);d.setUTCHours(f,g,h,0);m&&(l=a.charAt(m),"+"===l||"-"===l)&&(c=parseInt(a.substr(m+1,2),10),a=parseInt(a.substr(m+4,2),10),a=6E4*(60*c+a),"+"===l?d.setTime(+d-a):d.setTime(+d+a));return d};c.generalizedTimeToDate=function(a){var d=new Date,c=parseInt(a.substr(0,4),10),b=parseInt(a.substr(4,2),10)-1,e=parseInt(a.substr(6,2),10),f=parseInt(a.substr(8,2),10),g=parseInt(a.substr(10,2),10),h=parseInt(a.substr(12,2),10),l=0,m=0,n=!1;"Z"===a.charAt(a.length-1)&&(n=!0);var q=a.length-5,p=a.charAt(q);
if("+"===p||"-"===p)m=parseInt(a.substr(q+1,2),10),q=parseInt(a.substr(q+4,2),10),m=6E4*(60*m+q),"+"===p&&(m*=-1),n=!0;"."===a.charAt(14)&&(l=1E3*parseFloat(a.substr(14),10));n?(d.setUTCFullYear(c,b,e),d.setUTCHours(f,g,h,l),d.setTime(+d+m)):(d.setFullYear(c,b,e),d.setHours(f,g,h,l));return d};c.dateToUtcTime=function(a){var d="",c=[];c.push((""+a.getUTCFullYear()).substr(2));c.push(""+(a.getUTCMonth()+1));c.push(""+a.getUTCDate());c.push(""+a.getUTCHours());c.push(""+a.getUTCMinutes());c.push(""+
a.getUTCSeconds());for(a=0;a<c.length;++a)2>c[a].length&&(d+="0"),d+=c[a];return d+"Z"};c.integerToDer=function(a){var c=h.util.createBuffer();if(-128<=a&&128>a)return c.putSignedInt(a,8);if(-32768<=a&&32768>a)return c.putSignedInt(a,16);if(-8388608<=a&&8388608>a)return c.putSignedInt(a,24);if(-2147483648<=a&&2147483648>a)return c.putSignedInt(a,32);throw{message:"Integer too large; max is 32-bits.",integer:a};};c.derToInteger=function(a){"string"===typeof a&&(a=h.util.createBuffer(a));var c=8*a.length();
if(32<c)throw{message:"Integer too large; max is 32-bits."};return a.getSignedInt(c)};c.validate=function(a,d,k,b){var e=!1;if(a.tagClass!==d.tagClass&&"undefined"!==typeof d.tagClass||a.type!==d.type&&"undefined"!==typeof d.type)b&&(a.tagClass!==d.tagClass&&b.push("["+d.name+'] Expected tag class "'+d.tagClass+'", got "'+a.tagClass+'"'),a.type!==d.type&&b.push("["+d.name+'] Expected type "'+d.type+'", got "'+a.type+'"'));else if(a.constructed===d.constructed||"undefined"===typeof d.constructed){e=
!0;if(d.value&&h.util.isArray(d.value))for(var f=0,g=0;e&&g<d.value.length;++g)e=d.value[g].optional||!1,a.value[f]&&((e=c.validate(a.value[f],d.value[g],k,b))?++f:d.value[g].optional&&(e=!0)),!e&&b&&b.push("["+d.name+'] Tag class "'+d.tagClass+'", type "'+d.type+'" expected value length "'+d.value.length+'", got "'+a.value.length+'"');e&&k&&(d.capture&&(k[d.capture]=a.value),d.captureAsn1&&(k[d.captureAsn1]=a))}else b&&b.push("["+d.name+'] Expected constructed "'+d.constructed+'", got "'+a.constructed+
'"');return e};var p=/[^\\u0000-\\u00ff]/;c.prettyPrint=function(a,d,k){var b="";d=d||0;k=k||2;0<d&&(b+="\n");for(var e="",f=0;f<d*k;++f)e+=" ";b+=e+"Tag: ";switch(a.tagClass){case c.Class.UNIVERSAL:b+="Universal:";break;case c.Class.APPLICATION:b+="Application:";break;case c.Class.CONTEXT_SPECIFIC:b+="Context-Specific:";break;case c.Class.PRIVATE:b+="Private:"}if(a.tagClass===c.Class.UNIVERSAL)switch(b+=a.type,a.type){case c.Type.NONE:b+=" (None)";break;case c.Type.BOOLEAN:b+=" (Boolean)";break;
case c.Type.BITSTRING:b+=" (Bit string)";break;case c.Type.INTEGER:b+=" (Integer)";break;case c.Type.OCTETSTRING:b+=" (Octet string)";break;case c.Type.NULL:b+=" (Null)";break;case c.Type.OID:b+=" (Object Identifier)";break;case c.Type.ODESC:b+=" (Object Descriptor)";break;case c.Type.EXTERNAL:b+=" (External or Instance of)";break;case c.Type.REAL:b+=" (Real)";break;case c.Type.ENUMERATED:b+=" (Enumerated)";break;case c.Type.EMBEDDED:b+=" (Embedded PDV)";break;case c.Type.UTF8:b+=" (UTF8)";break;
case c.Type.ROID:b+=" (Relative Object Identifier)";break;case c.Type.SEQUENCE:b+=" (Sequence)";break;case c.Type.SET:b+=" (Set)";break;case c.Type.PRINTABLESTRING:b+=" (Printable String)";break;case c.Type.IA5String:b+=" (IA5String (ASCII))";break;case c.Type.UTCTIME:b+=" (UTC time)";break;case c.Type.GENERALIZEDTIME:b+=" (Generalized time)";break;case c.Type.BMPSTRING:b+=" (BMP String)"}else b+=a.type;b=b+"\n"+(e+"Constructed: "+a.constructed+"\n");if(a.composed){for(var g=0,n="",f=0;f<a.value.length;++f)void 0!==
a.value[f]&&(g+=1,n+=c.prettyPrint(a.value[f],d+1,k),f+1<a.value.length&&(n+=","));b+=e+"Sub values: "+g+n}else if(b+=e+"Value: ",a.type===c.Type.OID&&(d=c.derToOid(a.value),b+=d,h.pki&&h.pki.oids&&d in h.pki.oids&&(b+=" ("+h.pki.oids[d]+")")),a.type===c.Type.INTEGER)try{b+=c.derToInteger(a.value)}catch(l){b+="0x"+h.util.bytesToHex(a.value)}else b=p.test(a.value)?b+("0x"+h.util.createBuffer(a.value,"utf8").toHex()):0===a.value.length?b+"[null]":b+a.value;return b}}if("function"!==typeof define)if("object"===
typeof module&&module.exports){var v=!0;define=function(h,c){c(require,module)}}else return"undefined"===typeof forge&&(forge={}),r(forge);var t,w=function(h,c){c.exports=function(c){var p=t.map(function(a){return h(a)}).concat(r);c=c||{};c.defined=c.defined||{};if(c.defined.asn1)return c.asn1;c.defined.asn1=!0;for(var a=0;a<p.length;++a)p[a](c);return c.asn1}},u=define;define=function(h,c){t="string"===typeof h?c.slice(2):h.slice(2);if(v)return delete define,u.apply(null,Array.prototype.slice.call(arguments,
0));define=u;return define.apply(null,Array.prototype.slice.call(arguments,0))};define(["require","module","./util","./oids"],function(){w.apply(null,Array.prototype.slice.call(arguments,0))})})();
