var SERVICE_LIST_REFRESH_PERIOD=12E5,helper=new helpers_background.BackgroundHelper;helper.bindClient(client);
var pendingLoginRequests={},formRecorder={},settings={},LOGIN_STORE_KEY_PREFIX="last_used_service_for_host:",serviceForHostCache={},populateLastUsedServiceCache=function(){helper.storage.local.get(void 0,function(a){var b=0,c;for(c in a)0===c.indexOf(LOGIN_STORE_KEY_PREFIX)&&(serviceForHostCache[c.substr(LOGIN_STORE_KEY_PREFIX.length)]=a[c],++b);console.log("loaded",b,"recently used services from store")})},updateLastUsedServiceForHost=function(a){var b=LOGIN_STORE_KEY_PREFIX+getCanonicalHost(a.clientData.loginUrl),
c={};c[b]=a.secretId;helper.storage.local.set(c);serviceForHostCache[getCanonicalHost(a.clientData.loginUrl)]=a.secretId},getLastUsedServiceForHost=function(a){return serviceForHostCache[a]},getLoginHintsForHost=function(a){var b={};a=getServiceInstances(a);a.length&&(b.services=a);return b},getServiceInstances=function(a,b){var c=[],d=parseInt(getLastUsedServiceForHost(a),10);if(serviceInstances)if("undefined"!==typeof a&&null!==a)for(var e=0;e<serviceInstances.length;e++){var f=getCanonicalHost(serviceInstances[e].clientData.loginUrl);
if(f===a||f==="www."+a)serviceInstances[e].mostRecent=serviceInstances[e].secretId===d,c.push(serviceInstances[e])}else c=serviceInstances;"function"===typeof b&&b(c);return c},loadSettings=function(){helper.storage.sync.get("settings",function(a){CHROME&&chrome.runtime.lastError?console.log("error loading settings",chrome.runtime.lastError.message):"settings"in a&&(console.log("settings loaded; username:",a.settings.username,"rememberMe:",a.settings.rememberMe),settings=a.settings)});populateLastUsedServiceCache()},
loadSettingsAsync=function(a){loadSettings();a&&a(settings)},saveSettingsAsync=function(a,b,c){helper.storage.sync.set({settings:a},function(){CHROME&&chrome.runtime.lastError?(console.log("error saving settings to storage",chrome.runtime.lastError.message),c&&c(chrome.runtime.lastError.message)):loadSettingsAsync(b)})},getDeviceId=function(a){helper.storage.local.get("deviceIdAsBase64",function(b){CHROME&&chrome.runtime.lastError&&(console.log("error loading device key",chrome.runtime.lastError.message),
b={});if(b&&b.deviceIdAsBase64)a(b.deviceIdAsBase64);else{b=forge.random.getBytes(20);b=window.btoa(b);var c={};c.deviceIdAsBase64=b;helper.storage.local.set(c,function(){CHROME&&chrome.runtime.lastError&&console.log("error setting key",chrome.runtime.lastError.message)});a(b)}})},saveBlacklist={},hideNotLoggedInOnLoginPages=!1,neverAskToSavePasswords=!1,highlightSelectedForms=!1;
helper.storage.sync.get(null,function(a){CHROME&&chrome.runtime.lastError&&console.log("error loading blacklist",chrome.runtime.lastError.message);"save_blacklist"in a&&(console.log("blacklist loaded"),saveBlacklist=a.save_blacklist);"highlightSelectedForms"in a&&(highlightSelectedForms=a.highlightSelectedForms);a.hideNotLoggedInOnLoginPages&&(hideNotLoggedInOnLoginPages=!0);a.neverAskToSavePasswords&&(neverAskToSavePasswords=!0);a.serverHostnameOverride&&(MITRO_HOST=a.serverHostnameOverride)});
var addSiteToSaveBlacklist=function(a){a=getCanonicalHost(a);saveBlacklist[a]=1;helper.storage.sync.set({save_blacklist:saveBlacklist},function(){CHROME&&chrome.runtime.lastError?console.log("error saving blacklist to storage",chrome.runtime.lastError.message):console.log("blacklist saved successfully")})},isSiteOnSaveBlacklist=function(a){return getCanonicalHost(a)in saveBlacklist},serviceMatchesForm=function(a,b){return b.usernameField.value===a.clientData.username},findServicesMatchingForm=function(a){for(var b=
getCanonicalHost(a.before_page),b=getServiceInstances(b),c=[],d=0;d<b.length;d++)serviceMatchesForm(b[d],a)&&c.push(b[d]);return c},shouldShowSaveServiceDialog=function(a,b){if(getCanonicalHost(a.before_page)===MITRO_HOST)b(!1,null);else if(isSiteOnSaveBlacklist(a.before_page))console.log("ignoring password on "+a.before_page),b(!1,null);else{var c=function(a){console.log("shouldShowSaveServiceDialog onError called:",a);b(!1,null)},d=findServicesMatchingForm(a);d&&1===d.length?getSiteSecretData(d[0].secretId,
function(c){a.passwordField.value===c.criticalData.password?b(!1,null):(delete c.criticalData,b(!0,c))},c):b(!0,null)}},injectSaveDialog=function(a){!neverAskToSavePasswords&&formRecorder[a]&&shouldShowSaveServiceDialog(formRecorder[a],function(b,c){if(b){var d=formRecorder[a],e=function(b){console.log("sending showSaveServiceDialog");helper.tabs.sendMessage(a,client.composeMessage("content","showSaveServiceDialog",{recordedData:JSON.stringify(d),orgInfo:b,replacedSecretData:c}))};getOrganizationInfo(null,
e,function(){e(null)})}})};helper.tabs.onUpdated(function(a){setTimeout(function(){isLoggedIn()?injectSaveDialog(a):hideNotLoggedInOnLoginPages||isAttemptingLogin()||helper.tabs.sendMessage(a,client.composeMessage("content","showMitroLoginWarningInfobar"))},FIREFOX?8E3:0)});helper.tabs.onRemoved(function(a){a in formRecorder&&delete formRecorder[a];a in pendingLoginRequests&&delete pendingLoginRequests[a]});
var isLoginInProgress=function(a){return!!pendingLoginRequests[a]},sendLoginMessageToTab=function(a,b){var c=pendingLoginRequests[a.id].secretId;delete pendingLoginRequests[a.id];getSiteSecretData(c,function(c){b.sendResponse({data:{login:c,frameId:b.data.frameId,serverHints:getServerHintsForUrl(a.url)}})},function(a){console.log("sendLoginMessageToTab call to getSiteSecretData failed?",a)})},doLogin=function(a,b){console.log("login request for "+a.clientData.loginUrl);createTab({url:a.clientData.loginUrl,
active:!0,index:b},function(b){pendingLoginRequests[b.id]=a})},resolveUri=function(a,b){var c=new URI(b);return"http"!==c.getScheme()&&"https"!==c.getScheme()?c.resolve(new URI(a)).toString():b},hidePopup=function(){helper.hidePopup()},createTab=function(a,b){helper.tabs.create(a,b)},getSelectedTab=function(a){helper.tabs.getSelected(a)},RealForge=function(){};RealForge.prototype.getRandomByte=function(){return forge.random.getBytesSync(1).charCodeAt(0)};
var generatePassword=function(a,b,c){try{var d=new mitro.PasswordRequirements;a&&a.passwordReqs&&(d.numCharacters=void 0!==a.passwordReqs.numCharacters?a.passwordReqs.numCharacters:d.numCharacters,d.minUppercase=void 0!==a.passwordReqs.minUppercase?a.passwordReqs.minUppercase:d.minUppercase,d.maxUppercase=void 0!==a.passwordReqs.maxUppercase?a.passwordReqs.maxUppercase:d.maxUppercase,d.minDigits=void 0!==a.passwordReqs.minDigits?a.passwordReqs.minDigits:d.minDigits,d.maxDigits=void 0!==a.passwordReqs.maxDigits?
a.passwordReqs.maxDigits:d.maxDigits,d.minSymbols=void 0!==a.passwordReqs.minSymbols?a.passwordReqs.minSymbols:d.minSymbols,d.maxSymbols=void 0!==a.passwordReqs.maxSymbols?a.passwordReqs.maxSymbols:d.maxSymbols,d.symbolSet=void 0!==a.passwordReqs.symbolSet?a.passwordReqs.symbolSet:d.symbolSet);b(mitro.generatePassword(new RealForge,d))}catch(e){console.log(e.message),console.log(e.stack),c&&c(e.message)}};client.initRemoteExecution("extension","checkTwoFactor changePassword hidePopup mitroSignup saveSettingsAsync loadSettingsAsync mitroLogin getSelectedTab getServiceInstances".split(" "));
if(FIREFOX){var setPopupHeight=function(a){helper.setPopupHeight(a)};client.initRemoteExecution("extension","setPopupHeight");client.initRemoteExecution("main","addSecretFromSelection")}else client.initRemoteExecution("content","addSecretFromSelection");client.initRemoteExecution(["extension","content"],["createTab","generatePassword"]);
client.addListener(["content","extension"],function(a){var b=a.type,c=a.sender,d=a.data;console.log("background received message from content script, type:",a.type);var e=function(b){a.sendResponse({error:b})};if("init"===b)console.log("got init message from Frame ",a.data.frameId),isLoginInProgress(c.id)?sendLoginMessageToTab(c,a):(e=getCanonicalHost(a.data.url),console.log("trying to find logins for ",e),d=getLoginHintsForHost(e),d.serverHints=getServerHintsForUrl(a.data.url),d.frameId=a.data.frameId,
a.sendResponse({data:d}));else if("showInfoBarOnTopFrame"===b)a.sendResponse({data:a.data});else if("login"===b)doLogin(d,c.index+1);else if("loginAccepted"===b)b=parseInt(d.value,10),console.log("fetching secret for id ",b),getSiteSecretData(b,function(b){a.sendResponse({data:b,frameId:d.frameId});updateLastUsedServiceForHost(b)},e);else if("loginRejected"===b)console.log("login rejected");else if("saveServiceAccepted"===b)delete formRecorder[c.id],addSite(d,function(a){var b=function(){if(d.showShareDialog){var b=
{url:helper.getURL("/html/secrets.html#"+parseInt(a,10)),active:!0};createTab(b,function(a){})}};d.orgId?editSiteShares({secretId:a,groupIdList:[],identityList:[],orgGroupId:d.orgId},b,b):b()},e);else if("replaceServiceAccepted"===b)delete formRecorder[c.id],fe.workerInvokeOnIdentity(userIdentity,"editSitePassword",d.secretId,d.passwordField.value,function(){console.log("updated secret")},function(a){reportError(void 0,"Error saving password"+a.userVisibleError)});else if("saveServiceRejected"===
b)delete formRecorder[c.id];else if("saveServiceBlacklisted"===b)delete formRecorder[c.id],addSiteToSaveBlacklist(d.before_page);else if("formSubmit"===b)console.log("formSubmit"),e=d,e.after_page&&(e.after_page=resolveUri(c.url,e.after_page)),formRecorder[c.id]=e,setTimeout(function(){injectSaveDialog(c.id)},5E3);else return!1;return!0});
var processAPIMessage=function(a,b){var c=function(c){"undefined"!==typeof b?b({data:c}):a.sendResponse({data:c})},d=function(a){c({error:a})},e=function(a){c({data:a})};if("getIdentity"===a.type)getIdentity(e,d);else if("getLoginState"===a.type)getLoginState(e,d);else if("mitroLogout"===a.type)mitroLogout(e,d);else if("listUsersGroupsAndSecrets"===a.type)listUsersGroupsAndSecrets(e,d);else if("getSiteSecretData"===a.type)getSiteSecretData(a.data,e,d);else if("getSiteSecretDataForDisplay"===a.type)getSiteSecretDataForDisplay(a.data,
e,d);else if("addSecret"===a.type)addSecret(a.data,e,d);else if("addSecretToGroups"===a.type)addSecretToGroups(a.data,e,d);else if("editSecret"===a.type)editSecret(a.data,e,d);else if("removeSecret"===a.type)removeSecret(a.data,e,d);else if("editSiteShares"===a.type)editSiteShares(a.data,e,d);else if("getGroup"===a.type)getGroup(a.data,e,d);else if("addGroup"===a.type)addGroup(a.data,e,d);else if("removeGroup"===a.type)removeGroup(a.data,e,d);else if("editGroup"===a.type)editGroup(a.data,e,d);else if("addIssue"===
a.type)addIssue(a.data,e,d);else if("getAuditLog"===a.type)getAuditLog(a.data,e,d);else if("createOrganization"===a.type)createOrganization(a.data,e,d);else if("getOrganizationInfo"===a.type)getOrganizationInfo(a.data,e,d);else if("getOrganization"===a.type)getOrganization(a.data,e,d);else if("selectOrganization"===a.type)selectOrganization(a.data,e,d);else if("mutateOrganization"===a.type)mutateOrganization(a.data,e,d);else if("changeRemotePassword"===a.type)changeRemotePassword(a.data,e,d);else return!1;
return!0};client.addListener(["extension","page"],processAPIMessage);setInterval(listUsersGroupsAndSecrets,SERVICE_LIST_REFRESH_PERIOD);updateIconState();loadSettings();
var MIN_REJECTS_REFRESH_MS=36E5,MAX_REJECTS_REFRESH_MS=108E5,SERVER_REJECTS=[{regex:".*",reject:{login_submit:[],submit:[],password:[],username:[]}},{regex:"https://www.mint.com$",additional_submit_button_ids:["login_button"],reject:{login_submit:[[{attributeName:"value",exactMatch:"Sign up"}],[{attributeName:"id",exactMatch:"signup_button"}]],submit:[],password:[],username:[]}},{regex:"^https://accounts[.]google[.]com/ServiceLogin",allow_empty_username:!0,reject:{login_submit:[],submit:[],password:[],
username:[]}},{regex:"^https://www.budget.com.*",reject:{login_submit:[],submit:[],password:[],username:[],form:[[{attributeName:"name",exactMatch:"reservationForm"}]]}}],refreshServerHints=function(){try{mitro.fe.getDeviceIdAsync(function(a){$.getJSON("https://"+MITRO_HOST+":"+MITRO_PORT+"/mitro-core/ServerRejects?deviceId="+a,function(a){SERVER_REJECTS=a})})}catch(a){console.log(a),console.log(a.stack)}finally{setTimeout(refreshServerHints,MIN_REJECTS_REFRESH_MS+(MAX_REJECTS_REFRESH_MS-MIN_REJECTS_REFRESH_MS)*
Math.random())}},getServerHintsForUrl=function(a){var b={reject:{submit:[],password:[],username:[],form:[]},additional_submit_button_ids:[],allow_empty_username:!1,highlightSelectedForms:highlightSelectedForms};try{for(var c=0;c<SERVER_REJECTS.length;++c)a.match(SERVER_REJECTS[c].regex)&&(SERVER_REJECTS[c].reject.submit&&(b.reject.submit=b.reject.submit.concat(SERVER_REJECTS[c].reject.submit)),SERVER_REJECTS[c].reject.password&&(b.reject.password=b.reject.password.concat(SERVER_REJECTS[c].reject.password)),
SERVER_REJECTS[c].reject.username&&(b.reject.username=b.reject.username.concat(SERVER_REJECTS[c].reject.username)),SERVER_REJECTS[c].reject.form&&(b.reject.form=b.reject.form.concat(SERVER_REJECTS[c].reject.form)),SERVER_REJECTS[c].additional_submit_button_ids&&(b.additional_submit_button_ids=b.additional_submit_button_ids.concat(SERVER_REJECTS[c].additional_submit_button_ids)),SERVER_REJECTS[c].allow_empty_username&&(b.allow_empty_username=!0),SERVER_REJECTS[c].empty_password_username_selector&&
(b.empty_password_username_id=SERVER_REJECTS[c].empty_password_username_selector))}catch(d){console.log(d),console.log(d.stack)}return b},_automaticLoginTimerId=null,automaticLoginLoop=function(){clearTimeout(_automaticLoginTimerId);_automaticLoginTimerId=null;console.log("starting auto-login attempt");loadEncryptedKey(function(a){if(a)if(isLoggedIn())console.log("looks like we're actually logged in. abandoning auto-login efforts");else{var b=function(a){attemptingLogin=!1;console.log("error w/ background login; exception:",
a);"DoEmailVerificationException"===a.exceptionType?(saveEncryptedKey(null,null),console.log("device was invalidated; removing key")):(a=12E4+18E4*Math.random(),console.log("trying again in",a,"ms"),_automaticLoginTimerId=setTimeout(automaticLoginLoop,a))};getLoginToken(a.uid,function(c){attemptingLogin=!0;mitro.fe.workerLoginWithTokenAndLocalKey(a.uid,null,c,MITRO_HOST,MITRO_PORT,a.key,null,function(a,c){commonOnLoginCode(a,c,function(){WEBPAGE&&window.parent.__extension.location.reload()},b)},b)})}else console.log("autologin: no local key, abandoning efforts to auto-login")})};
window.addEventListener("online",function(a){setTimeout(function(){console.log("online event; triggering automatic login");automaticLoginLoop()},50)});getDeviceId(function(a){mitro.fe.setFailover(FAILOVER_MITRO_HOST,FAILOVER_MITRO_PORT);mitro.fe.setDeviceId(a);refreshServerHints();automaticLoginLoop()});var checkForNewInstall=function(){helper.tabs.getAll(function(a){for(var b=0;b<a.length;b++)if(isInstallPage(a[b].url)){var c=getInstallRedirectUrl(a[b].url);helper.tabs.setUrl(a[b].id,c)}})};checkForNewInstall();
