(function(){var g={};forge.debug&&forge.debug.set("forge.http","clients",[]);var p=function(b){return b.toLowerCase().replace(/(^.)|(-.)/g,function(a){return a.toUpperCase()})},t=function(b){return"forge.http."+b.url.scheme+"."+b.url.host+"."+b.url.port},x=function(b){if(b.persistCookies)try{var a=forge.util.getItem(b.socketPool.flashApi,t(b),"cookies");b.cookies=a||{}}catch(e){}},y=function(b){if(b.persistCookies)try{forge.util.setItem(b.socketPool.flashApi,t(b),"cookies",b.cookies)}catch(a){}x(b)},
u=function(b,a){a.isConnected()?(a.options.request.connectTime=+new Date,a.connected({type:"connect",id:a.id})):(a.options.request.connectTime=+new Date,a.connect({host:b.url.host,port:b.url.port,policyPort:b.policyPort,policyUrl:b.policyUrl}))},v=function(b,a){a.buffer.clear();for(var e=null;null===e&&0<b.requests.length;)e=b.requests.shift(),e.request.aborted&&(e=null);null===e?(null!==a.options&&(a.options=null),b.idle.push(a)):(a.retries=1,a.options=e,u(b,a))},B=function(b,a,e){a.options=null;
a.connected=function(c){if(null===a.options)v(b,a);else{var d=a.options.request;d.connectTime=+new Date-d.connectTime;c.socket=a;a.options.connected(c);d.aborted?a.close():(c=d.toString(),d.body&&(c+=d.body),d.time=+new Date,a.send(c),d.time=+new Date-d.time,a.options.response.time=+new Date,a.sending=!0)}};a.closed=function(c){if(a.sending)a.sending=!1,0<a.retries?(--a.retries,u(b,a)):a.error({id:a.id,type:"ioError",message:"Connection closed during send. Broken pipe.",bytesAvailable:0});else{var d=
a.options.response;d.readBodyUntilClose&&(d.time=+new Date-d.time,d.bodyReceived=!0,a.options.bodyReady({request:a.options.request,response:d,socket:a}));a.options.closed(c);v(b,a)}};a.data=function(c){a.sending=!1;if(a.options.request.aborted)a.close();else{var d=a.options.response;c=a.receive(c.bytesAvailable);null!==c&&(a.buffer.putBytes(c),d.headerReceived||(d.readHeader(a.buffer),d.headerReceived&&a.options.headerReady({request:a.options.request,response:d,socket:a})),d.headerReceived&&!d.bodyReceived&&
d.readBody(a.buffer),d.bodyReceived&&(a.options.bodyReady({request:a.options.request,response:d,socket:a}),-1!=(d.getField("Connection")||"").indexOf("close")||"HTTP/1.0"===d.version&&null===d.getField("Keep-Alive")?a.close():v(b,a)))}};a.error=function(b){a.options.error({type:b.type,message:b.message,request:a.options.request,response:a.options.response,socket:a});a.close()};e?(a=forge.tls.wrapSocket({sessionId:null,sessionCache:{},caStore:e.caStore,cipherSuites:e.cipherSuites,socket:a,virtualHost:e.virtualHost,
verify:e.verify,getCertificate:e.getCertificate,getPrivateKey:e.getPrivateKey,getSignature:e.getSignature,deflate:e.deflate||null,inflate:e.inflate||null}),a.options=null,a.buffer=forge.util.createBuffer(),b.sockets.push(a),e.prime?a.connect({host:b.url.host,port:b.url.port,policyPort:b.policyPort,policyUrl:b.policyUrl}):b.idle.push(a)):(a.buffer=forge.util.createBuffer(),b.sockets.push(a),b.idle.push(a))},D=function(b,a){var e=[],c=b.cookies,d;for(d in c){var l=c[d],h;for(h in l){var f=l[h],k=f,
z=!1;if(-1!==k.maxAge){var C=w(new Date);k.created+k.maxAge<=C&&(z=!0)}z?e.push(f):0===a.path.indexOf(f.path)&&a.addCookie(f)}}for(c=0;c<e.length;++c)f=e[c],b.removeCookie(f.name,f.path)};g.createClient=function(b){var a=null;b.caCerts&&(a=forge.pki.createCaStore(b.caCerts));b.url=b.url||window.location.protocol+"//"+window.location.host;var e=g.parseUrl(b.url);if(!e)throw{message:"Invalid url.",details:{url:b.url}};b.connections=b.connections||1;var c=b.socketPool,d={url:e,socketPool:c,policyPort:b.policyPort,
policyUrl:b.policyUrl,requests:[],sockets:[],idle:[],secure:"https"===e.scheme,cookies:{},persistCookies:"undefined"===typeof b.persistCookies?!0:b.persistCookies};forge.debug&&forge.debug.get("forge.http","clients").push(d);x(d);var l=function(a,b,c,e){0===c&&!0===b&&(a=e[c].subject.getField("CN"),null===a||d.url.host!==a.value)&&(b={message:"Certificate common name does not match url host."});return b},h=null;d.secure&&(h={caStore:a,cipherSuites:b.cipherSuites||null,virtualHost:b.virtualHost||e.host,
verify:b.verify||l,getCertificate:b.getCertificate||null,getPrivateKey:b.getPrivateKey||null,getSignature:b.getSignature||null,prime:b.primeTlsSockets||!1},null!==c.flashApi&&(h.deflate=function(a){return forge.util.deflate(c.flashApi,a,!0)},h.inflate=function(a){return forge.util.inflate(c.flashApi,a,!0)}));for(a=0;a<b.connections;++a)B(d,c.createSocket(),h);d.send=function(a){null===a.request.getField("Host")&&a.request.setField("Host",d.url.fullHost);var b={};b.request=a.request;b.connected=a.connected||
function(){};b.closed=a.close||function(){};b.headerReady=function(b){for(var c=b.response.getCookies(),e=0;e<c.length;++e)try{d.setCookie(c[e])}catch(h){}a.headerReady&&a.headerReady(b)};b.bodyReady=a.bodyReady||function(){};b.error=a.error||function(){};b.response=g.createResponse();b.response.time=0;b.response.flashApi=d.socketPool.flashApi;b.request.flashApi=d.socketPool.flashApi;b.request.abort=function(){b.request.aborted=!0;b.connected=function(){};b.closed=function(){};b.headerReady=function(){};
b.bodyReady=function(){};b.error=function(){}};D(d,b.request);if(0===d.idle.length)d.requests.push(b);else{for(var c=null,e=d.idle.length,h=0;null===c&&h<e;++h)c=d.idle[h],c.isConnected()?d.idle.splice(h,1):c=null;null===c&&(c=d.idle.pop());c.options=b;u(d,c)}};d.destroy=function(){d.requests=[];for(var a=0;a<d.sockets.length;++a)d.sockets[a].close(),d.sockets[a].destroy();d.socketPool=null;d.sockets=[];d.idle=[]};d.setCookie=function(a){var b;if("undefined"!==typeof a.name)if(null===a.value||"undefined"===
typeof a.value||""===a.value)b=d.removeCookie(a.name,a.path);else{a.comment=a.comment||"";a.maxAge=a.maxAge||0;a.secure="undefined"===typeof a.secure?!0:a.secure;a.httpOnly=a.httpOnly||!0;a.path=a.path||"/";a.domain=a.domain||null;a.version=a.version||null;a.created=w(new Date);if(a.secure!==d.secure)throw{message:"Http client url scheme is incompatible with cookie secure flag.",url:d.url,cookie:a};if(!g.withinCookieDomain(d.url,a))throw{message:"Http client url host is incompatible with cookie domain.",
url:d.url,cookie:a};a.name in d.cookies||(d.cookies[a.name]={});d.cookies[a.name][a.path]=a;b=!0;y(d)}return b};d.getCookie=function(a,b){var c=null;if(a in d.cookies){var e=d.cookies[a];if(b)b in e&&(c=e[b]);else for(var h in e){c=e[h];break}}return c};d.removeCookie=function(a,b){var c=!1;if(a in d.cookies)if(b){if(b in d.cookies[a]){c=!0;delete d.cookies[a][b];var e=!0,h;for(h in d.cookies[a]){e=!1;break}e&&delete d.cookies[a]}}else c=!0,delete d.cookies[a];c&&y(d);return c};d.clearCookies=function(){d.cookies=
{};if(d.persistCookies)try{forge.util.clearItems(d.socketPool.flashApi,t(d))}catch(a){}};forge.log&&forge.log.debug("forge.http","created client",b);return d};var s=function(b){return b.replace(/^\s*/,"").replace(/\s*$/,"")},A=function(){var b={fields:{},setField:function(a,e){b.fields[p(a)]=[s(""+e)]},appendField:function(a,e){a=p(a);a in b.fields||(b.fields[a]=[]);b.fields[a].push(s(""+e))},getField:function(a,e){var c=null;a=p(a);a in b.fields&&(c=b.fields[a][e||0]);return c}};return b},w=function(b){b.getTimezoneOffset();
return Math.floor(+new Date/1E3)};g.createRequest=function(b){b=b||{};var a=A();a.version=b.version||"HTTP/1.1";a.method=b.method||null;a.path=b.path||null;a.body=b.body||null;a.bodyDeflated=!1;a.flashApi=null;b=b.headers||[];forge.util.isArray(b)||(b=[b]);for(var e=0;e<b.length;++e)for(var c in b[e])a.appendField(c,b[e][c]);a.addCookie=function(b){var c="",e=a.getField("Cookie");null!==e&&(c=e+"; ");w(new Date);c+=b.name+"="+b.value;a.setField("Cookie",c)};a.toString=function(){null===a.getField("User-Agent")&&
a.setField("User-Agent","forge.http 1.0");null===a.getField("Accept")&&a.setField("Accept","*/*");null===a.getField("Connection")&&(a.setField("Connection","keep-alive"),a.setField("Keep-Alive","115"));null!==a.flashApi&&null===a.getField("Accept-Encoding")&&a.setField("Accept-Encoding","deflate");null!==a.flashApi&&null!==a.body&&null===a.getField("Content-Encoding")&&!a.bodyDeflated&&100<a.body.length?(a.body=forge.util.deflate(a.flashApi,a.body),a.bodyDeflated=!0,a.setField("Content-Encoding",
"deflate"),a.setField("Content-Length",a.body.length)):null!==a.body&&a.setField("Content-Length",a.body.length);var b=a.method.toUpperCase()+" "+a.path+" "+a.version+"\r\n",c;for(c in a.fields)for(var e=a.fields[c],f=0;f<e.length;++f)b+=c+": "+e[f]+"\r\n";return b+"\r\n"};return a};g.createResponse=function(){var b=!0,a=0,e=!1,c=A();c.version=null;c.code=0;c.message=null;c.body=null;c.headerReceived=!1;c.bodyReceived=!1;c.flashApi=null;var d=function(a){var b=null,c=a.data.indexOf("\r\n",a.read);
-1!=c&&(b=a.getBytes(c-a.read),a.getBytes(2));return b},g=function(a){var b=a.indexOf(":"),d=a.substring(0,b++);c.appendField(d,b<a.length?a.substring(b):"")};c.readHeader=function(a){for(var e="";!c.headerReceived&&null!==e;)if(e=d(a),null!==e)if(b){b=!1;var k=e.split(" ");if(3<=k.length)c.version=k[0],c.code=parseInt(k[1],10),c.message=k.slice(2).join(" ");else throw{message:"Invalid http response header.",details:{line:e}};}else 0===e.length?c.headerReceived=!0:g(e);return c.headerReceived};c.readBody=
function(b){var f=c.getField("Content-Length"),k=c.getField("Transfer-Encoding");null!==f&&(f=parseInt(f));if(null!==f&&0<=f)c.body=c.body||"",c.body+=b.getBytes(f),c.bodyReceived=c.body.length===f;else if(null!==k)if(-1!=k.indexOf("chunked"))for(c.body=c.body||"",f="";null!==f&&0<b.length();)if(0<a){if(a+2>b.length())break;c.body+=b.getBytes(a);b.getBytes(2);a=0}else if(e)for(f=d(b);null!==f;)0<f.length?(g(f),f=d(b)):(c.bodyReceived=!0,f=null);else f=d(b),null!==f&&(a=parseInt(f.split(";",1)[0],
16),e=0===a);else throw{message:"Unknown Transfer-Encoding.",details:{transferEncoding:k}};else null!==f&&0>f||null===f&&null!==c.getField("Content-Type")?(c.body=c.body||"",c.body+=b.getBytes(),c.readBodyUntilClose=!0):(c.body=null,c.bodyReceived=!0);c.bodyReceived&&(c.time=+new Date-c.time);null!==c.flashApi&&c.bodyReceived&&null!==c.body&&"deflate"===c.getField("Content-Encoding")&&(c.body=forge.util.inflate(c.flashApi,c.body));return c.bodyReceived};c.getCookies=function(){var a=[];if("Set-Cookie"in
c.fields)for(var b=c.fields["Set-Cookie"],d=+new Date/1E3,e=/\s*([^=]*)=?([^;]*)(;|$)/g,g=0;g<b.length;++g){var l=b[g],q;e.lastIndex=0;var p=!0,m={};do if(q=e.exec(l),null!==q){var n=s(q[1]),r=s(q[2]);if(p)m.name=n,m.value=r,p=!1;else switch(n=n.toLowerCase(),n){case "expires":r=r.replace(/-/g," ");n=Date.parse(r)/1E3;m.maxAge=Math.max(0,n-d);break;case "max-age":m.maxAge=parseInt(r,10);break;case "secure":m.secure=!0;break;case "httponly":m.httpOnly=!0;break;default:""!==n&&(m[n]=r)}}while(null!==
q&&""!==q[0]);a.push(m)}return a};c.toString=function(){var a=c.version+" "+c.code+" "+c.message+"\r\n",b;for(b in c.fields)for(var d=c.fields[b],e=0;e<d.length;++e)a+=b+": "+d[e]+"\r\n";return a+"\r\n"};return c};g.parseUrl=forge.util.parseUrl;g.withinCookieDomain=function(b,a){var e=!1,c=null===a||"string"===typeof a?a:a.domain;if(null===c)e=!0;else if("."===c.charAt(0)){"string"===typeof b&&(b=g.parseUrl(b));var d="."+b.host,l=d.lastIndexOf(c);-1!==l&&l+c.length===d.length&&(e=!0)}return e};"undefined"===
typeof forge&&(forge={});forge.http=g})();
