var kew=kew||{};
(function(){function h(a,b,c){b?a.reject(b):a.resolve(c)}function g(a){return"object"===typeof a&&"function"===typeof a.then}function k(a){var b=new kew.Promise;b.resolve(a);return b}function l(a,b,c){return a[b]=c}kew.Promise=function(a,b){this.promise=this;this._isPromise=!0;this._successFn=a;this._failFn=b;this._scope=this;this._boundArgs=null;this._hasContext=!1;this._currentContext=this._nextContext=void 0};kew.Promise.prototype._useContext=function(a){this._nextContext=this._currentContext=a;
this._hasContext=!0;return this};kew.Promise.prototype.clearContext=function(){this._hasContext=!1;this._nextContext=void 0;return this};kew.Promise.prototype.setContext=function(a){this._nextContext=a;this._hasContext=!0;return this};kew.Promise.prototype.getContext=function(){return this._nextContext};kew.Promise.prototype.resolve=function(a){if(this._error||this._hasData)throw Error("Unable to resolve or reject the same promise twice");var b;if(a&&a._isPromise){this._child=a;if(this._promises){for(b=
0;b<this._promises.length;b+=1)a._chainPromise(this._promises[b]);delete this._promises}if(this._onComplete){for(b=0;b<this._onComplete.length;b+=1)a.fin(this._onComplete[b]);delete this._onComplete}}else if(a&&g(a))a.then(function(a){this.resolve(a)}.bind(this),function(a){this.reject(a)}.bind(this));else{this._hasData=!0;this._data=a;if(this._onComplete)for(b=0;b<this._onComplete.length;b++)this._onComplete[b]();if(this._promises){for(b=0;b<this._promises.length;b+=1)this._promises[b]._withInput(a);
delete this._promises}}};kew.Promise.prototype.reject=function(a){if(this._error||this._hasData)throw Error("Unable to resolve or reject the same promise twice");var b;this._error=a;this._ended&&setTimeout(function(){throw a;},0);if(this._onComplete)for(b=0;b<this._onComplete.length;b++)this._onComplete[b]();if(this._promises){for(b=0;b<this._promises.length;b+=1)this._promises[b]._withError(a);delete this._promises}};kew.Promise.prototype.then=function(a,b){var c=new kew.Promise(a,b);this._nextContext&&
c._useContext(this._nextContext);this._child?this._child._chainPromise(c):this._chainPromise(c);return c};kew.Promise.prototype.thenBound=function(a,b,c){var d=new kew.Promise(a);this._nextContext&&d._useContext(this._nextContext);d._scope=b;2<arguments.length&&(d._boundArgs=Array.prototype.slice.call(arguments,2));this._child?this._child._chainPromise(d):this._chainPromise(d);return d};kew.Promise.prototype.fail=function(a){return this.then(null,a)};kew.Promise.prototype.failBound=function(a,b,c){var d=
new kew.Promise(null,a);this._nextContext&&d._useContext(this._nextContext);d._scope=b;2<arguments.length&&(d._boundArgs=Array.prototype.slice.call(arguments,2));this._child?this._child._chainPromise(d):this._chainPromise(d);return d};kew.Promise.prototype.fin=function(a){if(this._hasData||this._error)return a(),this;this._child?this._child.fin(a):this._onComplete?this._onComplete.push(a):this._onComplete=[a];return this};kew.Promise.prototype.end=function(){this._end();return this};kew.Promise.prototype._end=
function(){if(this._error)throw this._error;this._ended=!0;return this};kew.Promise.prototype.done=function(a,b){var c=this;if(a||b)c=c.then(a,b);c._end()};kew.Promise.prototype.timeout=function(a,b){var c=new kew.Promise,d=!1,f=setTimeout(function(){c.reject(Error(b||"Promise timeout after "+a+" ms."));d=!0},a);this.then(function(a){d||(clearTimeout(f),c.resolve(a))},function(a){d||(clearTimeout(f),c.reject(a))});return c.promise};kew.Promise.prototype._withInput=function(a){if(this._successFn)try{this.resolve(this._call(this._successFn,
[a,this._currentContext]))}catch(b){this.reject(b)}else this.resolve(a);delete this._currentContext};kew.Promise.prototype._withError=function(a){if(this._failFn)try{this.resolve(this._call(this._failFn,[a,this._currentContext]))}catch(b){this.reject(b)}else this.reject(a);delete this._currentContext};kew.Promise.prototype._call=function(a,b){this._boundArgs&&(b=this._boundArgs.concat(b));return a.apply(this._scope,b)};kew.Promise.prototype._chainPromise=function(a){this._hasContext&&a._useContext(this._nextContext);
this._child?this._child._chainPromise(a):this._hasData?a._withInput(this._data):this._error?a._withError(this._error):this._promises?this._promises.push(a):this._promises=[a]};kew.Promise.prototype.makeNodeResolver=function(){return h.bind(null,this)};kew.all=function(a){1==arguments.length&&Array.isArray(a)||(a=Array.prototype.slice.call(arguments,0));if(!a.length)return k([]);for(var b=[],c=!1,d=new kew.Promise,f=a.length,e=0;e<a.length;e+=1)a[e]&&g(a[e])?a[e].then(l.bind(null,b,e)).then(function(){f--;
c||0!==f||(c=!0,d.resolve(b))},function(a){c||(c=!0,d.reject(a))}):(b[e]=a[e],f-=1);0!==f||c||(c=!0,d.resolve(b));return d};kew.defer=function(){return new kew.Promise};"undefined"!==typeof module&&(module.exports=kew)})();
