var forge=forge||require("node-forge"),keyczar_util={};
(function(){function l(a){if(a.charAt(0)!=keyczar_util.VERSION_BYTE)throw Error("Unsupported version byte: "+a.charCodeAt(0));var b=a.substr(1,keyczar_util.KEYHASH_LENGTH);a=a.substr(1+keyczar_util.KEYHASH_LENGTH);return{keyhash:b,message:a}}function m(a,b){if(a.length!=keyczar_util.KEYHASH_LENGTH)throw Error("Invalid keyhash length: "+a.length);return keyczar_util.VERSION_BYTE+a+b}function n(a,b){if(b.keyhash!=a){var c=forge.util.bytesToHex(a),d=forge.util.bytesToHex(b.keyhash);throw Error("Mismatched keyhash (primary: "+
c+" actual: "+d+")");}}function e(a){return keyczar_util.encodeBase64Url(keyczar_util._bnToBytes(a))}function p(a,b){for(var c=keyczar_util._bnToBytes(b),d=0;d<c.length&&"\x00"==c.charAt(d);)d+=1;c=c.substring(d);a.update(keyczar_util._encodeBigEndian(c.length));a.update(c)}function t(a){var b=forge.md.sha1.create();p(b,a.n);p(b,a.e);return b.digest().getBytes(keyczar_util.KEYHASH_LENGTH)}function q(a){return{modulus:e(a.n),publicExponent:e(a.e),size:a.n.bitLength()}}function r(a){var b=forge.md.sha1.create();
b.update(a);b.update(keyczar_util.VERSION_BYTE);return b}function s(a){var b={keyhash:t(a),size:a.n.bitLength(),encrypt:function(c){c=forge.pki.setRsaPublicKey(a.n,a.e).encrypt(c,"RSA-OAEP");return m(b.keyhash,c)},verify:function(c,d){d=l(d);n(b.keyhash,d);var h=r(c).digest().getBytes();return forge.pki.setRsaPublicKey(a.n,a.e).verify(h,d.message)}};return b}keyczar_util.KEYHASH_LENGTH=4;keyczar_util.VERSION_BYTE="\x00";keyczar_util._bnToBytes=function(a){a=a.toString(16);"8"<=a[0]&&(a="00"+a);return forge.util.hexToBytes(a)};
keyczar_util.decodeBase64Url=function(a){a=a.replace(/-/g,"+").replace(/_/g,"/");var b=a.length%4;if(0<b){if(1==b)throw Error("Invalid base64: incorrect input length");a+="!!==".substring(b)}return forge.util.decode64(a)};keyczar_util.encodeBase64Url=function(a){a=forge.util.encode64(a);for(var b=a.length-1;"="==a.charAt(b);)b-=1;a=a.substring(0,b+1);return a.replace(/\+/g,"-").replace(/\//g,"_")};keyczar_util._encodeBigEndian=function(a){if(!(0<=a&&2147483647>=a))throw Error("number is out of range: "+
a);if((a&4294967295)!=a)throw Error("number is not a 32-bit integer? "+a);var b=String.fromCharCode(a>>24&255),c=String.fromCharCode(a>>16&255),d=String.fromCharCode(a>>8&255);a=String.fromCharCode(a&255);return b+c+d+a};keyczar_util._decodeBigEndian=function(a){if(4>a.length)throw Error("byteString too short: "+a.length);var b=a.charCodeAt(0);if(b&128)throw Error("Cannot decode negative number; initial byte = "+b.toString(16));var b=b<<24,c=a.charCodeAt(1)<<16,d=a.charCodeAt(2)<<8;a=a.charCodeAt(3);
return b|c|d|a};keyczar_util._unpackByteStrings=function(a){for(var b=keyczar_util._decodeBigEndian(a),c=4,d=[],h=0;h<b;h++){var e=keyczar_util._decodeBigEndian(a.substring(c)),c=c+4;d.push(a.substring(c,c+e));c+=e}if(c>a.length)throw Error("Malformed input: not enough data!");return d};keyczar_util._packByteStrings=function(a){var b=[];b.push(keyczar_util._encodeBigEndian(a.length));for(var c=0;c<a.length;c++)b.push(keyczar_util._encodeBigEndian(a[c].length)),b.push(a[c]);return b.join("")};keyczar_util._rsaPublicKeyToKeyczarJson=
function(a){a=q(a);return JSON.stringify(a)};keyczar_util._base64ToBn=function(a){a=keyczar_util.decodeBase64Url(a);a=forge.util.createBuffer(a).toHex();return new forge.jsbn.BigInteger(a,16)};keyczar_util._privateKeyToKeyczarObject=function(a){a={publicKey:q(a),privateExponent:e(a.d),primeP:e(a.p),primeQ:e(a.q),primeExponentP:e(a.dP),primeExponentQ:e(a.dQ),crtCoefficient:e(a.qInv),size:a.q.bitLength()+a.p.bitLength()};if(a.size!=a.publicKey.size)throw Error("Incorrect calculation of private key size? "+
a.size+" != "+a.publicKey.size);return a};keyczar_util._rsaPrivateKeyToKeyczarJson=function(a){a=keyczar_util._privateKeyToKeyczarObject(a);return JSON.stringify(a)};keyczar_util.publicKeyFromKeyczar=function(a){var b=JSON.parse(a);a=keyczar_util._base64ToBn(b.modulus);var b=keyczar_util._base64ToBn(b.publicExponent),c=forge.pki.setRsaPublicKey(a,b);a=s(c);a.toJson=function(){return keyczar_util._rsaPublicKeyToKeyczarJson(c)};return a};keyczar_util.privateKeyFromKeyczar=function(a){var b=JSON.parse(a);
a=keyczar_util._base64ToBn(b.publicKey.modulus);var c=keyczar_util._base64ToBn(b.publicKey.publicExponent),d=keyczar_util._base64ToBn(b.privateExponent),e=keyczar_util._base64ToBn(b.primeP),k=keyczar_util._base64ToBn(b.primeQ),u=keyczar_util._base64ToBn(b.primeExponentP),v=keyczar_util._base64ToBn(b.primeExponentQ),b=keyczar_util._base64ToBn(b.crtCoefficient),f=forge.pki.setRsaPrivateKey(a,c,d,e,k,u,v,b),g=s(f);g.decrypt=function(a){a=l(a);n(g.keyhash,a);return f.decrypt(a.message,"RSA-OAEP")};g.sign=
function(a){a=r(a);a=f.sign(a);return m(g.keyhash,a)};g.exportPublicKeyJson=function(){return keyczar_util._rsaPublicKeyToKeyczarJson(f)};g.toJson=function(){return keyczar_util._rsaPrivateKeyToKeyczarJson(f)};return g};keyczar_util.aesFromKeyczar=function(a){a=JSON.parse(a);if("CBC"!=a.mode)throw Error("Unsupported cipher mode: "+a.mode);var b=keyczar_util.decodeBase64Url(a.aesKeyString);if(b.length!=a.size/8)throw Error("Mismatched key sizes: "+b.length+" != "+a.size/8);var c=keyczar_util.decodeBase64Url(a.hmacKey.hmacKeyString);
if(c.length!=a.hmacKey.size/8)throw Error("Mismatched hmac key sizes: "+c.length+" != "+a.hmacKey.size/8);return keyczar_util._aesFromBytes(b,c)};keyczar_util._aesFromBytes=function(a,b){forge.aes.createEncryptionCipher(a);var c=forge.md.sha1.create(),d=forge.hmac.create();d.start(c,b);var e=forge.md.sha1.create();e.update(keyczar_util._encodeBigEndian(a.length));e.update(a);e.update(b);var k={keyhash:e.digest().getBytes(keyczar_util.KEYHASH_LENGTH),encrypt:function(b){var c=forge.random.getBytes(a.length),
f=forge.aes.startEncrypting(a,c,null);f.update(new forge.util.ByteBuffer(b));if(!f.finish())throw Error("AES encryption failed");b=m(k.keyhash,c+f.output.getBytes());d.start(null,null);d.update(b);c=d.getMac();return b+c.getBytes()},decrypt:function(b){var e=l(b);n(k.keyhash,e);var f=b.substring(b.length-c.digestLength);d.start(null,null);d.update(b.substring(0,b.length-c.digestLength));b=d.getMac().getBytes();if(f.length!=b.length)throw Error("Invalid arguments: strings must be the same length");
for(var g=1,h=0;h<f.length;h++)g&=f.charAt(h)==b.charAt(h);if(!g)throw Error("Decryption failed: HMAC does not match");f=e.message.substring(0,a.length);e=e.message.substring(a.length,e.message.length-c.digestLength);f=forge.aes.startDecrypting(a,f,null);f.update(new forge.util.ByteBuffer(e));if(!f.finish())throw Error("Decryption failed: AES error?");return f.output.getBytes()},toJson:function(){var c={aesKeyString:keyczar_util.encodeBase64Url(a),size:8*a.length,mode:"CBC",hmacKey:{hmacKeyString:keyczar_util.encodeBase64Url(b),
size:8*b.length}};return JSON.stringify(c)},pack:function(){return keyczar_util._packByteStrings([a,b])}};return k};"undefined"!==typeof module&&module.exports&&(module.exports=keyczar_util)})();
