var __testing__={};
(function(){function B(b){b=l(b.clientData.loginUrl);var d=l(window.location.href);return b===d&&t()}var q,l;"undefined"===typeof window?(q=require("assert"),l=require("./domain").getCanonicalHost):(q=window.assert,l=window.getCanonicalHost);var h={},C=function(b){h=b},n=function(b,d){if(!h)return 0;var a=h.reject;if(!a)return 0;a=a[b];if(!a)return 0;for(var c=0;c<a.length;++c){for(var f=!1,g=0;g<a[c].length;++g){var e=a[c][g].attributeName;if(a[c][g].exactMatch)if(d[e]!==a[c][g].exactMatch){f=!1;
break}else f=!0;else if(a[c][g].regexMatch)if(d[e]&&d[e].match(a[c][g].regexMatch))f=!0;else{f=!1;break}}if(f)return-1E3}return 0},r=function(b,d){if(b){for(var a=-1,c=null,f=0;f<b.length;f++){var g=d(b[f]);g>a&&(a=g,c=b[f])}return c}return null},u=function(b,d){var a=0;if(0>n("username",b))return console.log("user: rejected ",b," due to server hint"),-1E3;a="text"===b.type||"email"===b.type?a+2:a-1E3;if(d){var c=d.itemNo-b.itemNo;0<c&&(a+=1/c)}console.log("username field=",b," score:",a);return a},
v=function(b,d){var a=r(b,function(a){return u(a,d)});return null!==a&&0<u(a)?(q("password"!==a.type),a):null},w=function(b){if(0>n("password",b))return console.log("password: rejected ",b," due to server hint"),-1E3;var d=b.value?1:0,a=b.name?b.name.toLowerCase():"",d="password"===b.type?4>=b.maxlength?d-1E3:-1!=a.indexOf("creditcard")?d-1E3:d+2:d-1E3;console.log("password field=",b," score:",d);return d},x=function(b){b=r(b,w);return null!==b&&0<w(b)?b:null},I=function(b,d,a){var c=function(b){console.log("begin scoring of ",
b);if(0>n("submit",b))return console.log("rejected ",b," due to server hint"),-1E3;if("text"===b.type||"password"===b.type)return-1E3;var c="submit"===b.type||"button"===b.type?1:0,c=c+("image"===b.type&&d?.75:0),c=c+("a"===b.type?.25:0),e=b.value?b.value.toLowerCase():"";-1!==e.indexOf("forgot")&&(c-=1E3);if("sign in"===e||"log in"===e||"log on"===e||"submit"===e||"login"===e||"go"===e)c+=2;else if(-1!=e.indexOf("sign in")||-1!=e.indexOf("log in")||-1!=e.indexOf("log on")||-1!=e.indexOf("submit")||
-1!=e.indexOf("login")||-1!=e.indexOf("go"))c+=1;a&&(e=a[0].compareDocumentPosition(b.pointer[0])&4,c+=e?1:-1);console.log("submit field field=",b," score:",c);return c};b=r(b,c);return null!==b&&0<c(b)?b:null},y=function(b){for(var d=[],a=0;a<b.length;++a){var c=$(b[a]);c.is("button")?d.push({name:c.attr("name"),id:c.attr("id"),"class":c.attr("class"),value:c.text(),type:"button",pointer:c,itemNo:a}):c.is("a")?d.push({name:c.attr("id")||c.attr("class"),id:c.attr("id"),"class":c.attr("class"),type:"a",
value:c.text(),pointer:c,itemNo:a}):d.push({name:c.attr("name"),id:c.attr("id"),"class":c.attr("class"),value:"image"===c.attr("type")?c.attr("alt"):c.prop("value"),type:c.attr("type")||"text",maxlength:parseInt(c.attr("maxlength"),10),pointer:c,itemNo:a})}return d},s=function(b,d){console.log("trying to get login form from ",$(b));"undefined"===typeof d&&(d=!0);var a=$(b).find("input[type!=hidden],button[type!=hidden],a");if(d){var a=a.filter(":visible"),c=$(b).find("input[type!=hidden]:visible,button[type!=hidden]:visible,a:visible");
q(a.length===c.length);for(var a=[],f=0;f<c.length;++f){var g=c[f],e=g.getBoundingClientRect();0<=e.bottom&&0<=e.right?a.push(g):console.log("rejected element ",g," because it is outside the viewport")}}if(h&&h.additional_submit_button_ids)for(f=0;f<h.additional_submit_button_ids.length;++f)q(-1===h.additional_submit_button_ids[f].indexOf(" ")),a=a.add($("#"+h.additional_submit_button_ids[f]));a=y(a);c=x(a);f=null;g=!!c;c?f=v(a,c):h.empty_password_username_selector&&(e=$(h.empty_password_username_selector))&&
(f=y(e)[0],g=f.emptyPasswordPermitted=!0);if(g=g&&(h.allow_empty_username||null!==f)){g=I(a,!0,f&&f.pointer);e=y((c?c:f).pointer.closest("form"));if(!e)return null;e=e[0];return 0>n("form",e)?(console.log("rejected ",e," due to server hint"),null):{usernameField:f,passwordField:c,submitField:g,allFields:a,formDict:e,id:b.id}}return null},D=["login","log in","log on","signin","sign in"],E="signup;sign up;join;create;register;start;free;trial".split(";"),F=["login","signin"],G=["signup","regist"],p=
function(b){console.log("trying to guess login form");var d=function(c){if(0>n("form",c.formDict))return console.log("rejected ",c.formDict," due to server hint"),-1E3;if(!c)return 0;var a=0;b&&c.usernameField&&c.usernameField.name===b.clientData.usernameField&&c.passwordField&&c.passwordField.name===b.clientData.passwordField&&(a+=100);c.usernameField&&(a+=u(c.usernameField));if(c.passwordField||!c.usernameField.emptyPasswordPermitted)a+=w(c.passwordField);var d;d=c.submitField;var e=0;if(0>n("login_submit",
d))console.log("rejected ",d," due to server hint"),d=-1E3;else{if(d&&d.value){var m=d.value.toLowerCase(),k;for(k=0;k<D.length;++k){var h=D[k];-1!==m.indexOf(h)&&(e+=2)}for(k=0;k<E.length;++k)h=E[k],-1!==m.indexOf(h)&&(e-=1E3)}console.log("submit button score ",d," score ",e);d=e}a+=d;e=c.id;d=0;if(e){e=e.toLowerCase();for(m=0;m<F.length;++m)k=F[m],-1!==e.indexOf(k)&&(d+=1);if(0===d)for(m=0;m<G.length;++m)k=G[m],-1!==e.indexOf(k)&&(d-=1E3)}a+=d;d=c.allFields;for(m=e=0;m<d.length;++m)"password"===
d[m].type&&++e;1<e&&(a-=1E3);console.log("FORM FOR ",c," SCORE:",a);return a},a=$("form").map(function(){console.log("mapping for ",this);return s(this)});if((a=r(a,d))&&0>d(a))return null;a&&h&&h.highlightSelectedForms&&(a.usernameField&&a.usernameField.pointer.css({"border-color":"#0000ff","border-width":"10px","border-style":"dotted"}),a.passwordField.pointer.css({"border-color":"#00ff00","border-width":"10px","border-style":"dotted"}),a.submitField&&a.submitField.pointer.css({"border-color":"#ff0000",
"border-width":"10px","border-style":"dotted"}));return a},H=function(b){return null!==s(b)},t=function(){return null!==p()},z=function(b){var d=l(b.loginUrl),a=l(document.URL);if(d!==a)throw"Domain mismatch: "+a+", expected: "+d;var c=b.usernameField?b.usernameField.value:null,f=b.passwordField?b.passwordField.value:null;setTimeout(function(){var a=function(a){console.log("dispatching event");var b=new KeyboardEvent("keydown");b.keyCode=13;document.querySelector("#"+a).dispatchEvent(b);b=new KeyboardEvent("keypress");
b.keyCode=13;document.querySelector("#"+a).dispatchEvent(b);b=new KeyboardEvent("keyup");b.keyCode=13;document.querySelector("#"+a).dispatchEvent(b)},d=b.usernameField?b.usernameField.pointer:b.usernameField;if(d){var h=d.closest("form");d.val(c);var k=d.attr("id");k||(k="MITRO____184379378465893",d.attr("id",k));setTimeout(function(){a(k)},10)}if(b.passwordField){var l=b.passwordField.pointer;q("password"===l.attr("type"));var n=l.closest("form");l.val(f);helper.preventAutoFill(l,n);var p=l.attr("id");
p||(p="MITRO____184379378465894",l.attr("id",p));setTimeout(function(){a(p)},20);$(n[0]).attr("autocomplete","off");d&&d.attr("autocomplete","off");l.attr("autocomplete","off")}setTimeout(function(){var a=b.submitField;if(a){try{a.pointer.prop("disabled",!1)}catch(c){console.log(c)}a.pointer[0].click()}else try{n[0].submit()}catch(d){if(d instanceof TypeError)try{n[0].submit.click()}catch(e){h.find(":submit").click()}}},300)},200)},A=function(b){var d=p(b);if(!d)return console.log("login form not found"),
!1;d.loginUrl=b.clientData.loginUrl;d.usernameField&&(d.usernameField.value=b.clientData.username);d.passwordField&&(d.passwordField.value=b.criticalData.password);z(d);return!0};__testing__.findAndSubmitLoginForm=function(b,d){console.log("hello",document.URL,l(document.URL));var a={clientData:{loginUrl:document.URL,username:b},criticalData:{password:d}};console.log("sending data",a);return A(a)};__testing__.guessLoginForm=function(b,d){console.log("hello",document.URL,l(document.URL));var a=p({clientData:{loginUrl:document.URL,
username:b},criticalData:{password:d}});if(!a)return null;a.usernameField.pointer=null;a.passwordField.pointer=null;a.submitField.pointer=null;delete a.formDict;delete a.allFields;return a};"undefined"!==typeof module&&module.exports?(module.exports.guessUsernameField=v,module.exports.guessPasswordField=x,module.exports.getLoginForm=s,module.exports.guessLoginForm=p,module.exports.isLoginPageForService=B,module.exports.isLoginPage=t,module.exports.isLoginForm=H,module.exports.fillLoginForm=z,module.exports.setServerHints=
C,module.exports.guessAndFillLoginForm=A):(window.guessUsernameField=v,window.guessPasswordField=x,window.getLoginForm=s,window.guessLoginForm=p,window.isLoginPageForService=B,window.isLoginPage=t,window.isLoginForm=H,window.fillLoginForm=z,window.setServerHints=C,window.guessAndFillLoginForm=A)})();
