var keyczar=keyczar||require("keyczarjs"),mitro=mitro||{},forge=forge||require("node-forge");
(function(){function J(b,d,f,e){return K(b,d,f,e,function(b,d){return b-d})}function K(b,d,f,e,k){b.sort(k);d.sort(k);for(var m=k=0;k<b.length&&m<d.length;)b[k]<d[m]?(e.push(b[k]),++k):(b[k]>d[m]?f.push(d[m]):++k,++m);for(;k<b.length;++k)e.push(b[k]);for(;m<d.length;++m)f.push(d[m]);return 0!=e.length+f.length}function L(b,d,f,e,k,m,p){mitro.lib.AddIdentity({uid:b,password:d,analyticsId:f,server_host:e,server_port:k,_keyCache:v,_createPrivateGroup:!0,deviceId:D},function(d){try{var f=M(b,d.verified,
d.unsignedLoginToken,d.privateKey,!1,e,k,d.privateGroupId);f.retrieveDeviceSpecificKey(function(){m(f)},p)}catch(r){console.log(r),p(mitro.lib.makeLocalException(r))}},p)}function N(b,d,f,e,k,m,p){return E(b,d,void 0,f,e,k,m,p)}function E(b,d,f,e,k,m,p,t){return F(b,d,f,e,k,null,m,p,t)}function F(b,d,f,e,k,m,p,t,n){mitro.lib.clearCaches();f||(f={});f={uid:b,server_host:e,server_port:k,loginToken:f.loginToken,twoFactorCode:p,loginTokenSignature:f.loginTokenSignature,deviceId:D,automatic:!!m};z(mitro.lib.GetPrivateKey)(f,
function(f){try{var p=null;if(!d&&f.deviceKeyString&&m)var c=keyczar.fromJson(f.deviceKeyString),p=B().decryptWith(m,c);p||(p=B().loadFromJson(f.encryptedPrivateKey,d));var r=M(b,f.verified,f.unsignedLoginToken,p,f.changePasswordOnNextLogin,e,k);r.listSites(function(c){console.log("*** successfully logged in to ",r.getUid());r.retrieveDeviceSpecificKey(function(){r.listGroups(function(c){t(r)},n)},n)},n)}catch(q){console.log(q),n(mitro.lib.makeLocalException(q))}},n)}function M(b,d,f,e,k,m,p,t){function n(a){return{uid:b,
_privateKey:e,server_host:m,server_port:p,_transactionSpecificData:a,_keyCache:v,deviceId:D}}function q(a){var g={};return a&&"[object Function]"===g.toString.call(a)}r(keyczar);void 0===t&&(t=null);var y=null;f&&(console.log("mitro_fe createIdentity got token:",f),y={loginToken:f,loginTokenSignature:e.sign(f)});var c={uid:b,holdingTransaction:{}};f=new A(n);c.mitroclient=new mitro.Client(f);var s=null;c.getPrivateKeyStringForLocalDisk=function(){return s?e.encryptWith(s):null};c.setDeviceSpecificKeyFromString=
function(a){s=a?keyczar.fromJson(a):null};c.getPrivateKeyStringForLocalDiskAsync=function(a){a(s?e.encryptWith(s):null)};c.holdingTransaction.retrieveDeviceSpecificKey=function(a,g,l){try{var h=n(a);z(mitro.lib.RetrieveDeviceSpecificKey)(h,function(a){try{c.setDeviceSpecificKeyFromString(a.deviceKeyString),g()}catch(h){l(mitro.lib.makeLocalException(h))}},l)}catch(H){l(mitro.lib.makeLocalException(H))}};c.signMessage=function(a){return e.sign(a)};c.getLoginToken=function(){return y};c.signMessageAsync=
function(a,g,l){try{g(e.sign(a))}catch(h){l(mitro.lib.makeLocalException(h))}};c.getLoginTokenAsync=function(a,g){a(y)};c.isVerified=function(){return d};c.getUid=function(){return b};c.shouldChangePassword=function(){return k};c.isVerifiedAsync=function(a){a(d)};c.getUidAsync=function(a){a(b)};c.shouldChangePasswordAsync=function(a){a(k)};c.holdingTransaction.editSitePassword=function(a,g,l,h,H){c.holdingTransaction.getSiteData(a,g,!0,function(b){try{c.holdingTransaction.mutateSecret(a,g,b.serverData,
b.clientData,{password:l,oldPassword:b.criticalData.password},h,H)}catch(u){H(mitro.lib.makeLocalException(u))}},H)};c.holdingTransaction.mutateSite=function(a,g,l,h,b,d,u,f,e){l=E(l,h,b,d,u);return c.holdingTransaction.mutateSecret(a,g,null,l[0],l[1],f,e)};c.holdingTransaction.mutateSecret=function(a,g,l,h,b,d,u){var f=[[c.holdingTransaction.getSiteData,[a,g,!0]]];l&&(l.secretId=g,f.push([c.holdingTransaction.editServerSecret,[a,l]]));mitro.lib.batch(f,function(l){try{var c=l[0],f=c.groups.concat(c.hiddenGroups);
console.log("all groups:",f);l={};for(var P in f){var e=f[P],k=B().loadFromJson(c.groupIdToPublicKeyMap[e]);l[e]={encryptedClientData:k.encrypt(JSON.stringify(h))};b&&(l[e].encryptedCriticalData=k.encrypt(JSON.stringify(b)))}c={secretId:g,groupIdToEncryptedData:l};a.implicitEndTransaction=!0;mitro.lib.PostToMitro(c,n(a),"/mitro-core/api/EditSecretContent",d,u)}catch(m){console.log(m.message),console.log(m.stack),u(mitro.lib.makeLocalException(m))}},u)};c.holdingTransaction.removePendingGroups=function(a,
g,l,h){try{mitro.lib.PostToMitro({scope:g},n(a),"/mitro-core/api/RemovePendingGroupApprovals",l,h)}catch(c){console.log(c.stack),h(mitro.lib.makeLocalException(c))}};c.holdingTransaction.editServerSecret=function(a,g,l,h){try{var c={};r(void 0!==g.isViewable);c.isViewable=g.isViewable;c.secretId=g.secretId;mitro.lib.PostToMitro(c,n(a),"/mitro-core/api/EditSecret",l,h)}catch(b){h(mitro.lib.makeLocalException(b))}};c.holdingTransaction.getPendingGroups=function(a,g,l,h){try{mitro.lib.PostToMitro({scope:g},
n(a),"/mitro-core/api/GetPendingGroups",l,h)}catch(c){console.log("error getting groups:",c.stack),h(mitro.lib.makeLocalException(c))}};c.holdingTransaction.getOrganizationState=function(a,g,l,h){try{z(mitro.lib.GetOrganizationState)(n(a),{orgId:g},function(a){var h=a.orgSecretsToPath,g;for(g in a.orgSecretsToPath)h[g].encryptedClientData&&(mitro.lib.decryptSecretWithGroups(h[g],a.groups,e),h[g].clientData=JSON.parse(h[g].clientData)),h[g].hints={},h[g].hints.icons=h[g].icons,h[g].hints.title=h[g].title;
l(a)},h)}catch(c){console.log("error getting org state:",c.stack),h(mitro.lib.makeLocalException(c))}};c.holdingTransaction.applyPendingGroups=function(a,g,l,h){try{var b=g.scope,f=g.nonce;c.holdingTransaction.getPendingGroups(a,b,function(d){if(d.syncNonce!==f)h("Your sync information is stale, please refresh the page.");else try{console.log("got approvals!");for(var e=[],u={},k=0;k<d.pendingAdditionsAndModifications.length;++k){var n=d.pendingAdditionsAndModifications[k],m=JSON.parse(n.memberListJson);
r(m.groupName===n.groupName);r(!b||n.scope===b);u[n.scope]=!0;var w={},p=m.memberList,t;for(t in p)w[p[t]]="MODIFY_SECRETS_BUT_NOT_MEMBERSHIP";var q;n.matchedGroup?(r(n.matchedGroup.name===n.groupName),r(n.matchedGroup.scope===n.scope),q=n.matchedGroup.groupId):(e.push([c.holdingTransaction.addGroupWithScope,[a,n.groupName,n.scope,!1]]),q=void 0);e.push([c.holdingTransaction.mutateGroupWithScopesAndPermissions,[a,q,null,[d.orgId],p,n.scope,{},w]])}for(k=0;k<d.pendingDeletions.length;++k)e.push([c.holdingTransaction.removeGroup,
[a,d.pendingDeletions[k].groupId]]);for(var v in u)e.push([c.holdingTransaction.removePendingGroups,[a,v]]);var s=new mitro.MutateOrganizationClientRequest;s.orgId=d.orgId;s.newMembers=d.newOrgMembers;g.removeUsersFromOrg&&(s.membersToRemove=d.deletedOrgMemers);(s.membersToRemove.length||s.newMembers.length)&&e.push([c.holdingTransaction.mutateOrganization,[a,s]]);mitro.lib.series(e,l,h)}catch(y){h(mitro.lib.makeLocalException(y))}},h)}catch(d){h(mitro.lib.makeLocalException(d))}};c.holdingTransaction.checkTwoFactor=
function(a,g,l){a=n(a);a.loginToken=y.loginToken;a.loginTokenSignature=y.loginTokenSignature;try{mitro.lib.checkTwoFactor(a,function(a){g(a.twoFactorUrl)},l)}catch(h){l(mitro.lib.makeLocalException(h))}};c.holdingTransaction.mutatePrivateKeyPassword=function(a,g,l,h,c,b){var d=n(a);d.loginToken=y.loginToken;d.loginTokenSignature=y.loginTokenSignature;mitro.lib.GetPrivateKey(d,function(d){try{var f=B().loadFromJson(d.encryptedPrivateKey,g).toJsonEncrypted(l);mitro.lib.EditEncryptedPrivateKey(n(a),
h,f,function(a){k=!1;c(a)},b)}catch(e){b(mitro.lib.makeLocalException(e))}})};c.holdingTransaction.mutatePrivateKeyPasswordWithoutOldPassword=function(a,g,l,h){try{var c=e.toJsonEncrypted(g.newPassword);mitro.lib.EditEncryptedPrivateKey(n(a),g.up,c,function(a){k=!1;l(a)},h)}catch(b){h(mitro.lib.makeLocalException(b))}};c.holdingTransaction.addSecret=function(a,g,l,h,c,b){a=n(a);a.gid=t;a._=[null,g,JSON.stringify(l),JSON.stringify(h)];mitro.lib.AddSecret(a,function(a){c(a.secretId)},b)};c.holdingTransaction.addSecrets=
function(a,g,l,h){a=n(a);g.clientData=JSON.stringify(g.clientData);g.criticalData=JSON.stringify(g.criticalData);console.log("mitro_fe addSecrets",g.groupIds);mitro.lib.AddSecrets(a,g,l,h)};var E=function(a,g,l,h,c){return[{loginUrl:a,username:g,usernameField:h,passwordField:c},{password:l}]};c.holdingTransaction.addSite=function(a,g,l,h,b,d,f,e){l=E(g,l,h,b,d);return c.holdingTransaction.addSecret(a,g,l[0],l[1],f,e)};c.holdingTransaction.shareSite=function(a,g,l,h,b,d){return c.holdingTransaction.shareSiteAndOptionallySetOrg(a,
g,l,h,null,b,d)};c.holdingTransaction.shareSiteAndOptionallySetOrg=function(a,g,l,h,d,f,e){r(g);mitro.lib.parallel([[c.holdingTransaction.getSiteSecretData,[a,g]]],function(k){var m=k[0].owningOrgId;m&&!d?d=m:m&&r(d===m);var p=0,m=[],q=[],s=function(a,h,g){q.push(a);h(a)};if(null===l&&null===h)r(!1);else if(0===l.length&&(0===h.length||1===h.length&&h[0]===b))console.log("mitro_lib shareSiteAndOptionallySetOrg: desired final ACL is empty"),d&&c.organizations[d]&&c.organizations[d].privateOrgGroupId?
(console.log("mitro_lib shareSiteAndOptionallySetOrg: using org private group"),l=[c.organizations[d].privateOrgGroupId]):(console.log("mitro_lib shareSiteAndOptionallySetOrg: using non-org private group"),l=[t]);else{n(a).secretId=g;for(var p=!0,x=0;x<h.length;++x)if(b===h[x]){p=!1;break}p&&h.push(b);p=1;x=[];d&&(x=[d]);var w=K(k[0].users,h,[],[]);k[0].owningOrgId!==d||w?(console.log(" *** Mutation results in a different set of users or has org changes. We must create new groups, ugh."),m.push([c.holdingTransaction._addGroup,
[a,"hidden group "+g,!0]]),m.push([c.holdingTransaction.mutateGroup,[a,void 0,null,x,h]]),m.push([s,[void 0]])):(l=l.concat(k[0].hiddenGroups),console.log(" *** Mutation didn't change user list; don't need to create new groups!"))}s=k[0].groups;s=s.concat(k[0].hiddenGroups);x=[];if(d){w=!0;for(k=0;k<l.length;++k)if(parseInt(l[k],10)===parseInt(d,10)){w=!1;break}w&&(l.push(d),console.log("mitro_lib shareSiteAndOptionallySetOrg: FORCE-adding org group id to ACL"))}J(s,l,q,x);m.push([mitro.lib.AddSecrets,
[n(a),{groupIds:q,secretId:g}]]);for(k=0;k<x.length;++k)w=n(a),w.secretId=g,w._=[null,g],w.gid=x[k],m.push([mitro.lib.RemoveSecret,[w]]);p+=s.length-x.length+q.length;r(!0===0<p);mitro.lib.series(m,f,e)},e)};c.holdingTransaction.getGroup=function(a,g,l,h){a=n(a);a.gid=g;mitro.lib.GetGroup(a,l,h)};c.holdingTransaction.mutateGroup=function(a,g,l,h,b,d,f){return c.holdingTransaction.mutateGroupWithScopesAndPermissions(a,g,l,h,b,null,{},{},d,f)};c.holdingTransaction.mutateGroupWithScopesAndPermissions=
function(a,g,l,h,c,b,d,f,e,k){try{console.log(">>> fe.mutategroup");r(g);h||(h=[]);r(1>=h.length);var m=n(a);mitro.lib.GetUserAndGroupPublicKeys(m,!0,c,h,function(a){m.gid=g;m.orgId=null!==h?h[0]:null;mitro.lib.MutateMembership(m,function(g,c,d){var e;d=null;r(null===l||"string"===typeof l);null!==l&&(g.name=l);var k=[],m=null;for(e in g.acls)if(g.acls[e].memberIdentity)if(void 0===a.userIdToPublicKey[g.acls[e].memberIdentity])d=!0;else{var n=f[g.acls[e].memberIdentity];n&&n!=g.acls[e].level&&console.log("mutating permission from ",
g.acls[e].level," to ",n," for ",g.acls[e].memberIdentity);g.acls[e].level=n?n:g.acls[e].level;k.push(g.acls[e]);delete a.userIdToPublicKey[g.acls[e].memberIdentity]}else 0===h.length&&h.push(g.acls[e].memberGroup),r(g.acls[e].memberGroup==h[0]),m=g.acls[e];for(var u in a.userIdToPublicKey)e=B().loadFromJson(a.userIdToPublicKey[u]),k.push({myPublicKey:a.userIdToPublicKey[u],level:f[u]?f[u]:"ADMIN",groupKeyEncryptedForMe:e.encrypt(c.toJson()),memberIdentity:u});!m&&h&&h.length?(e=B().loadFromJson(a.groupIdToPublicKey[h[0]]),
k.push({myPublicKey:a.groupIdToPublicKey[h[0]],level:"ADMIN",groupKeyEncryptedForMe:e.encrypt(c.toJson()),memberGroup:h[0]})):m&&k.push(m);b&&r(g.scope==b);g.acls=k;d||(g.secrets=null);return d},function(a){e(a.groupId)},k)},k)}catch(p){k(mitro.lib.makeLocalException(p))}};c.holdingTransaction.getPublicKeys=function(a,g,l,h){mitro.lib.GetPublicKeys(n(a),g,l,h)};c.holdingTransaction._addGroup=function(a,g,l,h,b){return c.holdingTransaction.addGroupWithScope(a,g,null,l,h,b)};c.holdingTransaction.addGroupWithScope=
function(a,g,l,h,c,b){try{console.log("in addgroup with args: ",a,g,l,h);if(null===t){if(""!==g)throw Error("No private group id; must create a group without name first");}else if(""===g)throw Error("Empty group names are not permitted");var d=n(a);d.scope=l;d._=[null,g];d.autoDelete=h;mitro.lib.AddGroup(d,function(a){null===t&&(t=a.groupId);c(a.groupId)},b)}catch(e){b(e)}};c.holdingTransaction.addGroup=function(a,g,l,h){return c.holdingTransaction._addGroup(a,g,!1,l,h)};c.holdingTransaction.deleteSecret=
function(a,g,c,h){try{mitro.lib.PostToMitro({secretId:g,groupId:null},n(a),"/mitro-core/api/RemoveSecret",c,h)}catch(b){console.log(b.stack),h({local_exception:b})}};c.holdingTransaction.removeGroup=function(a,g,c,h){try{mitro.lib.PostToMitro({groupId:g},n(a),"/mitro-core/api/DeleteGroup",c,h)}catch(b){console.log(b.stack),h(mitro.lib.makeLocalException(b))}};var F=function(a){var g=mitro.fe.convertListSitesToExtension(a);if(null===t){for(var c in a.groups){var h=a.groups[c];if(h.isNonOrgPrivateGroup){t=
h.groupId;break}}if(null===t)throw Error("Could not find the private group for identity "+b);}return g};c.holdingTransaction.listSites=function(a,g,c){a=n(a);z(mitro.lib.ListGroupsAndSecrets)(a,function(a){try{g(F(a))}catch(b){console.log("Error:",b),c(mitro.lib.makeLocalException(b))}},c)};c.getDefaultOrgId=function(){if(c.organizations){var a=null,g;for(g in c.organizations){var b=c.organizations[g];if(b.isAdmin){a=b.id;break}else null===a&&(a=b.id)}return a}return null};c.getOrgInfo=function(a,
g){var b={};console.log("mitro_fe getOrgInfo(): returning stored state");b.myOrgId=c.getDefaultOrgId();b.organizations=c.organizations;a(b)};var G=function(a){var g=a.groups,d=a.organizations;c.organizations={};var h={},e;for(e in g){var f=g[e];f.isNonOrgPrivateGroup||(f.isOrgPrivateGroup&&(f.name=b,c.organizations[f.owningOrgId]={id:f.owningOrgId,name:f.owningOrgName,privateOrgGroupId:f.groupId,isAdmin:!1}),h[f.groupId]=f)}for(var k in d)a.organizations[k].isRequestorAnOrgAdmin&&(c.organizations[k].isAdmin=
!0);return h};c.holdingTransaction.listGroups=function(a,g,b){a=n(a);z(mitro.lib.ListGroupsAndSecrets)(a,function(a){g(G(a))},b)};c.holdingTransaction.listUsers=function(a,g,b){a=n(a);z(mitro.lib.ListGroupsAndSecrets)(a,function(a){g(a.autocompleteUsers)},b)};c.holdingTransaction.listUsersGroupsAndSecrets=function(a,g,b){a=n(a);z(mitro.lib.ListGroupsAndSecrets)(a,function(a){try{var c={users:a.autocompleteUsers,secrets:F(a),groups:G(a)};g(c)}catch(d){b(mitro.lib.makeLocalException(d))}},b)};c.holdingTransaction.addSiteToOrg=
function(a,g,b,h,d){try{c.holdingTransaction.getSiteData(a,g,!1,function(e){try{r(!e.owningOrgId);for(var f=[],k=0;k<e.groups.length;++k)f.push(e.groups[k].groupId);c.holdingTransaction.shareSiteAndOptionallySetOrg(a,g,f,e.users,b,h,d)}catch(m){d(mitro.lib.makeLocalException(m))}},d)}catch(e){d(mitro.lib.makeLocalException(e))}};c.holdingTransaction.getSiteSecretData=function(a,g,b,d){return c.holdingTransaction.getSiteData(a,g,"true",b,d)};c.holdingTransaction.getSiteSecretDataForDisplay=function(a,
b,d,h){return c.holdingTransaction.getSiteData(a,b,"display",d,h)};c.holdingTransaction.getSiteData=function(a,b,c,d,e){c=c.toString();r(c in{"true":1,"false":1,display:1});a=n(a);a._=[null,b];a.includeCriticalData=c;z(mitro.lib.GetSecret)(a,function(a){var b={};b.secretId=a.secretId;b.clientData=JSON.parse(a.clientData);if("true"===c||"display"===c)b.criticalData=JSON.parse(a.criticalData);b.hints={};b.hints.icons=a.icons;b.hints.title=a.title;b.groups=a.groups;b.users=a.users;b.hiddenGroups=a.hiddenGroups;
b.groupNames=a.groupNames;b.groupMap=a.groupMap;b.owningOrgId=a.owningOrgId;b.owningOrgName="number"===typeof b.owningOrgId?b.groupNames[b.owningOrgId]:void 0;b.canEditServerSecret=a.canEditServerSecret;b.isViewable=a.isViewable;b.creator=a.creator;b.groupIdToPublicKeyMap=a.groupIdToPublicKeyMap;d(b)},e)};c.holdingTransaction.getAuditLog=function(a,b,d,h){var e=n(a);e.orgId=b.orgId;e.offset=b.offset;e.limit=b.limit;e.startTimeMs=b.startTimeMs;e.endTimeMs=b.endTimeMs;var f=function(a,b,c,g){for(var d=
a.events,h=0;h<d.length;h++){var e=d[h],f=b[e.secretId];f&&(e.secretTitle=f.clientData&&null!==f.clientData.title&&void 0!==f.clientData.title?f.clientData.title:f.hints&&f.hints.title?f.hints.title:f.clientData?getCanonicalHost(f.clientData.loginUrl)||"":"");if(f=c[e.groupId])e.groupName=f.name}g(a)};mitro.lib.GetAuditLog(e,function(e){null===b.orgId?c.holdingTransaction.listSites(a,function(b){c.holdingTransaction.listGroups(a,function(a){for(var c={},g=0;g<b.length;g++)c[b[g].secretId]=b[g];f(e,
c,a,d)},h)},h):c.holdingTransaction.getOrganizationState(a,b.orgId,function(a){var b=a.orgSecretsToPath,c;for(c in a.orphanedSecretsToPath)b[c]=a.orphanedSecretsToPath[c];f(e,b,a.groups,d)},h)},h)};c.holdingTransaction.createOrganization=function(a,b,d,e){c.mitroclient.createOrganization(b.name,b.owners,b.members,function(){mitro.lib.clearCaches();var b=Array.prototype.slice.call(arguments);c.holdingTransaction.listGroups(a,function(){d.apply(void 0,b)},e)},e)};c.holdingTransaction.mutateOrganization=
function(a,b,d,e){c.mitroclient.mutateOrganization(b,a,d,e)};c.holdingTransaction.changeRemotePassword=function(a,d,e,h){c.holdingTransaction.getSiteData(a,d.secretId,!0,function(a){try{var f=a.criticalData;f.oldPassword=f.password;f.password=d.newPassword;var k=JSON.stringify({secretId:d.secretId,userId:b,criticalData:f}),m=c.signMessage(k);mitro.lib.PostToMitroAgent({dataFromUser:k,dataFromUserSignature:m,url:a.clientData.loginUrl,username:a.clientData.username,oldCriticalData:f},"/ChangePassword",
e,h)}catch(n){h(mitro.lib.makeLocalException(n))}},h)};f=function(a,c){return"createIdentity"===a||"listSecrets"===a||"listUsers"===a||"listUsersGroupsAndSecrets"===a||"listGroups"===a||"listSites"===a||"retrieveDeviceSpecificKey"===a||"getSiteData"===a||"getSiteSecretData"===a||"createOrganization"===a||"getOrganizationState"===a?function(){var a=Array.prototype.slice.call(arguments);a.unshift({id:null,isWriteOperation:!1});c.apply(void 0,a)}:Q(function(){var d=Array.prototype.slice.call(arguments),
e=d.pop(),f=d.pop();q(e)||(console.log(e),console.log(a),r(q(e)));var k=0===a.indexOf("add")||0===a.indexOf("mutate")||0===a.indexOf("remove")||0===a.indexOf("edit")||0===a.indexOf("rm")||0===a.indexOf("create")||0===a.indexOf("delete")||0===a.indexOf("apply")||0===a.indexOf("share");r(q(f));var m=n();r(void 0===m.transactionSpecificData);var p={id:null,isWriteOperation:k,implicitBeginTransaction:!0,operationName:a},t=function(a){console.log("ERROR IN TRANSACTION CODE:",a);mitro.lib.clearCaches();
mitro.lib.postEndTransaction(p);var c=n();c.type="exception";c.description=JSON.stringify(a);c.email=b;c.url="";e(a)};d.unshift(p);d.push(function(a){var b=function(){k&&(mitro.lib.clearCaches(),mitro.lib.postEndTransaction(p));f(a)};p.id&&(p.implicitEndTransaction?(console.log("transaction already closed: ",p),b()):(console.log("trying to close transaction with data:",p),mitro.lib.PostToMitro({},n(p),"/mitro-core/api/EndTransaction",b,t)))});d.push(t);c.apply(void 0,d)})};for(var C in c.holdingTransaction)c[C]=
f(C,c.holdingTransaction[C]);return c}mitro.fe={};var v=null;if("undefined"!==typeof module&&module.exports){mitro={lib:require("./mitro_lib.js"),keycache:require("./keycache"),fs:require("fs"),log:require("./logging")};var s=require("./mitroclient");mitro.Client=s.Client;module.exports=mitro.fe={};mitro.fe.initCacheFromFile=function(b){try{v=mitro.keycache.MakeKeyCache(),v.loadFromJson(mitro.fs.readFileSync(b)),console.log("loaded "+v.size()+" keys")}catch(d){console.log("could not read from key cache file "+
b+"... using default"),console.log(d),console.log(d.stack)}};mitro.fe.startCacheFiller=function(){v=mitro.keycache.MakeKeyCache();mitro.keycache.startFiller(v)};mitro.fe.initCacheFromJson=function(b){v=mitro.keycache.MakeKeyCache();v.loadFromJson(b)}}mitro.fe.getRandomness=function(b,d){console.log("WARNING: no randomness source supported");b({seed:""})};mitro.fe.setKeyCache=function(b){v=b};var q=mitro.fe,r=function(b){if(!b)throw Error("Assertion failed");},B=function(){return mitro.lib.getCrypto()};
mitro.fe.convertListSitesToExtension=function(b){var d=[],f;for(f in b.secretToPath){var e={};e.clientData=JSON.parse(b.secretToPath[f].clientData);e.secretId=b.secretToPath[f].secretId;e.owningOrgId=b.secretToPath[f].owningOrgId;e.owningOrgName=b.secretToPath[f].owningOrgName;e.groups=b.secretToPath[f].groups;e.users=b.secretToPath[f].users;e.hints={};e.hints.icons=b.secretToPath[f].icons;e.hints.title=b.secretToPath[f].title;for(var k={},m=0;m<e.users.length;++m)k[e.users[m]]=1;for(m=0;m<e.groups.length;++m){var p=
b.groups[e.groups[m]];if(p)for(var q=0;q<p.users.length;++q)k[p.users[q]]=1}e.flattenedUsers=Object.keys(k);d.push(e)}return d};var G=null,C=null,D=null,Q=function(b){return function(){var d=3,f=Array.prototype.slice.call(arguments),e=f.pop(),k=f.pop(),m=JSON.parse(JSON.stringify(f)),f=JSON.parse(JSON.stringify(m)),p=function(f){try{if("RetryTransactionException"===f.exceptionType){var n=2E3*Math.random()+1E3;console.log("retrying operation after ",n," ms");setTimeout(function(){var f=JSON.parse(JSON.stringify(m));
f.push(k);f.push(0>--d?e:p);b.apply(void 0,f)},n)}else e(f)}catch(q){e(mitro.lib.makeLocalException(q))}};f.push(k);f.push(p);b.apply(void 0,f)}},z=function(b){return function(){var d=Array.prototype.slice.call(arguments),f=d.pop();d.push(function(e){var k=!G||!C||d[0]._transactionSpecificData&&d[0]._transactionSpecificData.id||d[0]._transactionSpecificData&&d[0]._transactionSpecificData.isWriteOperation;(k=(k=k||400<=e.status&&500>e.status)||e&&("DoTwoFactorAuthException"===e.exceptionType||"UnverifiedUserException"===
e.exceptionType))?(console.log("could not retry on backup."),f(e)):(console.log("retrying on backup due to ",e),d[0].server_host=G,d[0].server_port=C,d.pop(),d.push(f),b.apply(void 0,d))});b.apply(void 0,d)}},A=function(b){this.makeArgs=b};A.prototype.getPublicKeys=function(b,d,f,e){d=this.makeArgs(d);d.addMissingUsers=!0;b.sort();mitro.lib.GetPublicKeys(d,b,function(b){0!==b.missingUsers.length?e(Error("LegacyAPIImplementation.getPublicKeys: missing users: "+b.missingUsers.length)):f(b.userIdToPublicKey)},
e)};A.prototype.cryptoLoadFromJson=function(b){return B().loadFromJson(b)};A.prototype.postSigned=function(b,d,f,e,k){f=this.makeArgs(f);mitro.lib.PostToMitro(d,f,b,e,k)};A.prototype.getNewRSAKeysAsync=function(b,d,f){v.getNewRSAKeysAsync(b,d,f)};A.prototype.getGroup=function(b,d,f,e){d=this.makeArgs(d);d.gid=b;mitro.lib.GetGroup(d,f,e)};A.prototype.getIdentity=function(){return this.makeArgs().uid};A.prototype.decrypt=function(b){return this.makeArgs()._privateKey.decrypt(b)};q.setFailover=function(b,
d){G=b;C=d};q.setDeviceId=function(b){D=b};q.getDeviceId=function(){return D};q.getDeviceIdAsync=function(b){b(D)};var I={},O=0,s=function(b){return function(){var d=Array.prototype.slice.call(arguments),f=d.pop(),e=d.pop(),k=function(b){I[++O]=b;var d=JSON.stringify({email:b.uid,nonce:Math.random().toString(36).substring(7)}),f=b.signMessage(d),d="/mitro-core/TwoFactorAuth/TFAPreferences?user="+encodeURIComponent(b.getUid())+"&token="+encodeURIComponent(d)+"&signature="+encodeURIComponent(f);e({identityId:O,
uid:b.getUid(),tfaAccessUrlPath:d,verified:b.isVerified(),changePwd:b.shouldChangePassword()})};try{d.push(k),d.push(f),b.apply(void 0,d)}catch(m){f(mitro.lib.makeLocalException(m))}}};q.workerInvokeOnIdentity=function(){var b=Array.prototype.slice.call(arguments),d=b[b.length-1];try{var f=b.shift(),e=b.shift();I[f.identityId][e].apply(void 0,b);q.getRandomness(function(b){forge.random.collect(b.seed);console.log("added randomness...")},function(){console.log("error adding randomness")})}catch(k){d(mitro.lib.makeLocalException(k))}};
q.workerLogout=function(b){delete I[b.identityId]};q.createIdentity=L;q.workerCreateIdentity=s(L);q.workerLogin=s(N);q.workerLoginWithToken=s(E);q.workerLoginWithTokenAndLocalKey=s(F);q.login=N;q.loginWithToken=E;q.loginWithTokenAndLocalKey=F;q.addIssue=function(b,d,f,e,k){b.server_host=d;b.server_port=f;mitro.lib.AddIssue(b,e,k)};q.keyCache=v;q.clearCaches=mitro.lib.clearCaches;q.bidirectionalSetDiff=J})();
