(function(){"undefined"!==typeof window?("undefined"===typeof mitro&&(mitro=window.mitro=window.mitro||{}),mitro.lib={}):"undefined"!==typeof module&&module.exports&&(getExtensionId=function(){return"node_extension_id"},mitro={crypto:require("./crypto.js"),crappycrypto:require("./crappycrypto.js"),keycache:require("./keycache"),rpc:require("./rpc.js"),cache:require("./lru_cache.js"),log:require("./logging.js")},module.exports=mitro.lib={});new mitro.cache.LRUCache(1024);var q={},m=function(a){try{console.log("local exception:",
a,a.stack)}catch(b){}var d={status:-1,userVisibleError:"Unknown local error",exceptionType:"JavascriptException",local_exception:a};a.userVisibleError&&(d.userVisibleError=a.userVisibleError);return d},s=function(a){if(a._transactionSpecificData&&a._transactionSpecificData.isWriteOperation&&a._transactionSpecificData.id)return a._transactionSpecificData.id in q||(q[a._transactionSpecificData.id]=new mitro.cache.LRUCache),q[a._transactionSpecificData.id];void 0===q[null]&&(q[null]=new mitro.cache.LRUCache(1024));
return q[null]},E=function(a){delete q[a.id]},p=function(a){return function(){console.log("mitro_lib: clearing global cache");delete q[null];a.apply(null,Array.prototype.slice.call(arguments))}},r=mitro.crypto,g=mitro.lib,l=function(a){if(!a)throw Error("Assertion failed");},h=function(a,b,d,c,f){a.deviceId=b.deviceId;a={identity:b.uid,request:JSON.stringify(a)};b._transactionSpecificData&&(a.operationName=b._transactionSpecificData.operationName,a.transactionId=b._transactionSpecificData.id,a.implicitEndTransaction=
b._transactionSpecificData.implicitEndTransaction,b._transactionSpecificData.implicitBeginTransaction&&(b._transactionSpecificData.implicitBeginTransaction=!1,a.implicitBeginTransaction=!0));void 0!==b._privateKey&&(a.signature=b._privateKey.sign(a.request));return mitro.rpc._PostToMitro(a,b,d,function(a){b._transactionSpecificData&&!b._transactionSpecificData.id&&(b._transactionSpecificData.id=a.transactionId);c(a)},f)},F=p(function(a,b,d){try{console.log(">>Add Identity");if(-1==a.uid.indexOf("@"))throw Error("uid does not appear to be an email address: "+
a.uid);if(8>a.password.length)throw Error("password is not long enough ("+a.password.length+" characters; must be at least 8 characters)");a._keyCache.getNewRSAKeysAsync(2,function(c){var e=c[0];c=c[1];var k={userId:a.uid,publicKey:e.exportPublicKey().toJson(),encryptedPrivateKey:e.toJsonEncrypted(a.password),analyticsId:a.analyticsId},g=null;b&&(g=function(a){a.privateKey=e;b(a)});a._privateKey=e;a._createPrivateGroup&&(k.groupKeyEncryptedForMe=e.encrypt(c.toJson()),k.groupPublicKey=c.exportPublicKey().toJson());
h(k,a,"/mitro-core/api/AddIdentity",p(g),d)},d)}catch(c){d(m(c))}}),M=p(function(a,b,d){try{a._keyCache.getNewRSAKeysAsync(1,function(c){c=c[0];console.log(">>Add Group");l(a.uid);if(2>a._.length)throw console.log("usage: mitro.js addgroup --uid=me@example.com NAME"),Error("Incorrect aruments");a.name=a._[1];c={name:a.name,autoDelete:a.autoDelete,publicKey:c.exportPublicKey().toJson(),signatureString:"TODO",scope:a.scope,acls:[{level:"ADMIN",groupKeyEncryptedForMe:a._privateKey.encrypt(c.toJson()),
memberGroup:null,memberIdentity:a.uid}]};h(c,a,"/mitro-core/api/AddGroup",p(b),d)},d)}catch(c){console.log(">> exception in add group"),d(m(c))}}),H=function(a,b,d){var c=[a.target_uid];G(a,c,function(a){a.publicKey=a.userIdToPublicKey[c[0]];a.myUserId=c[0];b(a)},d)},G=function(a,b,d,c){return u(a,a.addMissingUsers,b,null,d,c)},u=function(a,b,d,c,f,e){try{console.log(">>Get public key"),h({userIds:d,addMissingUsers:b,groupIds:c},a,"/mitro-core/api/GetPublicKeyForIdentity",function(a){l(!a.missingUsers||
0===a.missingUsers.length);f(a)},e)}catch(k){console.log(k.stack),e(m(k))}},x=function(a,b,d){try{console.log(">>Get private key");l(a.uid);var c={userId:a.uid,loginToken:a.loginToken,loginTokenSignature:a.loginTokenSignature,twoFactorCode:a.twoFactorCode,extensionId:getExtensionId(),automatic:a.automatic};h(c,a,"/mitro-core/api/GetMyPrivateKey",b,d)}catch(f){d(m(f))}},I=function(a,b,d){l(a);var c=a.groupIdPath,f;for(f in c){var e=c[f];b[e]?(d=d.decrypt(b[e].encryptedPrivateKey),d=r.loadFromJson(d)):
console.log("ERROR: could not get group info for (group)",e)}a.clientData=d.decrypt(a.encryptedClientData);a.encryptedCriticalData&&(a.criticalData=d.decryptNoMemo(a.encryptedCriticalData));return a},J=function(a,b,d){try{l(b);var c=a.includeCriticalData;void 0===c&&(c="true");var f=null;if(!c){var f=mitro.cache.makeKey("GetSecret",a.uid,a._[1]),e=s(a).getItem(f);if(e){console.log("mitro_lib GetSecret: Found response in cache");b(JSON.parse(e));return}}2>a._.length&&(console.log("usage: mitro.js cat --uid=me@example.com SECRET_ID"),
process.exit(-1));var k=parseInt(a._[1],10),g={userId:a.uid,secretId:k,includeCriticalData:c};console.log(">>GetSecret ("+JSON.stringify(g)+")");h(g,a,"/mitro-core/api/GetSecret",function(e){try{var k=e.secret,g=a._privateKey.decrypt(e.encryptedGroupKey),v=r.loadFromJson(g);k.clientData=v.decrypt(k.encryptedClientData);k.encryptedCriticalData&&(k.criticalData=v.decryptNoMemo(k.encryptedCriticalData));e.secret.groupNames&&(k.groupNames=e.secret.groupNames);e.secret.groupMap&&(k.groupMap=e.secret.groupMap);
k.groups=[];for(var L in k.groupNames){var h=parseInt(L,10);k.groups.push(h)}c||(l(f),s(a).setItem(f,JSON.stringify(k),{expirationAbsolute:new Date((new Date).getTime()+6E4)}));b(k)}catch(w){d(m(w))}},d)}catch(w){d(m(w))}},B=p(function(a,b,d,c){try{a.orgId=parseInt(a.orgId,10),l(d),l(c),console.log("mitro_lib MutateMembership(); onSuccess is truthy?",!!d),l(a.gid),a.includeCriticalData=!0,A(a,function(e){var k=null,f;for(f in e.acls){var g=e.acls[f];g.memberIdentity===a.uid&&(k=r.loadFromJson(a._privateKey.decrypt(g.groupKeyEncryptedForMe)))}var n=
function(f){try{b(e,f)?(l(f),l(null!==e.secrets),a._keyCache.getNewRSAKeysAsync(1,function(b){try{var k=b[0],g;for(g in e.acls){var l=r.loadFromJson(e.acls[g].myPublicKey);e.acls[g].groupKeyEncryptedForMe=l.encrypt(k.toJson())}for(g in e.secrets)e.secrets[g].encryptedClientData=k.encrypt(f.decrypt(e.secrets[g].encryptedClientData)),e.secrets[g].encryptedCriticalData=k.encrypt(f.decrypt(e.secrets[g].encryptedCriticalData));e.publicKey=k.exportPublicKey().toJson();h(e,a,"/mitro-core/api/EditGroup",
p(d),c)}catch(n){c(m(n))}},c)):h(e,a,"/mitro-core/api/EditGroup",p(d),c)}catch(k){c(m(k))}};if(null===k&&a.orgId){var t=null;for(f in e.acls)if(t=e.acls[f],a.gid=null,parseInt(t.memberGroup,10)===a.orgId){a.gid=a.orgId;break}A(a,function(b){var c=null,d;for(d in b.acls){var e=b.acls[d];e.memberIdentity===a.uid&&(c=r.loadFromJson(a._privateKey.decrypt(e.groupKeyEncryptedForMe)),c=r.loadFromJson(c.decrypt(t.groupKeyEncryptedForMe)))}n(c)},c)}else n(k)},c)}catch(f){c(m(f))}}),N=p(function(a,b,d){B(a,
function(b,d){l(d);b.acls.push({level:"ADMIN",groupKeyEncryptedForMe:a._targetPublicKey.encrypt(d.toJson()),memberIdentity:a.target_uid});b.secrets=null;return!1},b,d)}),O=p(function(a,b,d){a.includeCriticalData=!0;B(a,function(b,d){var e=[],k;for(k in b.acls){var g=b.acls[k];g.memberIdentity!==a.target_uid&&e.push(g)}l(e.length+1===b.acls.length);b.acls=e;return!0},b,d)}),A=function(a,b,d){try{l(a.gid);var c={groupId:a.gid,userId:a.uid,includeCriticalData:a.includeCriticalData},f=s(a).getItem(mitro.cache.makeKey("GetGroup",
a.uid,a.gid,a.includeCriticalData));f?(console.log("mitro_lib GetGroup: Found response in cache"),b(JSON.parse(f))):h(c,a,"/mitro-core/api/GetGroup",function(c){s(a).setItem(mitro.cache.makeKey("GetGroup",a.uid,a.gid,a.includeCriticalData),JSON.stringify(c),{expirationAbsolute:new Date((new Date).getTime()+6E4)});b(c)},d)}catch(e){d(m(e))}},D=p(function(a,b,d,c){try{if(0===b.groupIds.length)d();else{var f=function(e,f){u(a,!1,[],b.groupIds,function(g){var n=[];try{for(var t=0;t<b.groupIds.length;++t){var y=
b.groupIds[t],v=g.groupIdToPublicKey[y];console.log("getting key for ",y);l(v);var z=r.loadFromJson(v),q=b.secretId;l(z);var s={myUserId:a.uid,ownerGroupId:y,encryptedClientData:z.encrypt(e),encryptedCriticalData:z.encrypt(f),secretId:q};n.push([h,[s,a,"/mitro-core/api/AddSecret"]]);void 0===b.secretId&&0===t&&n.push([function(a,b,c){for(c=2;c<n.length;c++)n[c][1][0].secretId=a.secretId;b()},[void 0]])}C(n,p(d),c)}catch(u){c(m(u))}},c)};b.secretId?(a._=[null,b.secretId],J(a,function(a){f(a.clientData,
a.criticalData)},c)):(l(b.clientData),l(b.criticalData),f(b.clientData,b.criticalData))}}catch(e){c(m(e))}}),P=p(function(a,b,d,c){try{void 0===c&&(c=d,d=b,b=void 0),void 0===a.gid&&(a.gid=b,console.log("set gid to "+b)),l(a.gid),b=function(a){try{d(a[0])}catch(b){c(m(b))}},a.secretId?D(a,{groupIds:[a.gid],secretId:a.secretId},b,c):3>a._.length?(console.log("usage: mitro.js add --uid=me@example.com --gid=21 HOSTNAME client critical"),process.exit(-1)):D(a,{groupIds:[a.gid],secretId:a.secretId,clientData:a._[2],
criticalData:4===a._.length?a._[3]:null},b,c)}catch(f){c(m(f))}}),Q=p(function(a,b,d){try{l(a.uid);var c;a._?(2>a._.length&&(console.log("usage: mitro.js rm --uid=me@example.com SECRET_ID"),process.exit(-1)),c=parseInt(a._[1],10)):(l(a.secretId),c=a.secretId);h({myUserId:a.uid,secretId:c,groupId:a.gid},a,"/mitro-core/api/RemoveSecret",p(b),d)}catch(f){d(m(f))}}),K=function(a,b,d,c,f){var e=function(a){console.log("ERROR IN TRANSACTION CODE:",a.message,a.stack);f(mitro.lib.makeLocalException(a))};
b._privateKey=d;h({},b,"/mitro-core/api/BeginTransaction",function(f){var g=function(a){console.log("trying to close transaction");h({},b,"/mitro-core/api/EndTransaction",function(d){E(b._transactionSpecificData.id);c(a)},e)};b._transactionSpecificData={id:f.transactionId,isWriteOperation:!1};b.target_uid?H({uid:b.uid,target_uid:b.target_uid,deviceId:b.deviceId,_transactionSpecificData:b._transactionSpecificData,_privateKey:d,server_host:b.server_host,server_port:b.server_port,_keyCache:b._keyCache},
function(c){c=r.loadFromJson(c.publicKey);b._targetPublicKey=c;a(b,g,e)},e):a(b,g,e)},e);return!0},C=function(a,b,d,c){var f=[],e;for(e in a)if("string"===typeof a[e][0]||"number"===typeof a[e][0])f[e]=String(a[e][0]),a[e].shift();return R(f,a,b,d,c)},R=function(a,b,d,c,f){if(0===b.length)setTimeout(function(){d([])},0);else{var e=[],g={},l=[],m=function(b){a[e.length]&&(console.log("*** FINISHED ",a[e.length]),g[a[e.length]]=b);e.push(b);var c=l.pop();if(void 0!==c){for(var f in c[1])if(void 0===
c[1][f]){c[1][f]=b;break}c[0].apply(void 0,c[1])}else d(e,g)},n;for(n in b){var h=b[n][1];void 0===b[n][2]||void 0===b[n][2]?(h.push(m),h.push(c)):(h.push(c),h.push(m));l.push([b[n][0],h])}l.reverse();b=l.pop();for(n in b[1])if(void 0===b[1][n]){b[1][n]=f;f=void 0;break}b[0].apply(void 0,b[1])}};g.parallel=function(a,b,d){if(0===a.length)setTimeout(function(){b([])},0);else{var c={},f=0,e=!1,g=!1,h=function(a){e||(g=e=!0,d(a))},m=function(d){return function(h){if(!e&&(l(void 0===c[d]),c[d]=h,++f,
f===a.length)){l(!g);g=!0;h=[];for(var m=0;m<f;++m)h.push(c[m]);b(h)}}},n;for(n in a){var p=a[n][1];void 0===a[n][2]||void 0===a[n][2]?(p.push(m(n)),p.push(h)):(p.push(h),p.push(m(n)));a[n][0].apply(void 0,p)}}};g.series=C;g.batch=C;g.GetGroup=A;g.GetSecret=J;g.GetPrivateKey=x;g.GetPublicKey=H;g.GetPublicKeys=G;g.GetUserAndGroupPublicKeys=u;g.MutateMembership=B;g.AddSecret=P;g.AddSecrets=D;g.RetrieveDeviceSpecificKey=function(a,b,d){try{console.log(">>Retrieve Device key");l(a.uid);var c={userId:a.uid,
extensionId:getExtensionId()};h(c,a,"/mitro-core/api/GetMyDeviceKey",b,d)}catch(f){d(m(f))}};g.AddMember=N;g.AddGroup=M;g.AddIdentity=F;g.RemoveSecret=Q;g.RemoveMember=O;g.ListGroupsAndSecrets=function(a,b,d){try{var c=s(a).getItem(mitro.cache.makeKey("ListGroupsAndSecrets",a.uid));c?(console.log("mitro_lib ListGroupsAndSecrets: Found response in cache"),(b||mitro.rpc.DefaultResponseHandler)(JSON.parse(c))):(console.log(">>Get List Groups and Secrets"),l(a.uid),h({myUserId:a.uid},a,"/mitro-core/api/ListMySecretsAndGroupKeys",
function(c){var d=Object.keys(c.secretToPath),f;for(f in d)I(c.secretToPath[d[f]],c.groups,a._privateKey);s(a).setItem(mitro.cache.makeKey("ListGroupsAndSecrets",a.uid),JSON.stringify(c),{expirationAbsolute:new Date((new Date).getTime()+6E4)});(b||mitro.rpc.DefaultResponseHandler)(c)},d))}catch(f){console.log(f),console.log(f.stack),d(m(f))}};g.GetOrganizationState=function(a,b,d,c){var f=mitro.cache.makeKey("/mitro-core/api/GetOrganizationState",b.orgId),e=s(a).getItem(f);e?d(JSON.parse(e)):mitro.lib.PostToMitro(b,
a,"/mitro-core/api/GetOrganizationState",function(b){s(a).setItem(f,JSON.stringify(b),{expirationAbsolute:new Date((new Date).getTime()+6E4)});d(b)},c)};g.AddIssue=function(a,b,d){try{console.log(">>Add Issue"),h(a,a,"/mitro-core/api/AddIssue",b,d)}catch(c){console.log(">> exception in add issue"),d(m(c))}};g.GetAuditLog=function(a,b,d){try{console.log(">>Get Audit Log"),h(a,a,"/mitro-core/api/GetAuditLog",b,d)}catch(c){console.log(">> exception in get audit log"),d(m(c))}};g.runCommand=function(a,
b,d,c){var f=!1;d=d||mitro.rpc.DefaultResponseHandler;c=c||mitro.rpc.DefaultErrorHandler;b._keyCache=b._keyCache||mitro.keycache.MakeKeyCache();a&&(a!==F&&a!==x?x(b,function(e){e=r.loadFromJson(e.encryptedPrivateKey,b.password);K(a,b,e,d,c)},c):a(b,d,c),f=!0);return f};g.runCommandWithPrivateKey=K;g.initForTest=function(){if(!mitro.crappycrypto)throw Error("crappycrypto does not exist?");r=mitro.crappycrypto;mitro.keycache.useCrappyCrypto()};g.postEndTransaction=E;g.getCrypto=function(){return r};
g.PostToMitro=h;g.PostToMitroAgent=function(a,b,d,c){return mitro.rpc._PostToMitro(a,{server_host:MITRO_AGENT_HOST,server_port:MITRO_AGENT_PORT},b,d,c)};g.setPostToMitroForTest=function(a){h=a};g.decryptSecretWithGroups=I;g.EditEncryptedPrivateKey=function(a,b,d,c,f){try{var e={userId:a.uid,encryptedPrivateKey:d,tfaToken:b.token,tfaSignature:b.token_signature};l(d);h(e,a,"/mitro-core/api/EditEncryptedPrivateKey",c,f)}catch(g){f(m(g))}};g.clearCaches=function(){delete q[null]};g.makeLocalException=
m;g.checkTwoFactor=function(a,b,d){try{var c={userId:a.uid,extensionId:getExtensionId()};h(c,a,"/mitro-core/api/ChangePwdTwoFactorRequired",b,d)}catch(f){d(m(f))}}})();
