(function(){function u(c){function p(a,c,b){for(var d=[m(a+c)],e=16,g=1;e<b;++g,e+=16)d.push(m(d[g-1]+a+c));return d.join("").substr(0,b)}function m(a){return c.md.md5.create().update(a).digest().getBytes()}if("undefined"===typeof x)var x=c.jsbn.BigInteger;var a=c.asn1,k=c.pki=c.pki||{};k.pbe=c.pbe=c.pbe||{};var r=k.oids,u={name:"EncryptedPrivateKeyInfo",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"EncryptedPrivateKeyInfo.encryptionAlgorithm",tagClass:a.Class.UNIVERSAL,
type:a.Type.SEQUENCE,constructed:!0,value:[{name:"AlgorithmIdentifier.algorithm",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"encryptionOid"},{name:"AlgorithmIdentifier.parameters",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,captureAsn1:"encryptionParams"}]},{name:"EncryptedPrivateKeyInfo.encryptedData",tagClass:a.Class.UNIVERSAL,type:a.Type.OCTETSTRING,constructed:!1,capture:"encryptedData"}]},w={name:"PBES2Algorithms",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,
constructed:!0,value:[{name:"PBES2Algorithms.keyDerivationFunc",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"PBES2Algorithms.keyDerivationFunc.oid",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"kdfOid"},{name:"PBES2Algorithms.params",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"PBES2Algorithms.params.salt",tagClass:a.Class.UNIVERSAL,type:a.Type.OCTETSTRING,constructed:!1,capture:"kdfSalt"},{name:"PBES2Algorithms.params.iterationCount",
tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,onstructed:!0,capture:"kdfIterationCount"}]}]},{name:"PBES2Algorithms.encryptionScheme",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"PBES2Algorithms.encryptionScheme.oid",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"encOid"},{name:"PBES2Algorithms.encryptionScheme.iv",tagClass:a.Class.UNIVERSAL,type:a.Type.OCTETSTRING,constructed:!1,capture:"encIv"}]}]},v={name:"pkcs-12PbeParams",tagClass:a.Class.UNIVERSAL,
type:a.Type.SEQUENCE,constructed:!0,value:[{name:"pkcs-12PbeParams.salt",tagClass:a.Class.UNIVERSAL,type:a.Type.OCTETSTRING,constructed:!1,capture:"salt"},{name:"pkcs-12PbeParams.iterations",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"iterations"}]};k.encryptPrivateKeyInfo=function(f,h,b){b=b||{};b.saltSize=b.saltSize||8;b.count=b.count||2048;b.algorithm=b.algorithm||"aes128";var d=c.random.getBytesSync(b.saltSize),e=b.count,g=a.integerToDer(e),n;if(0===b.algorithm.indexOf("aes")||
"des"===b.algorithm){var l,m;switch(b.algorithm){case "aes128":l=n=16;b=r["aes128-CBC"];m=c.aes.createEncryptionCipher;break;case "aes192":n=24;l=16;b=r["aes192-CBC"];m=c.aes.createEncryptionCipher;break;case "aes256":n=32;l=16;b=r["aes256-CBC"];m=c.aes.createEncryptionCipher;break;case "des":l=n=8;b=r.desCBC;m=c.des.createEncryptionCipher;break;default:throw{message:"Cannot encrypt private key. Unknown encryption algorithm.",algorithm:b.algorithm};}var q=c.pkcs5.pbkdf2(h,d,e,n);h=c.random.getBytesSync(l);
e=m(q);e.start(h);e.update(a.toDer(f));e.finish();f=e.output.getBytes();d=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(r.pkcs5PBES2).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(r.pkcs5PBKDF2).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,d),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,
!1,g.getBytes())])]),a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(b).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,h)])])])}else if("3des"===b.algorithm)n=24,b=new c.util.ByteBuffer(d),q=k.pbe.generatePkcs12Key(h,b,1,e,n),h=k.pbe.generatePkcs12Key(h,b,2,e,n),e=c.des.createEncryptionCipher(q),e.start(h),e.update(a.toDer(f)),e.finish(),f=e.output.getBytes(),d=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,
a.Type.OID,!1,a.oidToDer(r["pbeWithSHAAnd3-KeyTripleDES-CBC"]).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,d),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,g.getBytes())])]);else throw{message:"Cannot encrypt private key. Unknown encryption algorithm.",algorithm:b.algorithm};return a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[d,a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,f)])};k.decryptPrivateKeyInfo=function(f,h){var b=null,d=
{},e=[];if(!a.validate(f,u,d,e))throw{message:"Cannot read encrypted private key. ASN.1 object is not a supported EncryptedPrivateKeyInfo.",errors:e};e=a.derToOid(d.encryptionOid);e=k.pbe.getCipher(e,d.encryptionParams,h);d=c.util.createBuffer(d.encryptedData);e.update(d);e.finish()&&(b=a.fromDer(e.output));return b};k.encryptedPrivateKeyToPem=function(f,h){var b={type:"ENCRYPTED PRIVATE KEY",body:a.toDer(f).getBytes()};return c.pem.encode(b,{maxline:h})};k.encryptedPrivateKeyFromPem=function(f){f=
c.pem.decode(f)[0];if("ENCRYPTED PRIVATE KEY"!==f.type)throw{message:'Could not convert encrypted private key from PEM; PEM header type is "ENCRYPTED PRIVATE KEY".',headerType:f.type};if(f.procType&&"ENCRYPTED"===f.procType.type)throw{message:"Could not convert encrypted private key from PEM; PEM is encrypted."};return a.fromDer(f.body)};k.encryptRsaPrivateKey=function(f,h,b){b=b||{};if(!b.legacy)return f=k.wrapRsaPrivateKey(k.privateKeyToAsn1(f)),f=k.encryptPrivateKeyInfo(f,h,b),k.encryptedPrivateKeyToPem(f);
var d,e,g;switch(b.algorithm){case "aes128":b="AES-128-CBC";e=16;d=c.random.getBytesSync(16);g=c.aes.createEncryptionCipher;break;case "aes192":b="AES-192-CBC";e=24;d=c.random.getBytesSync(16);g=c.aes.createEncryptionCipher;break;case "aes256":b="AES-256-CBC";e=32;d=c.random.getBytesSync(16);g=c.aes.createEncryptionCipher;break;case "3des":b="DES-EDE3-CBC";e=24;d=c.random.getBytesSync(8);g=c.des.createEncryptionCipher;break;case "des":b="DES-CBC";e=8;d=c.random.getBytesSync(8);g=c.des.createEncryptionCipher;
break;default:throw{message:'Could not encrypt RSA private key; unsupported encryption algorithm "'+b.algorithm+'".',algorithm:b.algorithm};}h=p(h,d.substr(0,8),e);h=g(h);h.start(d);h.update(a.toDer(k.privateKeyToAsn1(f)));h.finish();f={type:"RSA PRIVATE KEY",procType:{version:"4",type:"ENCRYPTED"},dekInfo:{algorithm:b,parameters:c.util.bytesToHex(d).toUpperCase()},body:h.output.getBytes()};return c.pem.encode(f)};k.decryptRsaPrivateKey=function(f,h){var b=null,d=c.pem.decode(f)[0];if("ENCRYPTED PRIVATE KEY"!==
d.type&&"PRIVATE KEY"!==d.type&&"RSA PRIVATE KEY"!==d.type)throw{message:'Could not convert private key from PEM; PEM header type is not "ENCRYPTED PRIVATE KEY", "PRIVATE KEY", or "RSA PRIVATE KEY".',headerType:d.type};if(d.procType&&"ENCRYPTED"===d.procType.type){var e,g;switch(d.dekInfo.algorithm){case "DES-CBC":e=8;g=c.des.createDecryptionCipher;break;case "DES-EDE3-CBC":e=24;g=c.des.createDecryptionCipher;break;case "AES-128-CBC":e=16;g=c.aes.createDecryptionCipher;break;case "AES-192-CBC":e=
24;g=c.aes.createDecryptionCipher;break;case "AES-256-CBC":e=32;g=c.aes.createDecryptionCipher;break;case "RC2-40-CBC":e=5;g=function(a){return c.rc2.createDecryptionCipher(a,40)};break;case "RC2-64-CBC":e=8;g=function(a){return c.rc2.createDecryptionCipher(a,64)};break;case "RC2-128-CBC":e=16;g=function(a){return c.rc2.createDecryptionCipher(a,128)};break;default:throw{message:'Could not decrypt private key; unsupported encryption algorithm "'+d.dekInfo.algorithm+'".',algorithm:d.dekInfo.algorithm};
}var n=c.util.hexToBytes(d.dekInfo.parameters);e=p(h,n.substr(0,8),e);g=g(e);g.start(n);g.update(c.util.createBuffer(d.body));if(g.finish())b=g.output.getBytes();else return b}else b=d.body;b="ENCRYPTED PRIVATE KEY"===d.type?k.decryptPrivateKeyInfo(a.fromDer(b),h):a.fromDer(b);null!==b&&(b=k.privateKeyFromAsn1(b));return b};k.pbe.generatePkcs12Key=function(a,h,b,d,e,g){var k,l;if("undefined"===typeof g||null===g)g=c.md.sha1.create();var m=g.digestLength,q=g.blockLength,p=new c.util.ByteBuffer,t=new c.util.ByteBuffer;
for(l=0;l<a.length;l++)t.putInt16(a.charCodeAt(l));t.putInt16(0);a=t.length();var r=h.length(),u=new c.util.ByteBuffer;u.fillWithByte(b,q);var s=q*Math.ceil(r/q);b=new c.util.ByteBuffer;for(l=0;l<s;l++)b.putByte(h.at(l%r));s=q*Math.ceil(a/q);h=new c.util.ByteBuffer;for(l=0;l<s;l++)h.putByte(t.at(l%a));t=b;t.putBuffer(h);h=Math.ceil(e/m);for(b=1;b<=h;b++){s=new c.util.ByteBuffer;s.putBytes(u.bytes());s.putBytes(t.bytes());for(l=0;l<d;l++)g.start(),g.update(s.getBytes()),s=g.digest();var x=new c.util.ByteBuffer;
for(l=0;l<q;l++)x.putByte(s.at(l%m));var w=Math.ceil(r/q)+Math.ceil(a/q),v=new c.util.ByteBuffer;for(k=0;k<w;k++){var z=new c.util.ByteBuffer(t.getBytes(q)),y=511;for(l=x.length()-1;0<=l;l--)y>>=8,y+=x.at(l)+z.at(l),z.setAt(l,y&255);v.putBuffer(z)}t=v;p.putBuffer(s)}p.truncate(p.length()-e);return p};k.pbe.getCipher=function(a,c,b){switch(a){case k.oids.pkcs5PBES2:return k.pbe.getCipherForPBES2(a,c,b);case k.oids["pbeWithSHAAnd3-KeyTripleDES-CBC"]:case k.oids["pbewithSHAAnd40BitRC2-CBC"]:return k.pbe.getCipherForPKCS12PBE(a,
c,b);default:throw{message:"Cannot read encrypted PBE data block. Unsupported OID.",oid:a,supportedOids:["pkcs5PBES2","pbeWithSHAAnd3-KeyTripleDES-CBC","pbewithSHAAnd40BitRC2-CBC"]};}};k.pbe.getCipherForPBES2=function(f,h,b){var d={};f=[];if(!a.validate(h,w,d,f))throw{message:"Cannot read password-based-encryption algorithm parameters. ASN.1 object is not a supported EncryptedPrivateKeyInfo.",errors:f};f=a.derToOid(d.kdfOid);if(f!==k.oids.pkcs5PBKDF2)throw{message:"Cannot read encrypted private key. Unsupported key derivation function OID.",
oid:f,supportedOids:["pkcs5PBKDF2"]};f=a.derToOid(d.encOid);if(f!==k.oids["aes128-CBC"]&&f!==k.oids["aes192-CBC"]&&f!==k.oids["aes256-CBC"]&&f!==k.oids["des-EDE3-CBC"]&&f!==k.oids.desCBC)throw{message:"Cannot read encrypted private key. Unsupported encryption scheme OID.",oid:f,supportedOids:["aes128-CBC","aes192-CBC","aes256-CBC","des-EDE3-CBC","desCBC"]};h=d.kdfSalt;var e=c.util.createBuffer(d.kdfIterationCount),e=e.getInt(e.length()<<3),g,n;switch(k.oids[f]){case "aes128-CBC":g=16;n=c.aes.createDecryptionCipher;
break;case "aes192-CBC":g=24;n=c.aes.createDecryptionCipher;break;case "aes256-CBC":g=32;n=c.aes.createDecryptionCipher;break;case "des-EDE3-CBC":g=24;n=c.des.createDecryptionCipher;break;case "desCBC":g=8,n=c.des.createDecryptionCipher}b=c.pkcs5.pbkdf2(b,h,e,g);d=d.encIv;n=n(b);n.start(d);return n};k.pbe.getCipherForPKCS12PBE=function(f,h,b){var d={},e=[];if(!a.validate(h,v,d,e))throw{message:"Cannot read password-based-encryption algorithm parameters. ASN.1 object is not a supported EncryptedPrivateKeyInfo.",
errors:e};h=c.util.createBuffer(d.salt);var d=c.util.createBuffer(d.iterations),d=d.getInt(d.length()<<3),g;switch(f){case k.oids["pbeWithSHAAnd3-KeyTripleDES-CBC"]:g=24;e=8;f=c.des.startDecrypting;break;case k.oids["pbewithSHAAnd40BitRC2-CBC"]:g=5;e=8;f=function(a,b){var d=c.rc2.createDecryptionCipher(a,40);d.start(b,null);return d};break;default:throw{message:"Cannot read PKCS #12 PBE data block. Unsupported OID.",oid:f};}g=k.pbe.generatePkcs12Key(b,h,1,d,g);b=k.pbe.generatePkcs12Key(b,h,2,d,e);
return f(g,b)}}if("function"!==typeof define)if("object"===typeof module&&module.exports){var A=!0;define=function(c,p){p(require,module)}}else return"undefined"===typeof forge&&(forge={}),u(forge);var w,B=function(c,p){p.exports=function(m){var p=w.map(function(a){return c(a)}).concat(u);m=m||{};m.defined=m.defined||{};if(m.defined.pbe)return m.pbe;m.defined.pbe=!0;for(var a=0;a<p.length;++a)p[a](m);return m.pbe}},v=define;define=function(c,p){w="string"===typeof c?p.slice(2):c.slice(2);if(A)return delete define,
v.apply(null,Array.prototype.slice.call(arguments,0));define=v;return define.apply(null,Array.prototype.slice.call(arguments,0))};define("require module ./aes ./asn1 ./des ./md ./oids ./pem ./pbkdf2 ./random ./rc2 ./rsa ./util".split(" "),function(){B.apply(null,Array.prototype.slice.call(arguments,0))})})();
