(function(){function r(h){function p(a,c,g,b){for(var d=[],e=0;e<a.length;e++)for(var k=0;k<a[e].safeBags.length;k++){var f=a[e].safeBags[k];if(void 0===b||f.type===b)null===c?d.push(f):void 0!==f.attributes[c]&&0<=f.attributes[c].indexOf(g)&&d.push(f)}return d}function n(l,c,m,b){c=a.fromDer(c,m);if(c.tagClass!==a.Class.UNIVERSAL||c.type!==a.Type.SEQUENCE||!0!==c.constructed)throw{message:"PKCS#12 AuthenticatedSafe expected to be a SEQUENCE OF ContentInfo"};for(var d=0;d<c.value.length;d++){var e=
{},k=[];if(!a.validate(c.value[d],r,e,k))throw{message:"Cannot read ContentInfo.",errors:k};var k={encrypted:!1},f=null,f=e.content.value[0];switch(a.derToOid(e.contentType)){case g.oids.data:if(f.tagClass!==a.Class.UNIVERSAL||f.type!==a.Type.OCTETSTRING)throw{message:"PKCS#12 SafeContents Data is not an OCTET STRING."};f=f.value;break;case g.oids.encryptedData:if(void 0===b)throw{message:"Found PKCS#12 Encrypted SafeContents Data but no password available."};var q=b,e={},s=[];if(!a.validate(f,h.pkcs7.asn1.encryptedDataValidator,
e,s))throw{message:"Cannot read EncryptedContentInfo. ",errors:s};f=a.derToOid(e.contentType);if(f!==g.oids.data)throw{message:"PKCS#12 EncryptedContentInfo ContentType is not Data.",oid:f};f=a.derToOid(e.encAlgorithm);f=g.pbe.getCipher(f,e.encParameter,q);e=h.util.createBuffer(e.encryptedContent);f.update(e);if(!f.finish())throw{message:"Failed to decrypt PKCS#12 SafeContents."};f=f.output.getBytes();k.encrypted=!0;break;default:throw{message:"Unsupported PKCS#12 contentType.",contentType:a.derToOid(e.contentType)};
}k.safeBags=A(f,m,b);l.safeContents.push(k)}}function A(l,c,h){l=a.fromDer(l,c);if(l.tagClass!==a.Class.UNIVERSAL||l.type!==a.Type.SEQUENCE||!0!==l.constructed)throw{message:"PKCS#12 SafeContents expected to be a SEQUENCE OF SafeBag"};for(var b=[],d=0;d<l.value.length;d++){var e={},k=[];if(!a.validate(l.value[d],x,e,k))throw{message:"Cannot read SafeBag.",errors:k};var f={type:a.derToOid(e.bagId),attributes:t(e.bagAttributes)};b.push(f);var q,s,u=e.bagValue.value[0];switch(f.type){case g.oids.pkcs8ShroudedKeyBag:if(void 0===
h)throw{message:"Found PKCS#8 ShroudedKeyBag but no password available."};u=g.decryptPrivateKeyInfo(u,h);if(null===u)throw{message:"Unable to decrypt PKCS#8 ShroudedKeyBag, wrong password?"};case g.oids.keyBag:f.key=g.privateKeyFromAsn1(u);continue;case g.oids.certBag:q=z;s=function(){if(a.derToOid(e.certId)!==g.oids.x509Certificate)throw{message:"Unsupported certificate type, only X.509 supported.",oid:a.derToOid(e.certId)};f.cert=g.certificateFromAsn1(a.fromDer(e.cert,c),!0)};break;default:throw{message:"Unsupported PKCS#12 SafeBag type.",
oid:f.type};}if(void 0!==q&&!a.validate(u,q,e,k))throw{message:"Cannot read PKCS#12 "+q.name,errors:k};s()}return b}function t(h){var c={};if(void 0!==h)for(var m=0;m<h.length;++m){var b={},d=[];if(!a.validate(h[m],y,b,d))throw{message:"Cannot read PKCS#12 BagAttribute.",errors:d};d=a.derToOid(b.oid);if(void 0!==g.oids[d]){c[g.oids[d]]=[];for(var e=0;e<b.values.length;++e)c[g.oids[d]].push(b.values[e].value)}}return c}var a=h.asn1,g=h.pki,v=h.pkcs12=h.pkcs12||{},r={name:"ContentInfo",tagClass:a.Class.UNIVERSAL,
type:a.Type.SEQUENCE,constructed:!0,value:[{name:"ContentInfo.contentType",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"contentType"},{name:"ContentInfo.content",tagClass:a.Class.CONTEXT_SPECIFIC,constructed:!0,captureAsn1:"content"}]},w={name:"PFX",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"PFX.version",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"version"},r,{name:"PFX.macData",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,
constructed:!0,optional:!0,captureAsn1:"mac",value:[{name:"PFX.macData.mac",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"PFX.macData.mac.digestAlgorithm",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"PFX.macData.mac.digestAlgorithm.algorithm",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"macAlgorithm"},{name:"PFX.macData.mac.digestAlgorithm.parameters",tagClass:a.Class.UNIVERSAL,captureAsn1:"macAlgorithmParameters"}]},
{name:"PFX.macData.mac.digest",tagClass:a.Class.UNIVERSAL,type:a.Type.OCTETSTRING,constructed:!1,capture:"macDigest"}]},{name:"PFX.macData.macSalt",tagClass:a.Class.UNIVERSAL,type:a.Type.OCTETSTRING,constructed:!1,capture:"macSalt"},{name:"PFX.macData.iterations",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,optional:!0,capture:"macIterations"}]}]},x={name:"SafeBag",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"SafeBag.bagId",tagClass:a.Class.UNIVERSAL,
type:a.Type.OID,constructed:!1,capture:"bagId"},{name:"SafeBag.bagValue",tagClass:a.Class.CONTEXT_SPECIFIC,constructed:!0,captureAsn1:"bagValue"},{name:"SafeBag.bagAttributes",tagClass:a.Class.UNIVERSAL,type:a.Type.SET,constructed:!0,optional:!0,capture:"bagAttributes"}]},y={name:"Attribute",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"Attribute.attrId",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"oid"},{name:"Attribute.attrValues",tagClass:a.Class.UNIVERSAL,
type:a.Type.SET,constructed:!0,capture:"values"}]},z={name:"CertBag",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"CertBag.certId",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"certId"},{name:"CertBag.certValue",tagClass:a.Class.CONTEXT_SPECIFIC,constructed:!0,value:[{name:"CertBag.certValue[0]",tagClass:a.Class.UNIVERSAL,type:a.Class.OCTETSTRING,constructed:!1,capture:"cert"}]}]};v.pkcs12FromAsn1=function(l,c,m){"string"===typeof c?(m=c,c=!0):void 0===
c&&(c=!0);var b={},d=[];if(!a.validate(l,w,b,d))throw{message:"Cannot read PKCS#12 PFX. ASN.1 object is not an PKCS#12 PFX.",errors:d};var e={version:b.version.charCodeAt(0),safeContents:[],getBags:function(a){var b={},c;"localKeyId"in a?c=a.localKeyId:"localKeyIdHex"in a&&(c=h.util.hexToBytes(a.localKeyIdHex));void 0===c&&!("friendlyName"in a)&&"bagType"in a&&(b[a.bagType]=p(e.safeContents,null,null,a.bagType));void 0!==c&&(b.localKeyId=p(e.safeContents,"localKeyId",c,a.bagType));"friendlyName"in
a&&(b.friendlyName=p(e.safeContents,"friendlyName",a.friendlyName,a.bagType));return b},getBagsByFriendlyName:function(a,b){return p(e.safeContents,"friendlyName",a,b)},getBagsByLocalKeyId:function(a,b){return p(e.safeContents,"localKeyId",a,b)}};if(3!==b.version.charCodeAt(0))throw{message:"PKCS#12 PFX of version other than 3 not supported.",version:b.version.charCodeAt(0)};if(a.derToOid(b.contentType)!==g.oids.data)throw{message:"Only PKCS#12 PFX in password integrity mode supported.",oid:a.derToOid(b.contentType)};
l=b.content.value[0];if(l.tagClass!==a.Class.UNIVERSAL||l.type!==a.Type.OCTETSTRING)throw{message:"PKCS#12 authSafe content data is not an OCTET STRING."};if(b.mac){var d=null,k=0,f=a.derToOid(b.macAlgorithm);switch(f){case g.oids.sha1:d=h.md.sha1.create();k=20;break;case g.oids.sha256:d=h.md.sha256.create();k=32;break;case g.oids.sha384:d=h.md.sha384.create();k=48;break;case g.oids.sha512:d=h.md.sha512.create();k=64;break;case g.oids.md5:d=h.md.md5.create(),k=16}if(null===d)throw{message:"PKCS#12 uses unsupported MAC algorithm: "+
f};var f=new h.util.ByteBuffer(b.macSalt),q="macIterations"in b?parseInt(h.util.bytesToHex(b.macIterations),16):1,k=v.generateKey(m||"",f,3,q,k,d),f=h.hmac.create();f.start(d,k);f.update(l.value);if(f.getMac().getBytes()!==b.macDigest)throw{message:"PKCS#12 MAC could not be verified. Invalid password?"};}n(e,l.value,c,m);return e};v.toPkcs12Asn1=function(l,c,m,b){b=b||{};b.saltSize=b.saltSize||8;b.count=b.count||2048;b.algorithm=b.algorithm||b.encAlgorithm||"aes128";"useMac"in b||(b.useMac=!0);"localKeyId"in
b||(b.localKeyId=null);"generateLocalKeyId"in b||(b.generateLocalKeyId=!0);var d=b.localKeyId,e;if(null!==d)d=h.util.hexToBytes(d);else if(b.generateLocalKeyId)if(c){var k=h.util.isArray(c)?c[0]:c;"string"===typeof k&&(k=g.certificateFromPem(k));d=h.md.sha1.create();d.update(a.toDer(g.certificateToAsn1(k)).getBytes());d=d.digest().getBytes()}else d=h.random.getBytes(20);k=[];null!==d&&k.push(a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.localKeyId).getBytes()),
a.create(a.Class.UNIVERSAL,a.Type.SET,!0,[a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,d)])]));"friendlyName"in b&&k.push(a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.friendlyName).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.SET,!0,[a.create(a.Class.UNIVERSAL,a.Type.BMPSTRING,!1,b.friendlyName)])]));0<k.length&&(e=a.create(a.Class.UNIVERSAL,a.Type.SET,!0,k));d=[];k=[];null!==c&&(k=h.util.isArray(c)?c:[c]);for(var f=[],q=0;q<k.length;++q){c=
k[q];"string"===typeof c&&(c=g.certificateFromPem(c));var p=0===q?e:void 0;c=g.certificateToAsn1(c);c=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.certBag).getBytes()),a.create(a.Class.CONTEXT_SPECIFIC,0,!0,[a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.x509Certificate).getBytes()),a.create(a.Class.CONTEXT_SPECIFIC,0,!0,[a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,a.toDer(c).getBytes())])])]),
p]);f.push(c)}0<f.length&&(c=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,f),c=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.data).getBytes()),a.create(a.Class.CONTEXT_SPECIFIC,0,!0,[a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,a.toDer(c).getBytes())])]),d.push(c));c=null;null!==l&&(l=g.wrapRsaPrivateKey(g.privateKeyToAsn1(l)),c=null===m?a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.keyBag).getBytes()),
a.create(a.Class.CONTEXT_SPECIFIC,0,!0,[l]),e]):a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.pkcs8ShroudedKeyBag).getBytes()),a.create(a.Class.CONTEXT_SPECIFIC,0,!0,[g.encryptPrivateKeyInfo(l,m,b)]),e]),l=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[c]),l=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.data).getBytes()),a.create(a.Class.CONTEXT_SPECIFIC,0,!0,[a.create(a.Class.UNIVERSAL,
a.Type.OCTETSTRING,!1,a.toDer(l).getBytes())])]),d.push(l));e=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,d);var n;b.useMac&&(d=h.md.sha1.create(),n=new h.util.ByteBuffer(h.random.getBytes(b.saltSize)),b=b.count,l=v.generateKey(m||"",n,3,b,20),m=h.hmac.create(),m.start(d,l),m.update(a.toDer(e).getBytes()),m=m.getMac(),n=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,
!1,a.oidToDer(g.oids.sha1).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.NULL,!1,"")]),a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,m.getBytes())]),a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,n.getBytes()),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,a.integerToDer(b).getBytes())]));return a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,a.integerToDer(3).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,
!1,a.oidToDer(g.oids.data).getBytes()),a.create(a.Class.CONTEXT_SPECIFIC,0,!0,[a.create(a.Class.UNIVERSAL,a.Type.OCTETSTRING,!1,a.toDer(e).getBytes())])]),n])};v.generateKey=h.pbe.generatePkcs12Key}if("function"!==typeof define)if("object"===typeof module&&module.exports){var y=!0;define=function(h,p){p(require,module)}}else return"undefined"===typeof forge&&(forge={}),r(forge);var w,z=function(h,p){p.exports=function(n){var p=w.map(function(a){return h(a)}).concat(r);n=n||{};n.defined=n.defined||
{};if(n.defined.pkcs12)return n.pkcs12;n.defined.pkcs12=!0;for(var t=0;t<p.length;++t)p[t](n);return n.pkcs12}},x=define;define=function(h,p){w="string"===typeof h?p.slice(2):h.slice(2);if(y)return delete define,x.apply(null,Array.prototype.slice.call(arguments,0));define=x;return define.apply(null,Array.prototype.slice.call(arguments,0))};define("require module ./asn1 ./hmac ./oids ./pkcs7asn1 ./pbe ./random ./rsa ./sha1 ./util ./x509".split(" "),function(){z.apply(null,Array.prototype.slice.call(arguments,
0))})})();
