(function(){function t(d){function p(b,a,c){var k=d.util.createBuffer();a=Math.ceil(a.n.bitLength()/8);if(b.length>a-11)throw{message:"Message is too long for PKCS#1 v1.5 padding.",length:b.length,max:a-11};k.putByte(0);k.putByte(c);a=a-3-b.length;if(0===c||1===c){c=0===c?0:255;for(var f=0;f<a;++f)k.putByte(c)}else for(;0<a;){for(var e=0,g=d.random.getBytes(a),f=0;f<a;++f)c=g.charCodeAt(f),0===c?++e:k.putByte(c);a=e}k.putByte(0);k.putBytes(b);return k}function m(b,a,c,k){a=Math.ceil(a.n.bitLength()/
8);b=d.util.createBuffer(b);var f=b.getByte(),e=b.getByte();if(0!==f||c&&0!==e&&1!==e||!c&&2!=e||c&&0===e&&"undefined"===typeof k)throw{message:"Encryption block is invalid."};c=0;if(0===e)for(c=a-3-k,k=0;k<c;++k){if(0!==b.getByte())throw{message:"Encryption block is invalid."};}else if(1===e)for(c=0;1<b.length();){if(255!==b.getByte()){--b.read;break}++c}else if(2===e)for(c=0;1<b.length();){if(0===b.getByte()){--b.read;break}++c}if(0!==b.getByte()||c!==a-3-b.length())throw{message:"Encryption block is invalid."};
return b.getBytes()}function z(b,a,c){function k(){q=Math.max(1,q);f(b.pBits,function(a,h){if(a)return c(a);b.p=h;f(b.qBits,e)})}function f(a,h){function c(){var h=a-1,f=new l(a,b.rng);f.testBit(h)||f.bitwiseTo(l.ONE.shiftLeft(h),A,f);f.dAddOffset(31-f.mod(p).byteValue(),0);return f}function k(e){if(!s){--d;var r=e.data;if(r.found){for(e=0;e<f.length;++e)f[e].terminate();s=!0;return h(null,new l(r.prime,16))}g.bitLength()>a&&(g=c());r=g.toString(16);e.target.postMessage({e:b.eInt,hex:r,workLoad:m});
g.dAddOffset(n,0)}}for(var f=[],e=0;e<q;++e)f[e]=new Worker(r);for(var d=q,g=c(),e=0;e<q;++e)f[e].addEventListener("message",k);var s=!1}function e(a,h){b.q=h;if(0>b.p.compareTo(b.q)){var d=b.p;b.p=b.q;b.q=d}b.p1=b.p.subtract(l.ONE);b.q1=b.q.subtract(l.ONE);b.phi=b.p1.multiply(b.q1);0!==b.phi.gcd(b.e).compareTo(l.ONE)?(b.p=b.q=null,k()):(b.n=b.p.multiply(b.q),b.n.bitLength()!==b.bits?(b.q=null,f(b.qBits,e)):(d=b.e.modInverse(b.phi),b.keys={privateKey:g.rsa.setPrivateKey(b.n,b.e,d,b.p,b.q,d.mod(b.p1),
d.mod(b.q1),b.q.modInverse(b.p)),publicKey:g.rsa.setPublicKey(b.n,b.e)},c(null,b.keys)))}"function"===typeof a&&(c=a,a={});if("undefined"===typeof Worker){var s=function(){if(g.rsa.stepKeyPairGenerationState(b,10))return c(null,b.keys);d.util.setImmediate(s)};return s()}var q=a.workers||2,m=a.workLoad||100,n=30*m/8,r=a.workerScript||"forge/prime.worker.js",p=new l(null);p.fromInt(30);var A=function(b,a){return b|a};if(-1===q)return d.util.estimateCores(function(b,a){b&&(a=2);q=a-1;k()});k()}function n(b){b=
b.toString(16);"8"<=b[0]&&(b="00"+b);return d.util.hexToBytes(b)}function B(b){return 100>=b?27:150>=b?18:200>=b?15:250>=b?12:300>=b?9:350>=b?8:400>=b?7:500>=b?6:600>=b?5:800>=b?4:1250>=b?3:2}if("undefined"===typeof l)var l=d.jsbn.BigInteger;var a=d.asn1;d.pki=d.pki||{};d.pki.rsa=d.rsa=d.rsa||{};var g=d.pki,t=[6,4,2,4,2,4,6,2],u={name:"PrivateKeyInfo",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"PrivateKeyInfo.version",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,
constructed:!1,capture:"privateKeyVersion"},{name:"PrivateKeyInfo.privateKeyAlgorithm",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"AlgorithmIdentifier.algorithm",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"privateKeyOid"}]},{name:"PrivateKeyInfo",tagClass:a.Class.UNIVERSAL,type:a.Type.OCTETSTRING,constructed:!1,capture:"privateKey"}]},v={name:"RSAPrivateKey",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"RSAPrivateKey.version",
tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"privateKeyVersion"},{name:"RSAPrivateKey.modulus",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"privateKeyModulus"},{name:"RSAPrivateKey.publicExponent",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"privateKeyPublicExponent"},{name:"RSAPrivateKey.privateExponent",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"privateKeyPrivateExponent"},{name:"RSAPrivateKey.prime1",
tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"privateKeyPrime1"},{name:"RSAPrivateKey.prime2",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"privateKeyPrime2"},{name:"RSAPrivateKey.exponent1",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"privateKeyExponent1"},{name:"RSAPrivateKey.exponent2",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"privateKeyExponent2"},{name:"RSAPrivateKey.coefficient",tagClass:a.Class.UNIVERSAL,
type:a.Type.INTEGER,constructed:!1,capture:"privateKeyCoefficient"}]},w={name:"RSAPublicKey",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"RSAPublicKey.modulus",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"publicKeyModulus"},{name:"RSAPublicKey.exponent",tagClass:a.Class.UNIVERSAL,type:a.Type.INTEGER,constructed:!1,capture:"publicKeyExponent"}]},x=d.pki.rsa.publicKeyValidator={name:"SubjectPublicKeyInfo",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,
constructed:!0,captureAsn1:"subjectPublicKeyInfo",value:[{name:"SubjectPublicKeyInfo.AlgorithmIdentifier",tagClass:a.Class.UNIVERSAL,type:a.Type.SEQUENCE,constructed:!0,value:[{name:"AlgorithmIdentifier.algorithm",tagClass:a.Class.UNIVERSAL,type:a.Type.OID,constructed:!1,capture:"publicKeyOid"}]},{name:"SubjectPublicKeyInfo.subjectPublicKey",tagClass:a.Class.UNIVERSAL,type:a.Type.BITSTRING,constructed:!1,value:[{name:"SubjectPublicKeyInfo.subjectPublicKey.RSAPublicKey",tagClass:a.Class.UNIVERSAL,
type:a.Type.SEQUENCE,constructed:!0,optional:!0,captureAsn1:"rsaPublicKey"}]}]},C=function(b){var h;if(b.algorithm in g.oids)h=g.oids[b.algorithm];else throw{message:"Unknown message digest algorithm.",algorithm:b.algorithm};var c=a.oidToDer(h).getBytes();h=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[]);var k=a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[]);k.value.push(a.create(a.Class.UNIVERSAL,a.Type.OID,!1,c));k.value.push(a.create(a.Class.UNIVERSAL,a.Type.NULL,!1,""));b=a.create(a.Class.UNIVERSAL,
a.Type.OCTETSTRING,!1,b.digest().getBytes());h.value.push(k);h.value.push(b);return a.toDer(h).getBytes()},y=function(b,a,c){if(c)a=b.modPow(a.e,a.n);else if(a.p&&a.q){a.dP||(a.dP=a.d.mod(a.p.subtract(l.ONE)));a.dQ||(a.dQ=a.d.mod(a.q.subtract(l.ONE)));a.qInv||(a.qInv=a.q.modInverse(a.p));c=b.mod(a.p).modPow(a.dP,a.p);for(b=b.mod(a.q).modPow(a.dQ,a.q);0>c.compareTo(b);)c=c.add(a.p);a=c.subtract(b).multiply(a.qInv).mod(a.p).multiply(a.q).add(b)}else a=b.modPow(a.d,a.n);return a};g.rsa.encrypt=function(b,
a,c){var k=c,f=Math.ceil(a.n.bitLength()/8);!1!==c&&!0!==c?(k=2===c,c=p(b,a,c)):(c=d.util.createBuffer(),c.putBytes(b));b=new l(c.toHex(),16);a=y(b,a,k).toString(16);k=d.util.createBuffer();for(f-=Math.ceil(a.length/2);0<f;)k.putByte(0),--f;k.putBytes(d.util.hexToBytes(a));return k.getBytes()};g.rsa.decrypt=function(b,a,c,k){var f=Math.ceil(a.n.bitLength()/8);if(b.length!==f)throw{message:"Encrypted message length is invalid.",length:b.length,expected:f};b=new l(d.util.createBuffer(b).toHex(),16);
if(0<=b.compareTo(a.n))throw{message:"Encrypted message is invalid."};b=y(b,a,c).toString(16);for(var e=d.util.createBuffer(),f=f-Math.ceil(b.length/2);0<f;)e.putByte(0),--f;e.putBytes(d.util.hexToBytes(b));return!1!==k?m(e.getBytes(),a,c):e.getBytes()};g.rsa.createKeyPairGenerationState=function(b,a,c){"string"===typeof b&&(b=parseInt(b,10));b=b||2048;c=c||{};c.prng=c.prng||d.random;b={state:0,bits:b,rng:{nextBytes:function(b){for(var a=c.prng.getBytesSync(b.length),e=0;e<b.length;++e)b[e]=a.charCodeAt(e)}},
eInt:a||65537,e:new l(null),p:null,q:null,qBits:b>>1,pBits:b-(b>>1),pqState:0,num:null,keys:null};b.e.fromInt(b.eInt);return b};g.rsa.stepKeyPairGenerationState=function(b,a){var c=new l(null);c.fromInt(30);for(var k=0,f=function(b,a){return b|a},e=+new Date,d,q=0;null===b.keys&&(0>=a||q<a);){if(0===b.state){d=null===b.p?b.pBits:b.qBits;var m=d-1;0===b.pqState?(b.num=new l(d,b.rng),b.num.testBit(m)||b.num.bitwiseTo(l.ONE.shiftLeft(m),f,b.num),b.num.dAddOffset(31-b.num.mod(c).byteValue(),0),k=0,++b.pqState):
1===b.pqState?b.num.bitLength()>d?b.pqState=0:b.num.isProbablePrime(B(b.num.bitLength()))?++b.pqState:b.num.dAddOffset(t[k++%8],0):2===b.pqState?b.pqState=0===b.num.subtract(l.ONE).gcd(b.e).compareTo(l.ONE)?3:0:3===b.pqState&&(b.pqState=0,null===b.p?b.p=b.num:b.q=b.num,null!==b.p&&null!==b.q&&++b.state,b.num=null)}else 1===b.state?(0>b.p.compareTo(b.q)&&(b.num=b.p,b.p=b.q,b.q=b.num),++b.state):2===b.state?(b.p1=b.p.subtract(l.ONE),b.q1=b.q.subtract(l.ONE),b.phi=b.p1.multiply(b.q1),++b.state):3===
b.state?0===b.phi.gcd(b.e).compareTo(l.ONE)?++b.state:(b.p=null,b.q=null,b.state=0):4===b.state?(b.n=b.p.multiply(b.q),b.n.bitLength()===b.bits?++b.state:(b.q=null,b.state=0)):5===b.state&&(d=b.e.modInverse(b.phi),b.keys={privateKey:g.rsa.setPrivateKey(b.n,b.e,d,b.p,b.q,d.mod(b.p1),d.mod(b.q1),b.q.modInverse(b.p)),publicKey:g.rsa.setPublicKey(b.n,b.e)});d=+new Date;q+=d-e;e=d}return null!==b.keys};g.rsa.generateKeyPair=function(b,a,c,d){1===arguments.length?"object"===typeof b?(c=b,b=void 0):"function"===
typeof b&&(d=b,b=void 0):2===arguments.length?("number"===typeof b?"function"===typeof a?d=a:c=a:(c=b,d=a,b=void 0),a=void 0):3===arguments.length&&("number"===typeof a?"function"===typeof c&&(d=c,c=void 0):(d=c,c=a,a=void 0));c=c||{};void 0===b&&(b=c.bits||2048);void 0===a&&(a=c.e||65537);var f=g.rsa.createKeyPairGenerationState(b,a,c);if(!d)return g.rsa.stepKeyPairGenerationState(f,0),f.keys;z(f,c,d)};g.setRsaPublicKey=g.rsa.setPublicKey=function(b,h){var c={n:b,e:h,encrypt:function(b,a,e){"string"===
typeof a?a=a.toUpperCase():void 0===a&&(a="RSAES-PKCS1-V1_5");if("RSAES-PKCS1-V1_5"===a)a={encode:function(b,a,c){return p(b,a,2).getBytes()}};else if("RSA-OAEP"===a||"RSAES-OAEP"===a)a={encode:function(b,a){return d.pkcs1.encode_rsa_oaep(a,b,e)}};else if(-1!==["RAW","NONE","NULL",null].indexOf(a))a={encode:function(b){return b}};else throw{message:'Unsupported encryption scheme: "'+a+'".'};b=a.encode(b,c,!0);return g.rsa.encrypt(b,c,!0)},verify:function(b,d,e){"string"===typeof e?e=e.toUpperCase():
void 0===e&&(e="RSASSA-PKCS1-V1_5");if("RSASSA-PKCS1-V1_5"===e)e={verify:function(b,d){d=m(d,c,!0);var e=a.fromDer(d);return b===e.value[1].value}};else if("NONE"===e||"NULL"===e||null===e)e={verify:function(b,a){a=m(a,c,!0);return b===a}};d=g.rsa.decrypt(d,c,!0,!1);return e.verify(b,d,c.n.bitLength())}};return c};g.setRsaPrivateKey=g.rsa.setPrivateKey=function(b,a,c,k,f,e,l,n){var p={n:b,e:a,d:c,p:k,q:f,dP:e,dQ:l,qInv:n,decrypt:function(b,a,c){"string"===typeof a?a=a.toUpperCase():void 0===a&&(a=
"RSAES-PKCS1-V1_5");b=g.rsa.decrypt(b,p,!1,!1);if("RSAES-PKCS1-V1_5"===a)a={decode:m};else if("RSA-OAEP"===a||"RSAES-OAEP"===a)a={decode:function(b,a){return d.pkcs1.decode_rsa_oaep(a,b,c)}};else if(-1!==["RAW","NONE","NULL",null].indexOf(a))a={decode:function(b){return b}};else throw{message:'Unsupported encryption scheme: "'+a+'".'};return a.decode(b,p,!1)},sign:function(b,a){var c=!1;"string"===typeof a&&(a=a.toUpperCase());if(void 0===a||"RSASSA-PKCS1-V1_5"===a)a={encode:C},c=1;else if("NONE"===
a||"NULL"===a||null===a)a={encode:function(){return b}},c=1;var d=a.encode(b,p.n.bitLength());return g.rsa.encrypt(d,p,c)}};return p};g.wrapRsaPrivateKey=function(b){return a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,a.integerToDer(0).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.rsaEncryption).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.NULL,!1,"")]),a.create(a.Class.UNIVERSAL,
a.Type.OCTETSTRING,!1,a.toDer(b).getBytes())])};g.privateKeyFromAsn1=function(b){var h={},c=[];a.validate(b,u,h,c)&&(b=a.fromDer(d.util.createBuffer(h.privateKey)));h={};c=[];if(!a.validate(b,v,h,c))throw{message:"Cannot read private key. ASN.1 object does not contain an RSAPrivateKey.",errors:c};var k,f,e,m,n;b=d.util.createBuffer(h.privateKeyModulus).toHex();c=d.util.createBuffer(h.privateKeyPublicExponent).toHex();k=d.util.createBuffer(h.privateKeyPrivateExponent).toHex();f=d.util.createBuffer(h.privateKeyPrime1).toHex();
e=d.util.createBuffer(h.privateKeyPrime2).toHex();m=d.util.createBuffer(h.privateKeyExponent1).toHex();n=d.util.createBuffer(h.privateKeyExponent2).toHex();h=d.util.createBuffer(h.privateKeyCoefficient).toHex();return g.setRsaPrivateKey(new l(b,16),new l(c,16),new l(k,16),new l(f,16),new l(e,16),new l(m,16),new l(n,16),new l(h,16))};g.privateKeyToAsn1=g.privateKeyToRSAPrivateKey=function(b){return a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,a.integerToDer(0).getBytes()),
a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.n)),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.e)),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.d)),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.p)),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.q)),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.dP)),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.dQ)),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.qInv))])};g.publicKeyFromAsn1=function(b){var h={},c=[];if(a.validate(b,x,h,c)){b=
a.derToOid(h.publicKeyOid);if(b!==g.oids.rsaEncryption)throw{message:"Cannot read public key. Unknown OID.",oid:b};b=h.rsaPublicKey}c=[];if(!a.validate(b,w,h,c))throw{message:"Cannot read public key. ASN.1 object does not contain an RSAPublicKey.",errors:c};b=d.util.createBuffer(h.publicKeyModulus).toHex();h=d.util.createBuffer(h.publicKeyExponent).toHex();return g.setRsaPublicKey(new l(b,16),new l(h,16))};g.publicKeyToAsn1=g.publicKeyToSubjectPublicKeyInfo=function(b){return a.create(a.Class.UNIVERSAL,
a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.OID,!1,a.oidToDer(g.oids.rsaEncryption).getBytes()),a.create(a.Class.UNIVERSAL,a.Type.NULL,!1,"")]),a.create(a.Class.UNIVERSAL,a.Type.BITSTRING,!1,[g.publicKeyToRSAPublicKey(b)])])};g.publicKeyToRSAPublicKey=function(b){return a.create(a.Class.UNIVERSAL,a.Type.SEQUENCE,!0,[a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.n)),a.create(a.Class.UNIVERSAL,a.Type.INTEGER,!1,n(b.e))])}}if("function"!==typeof define)if("object"===
typeof module&&module.exports){var w=!0;define=function(d,p){p(require,module)}}else return"undefined"===typeof forge&&(forge={}),t(forge);var u,x=function(d,p){p.exports=function(m){var p=u.map(function(m){return d(m)}).concat(t);m=m||{};m.defined=m.defined||{};if(m.defined.rsa)return m.rsa;m.defined.rsa=!0;for(var n=0;n<p.length;++n)p[n](m);return m.rsa}},v=define;define=function(d,p){u="string"===typeof d?p.slice(2):d.slice(2);if(w)return delete define,v.apply(null,Array.prototype.slice.call(arguments,
0));define=v;return define.apply(null,Array.prototype.slice.call(arguments,0))};define("require module ./asn1 ./oids ./random ./util ./jsbn ./pkcs1".split(" "),function(){x.apply(null,Array.prototype.slice.call(arguments,0))})})();
