(function(){function k(d){var g={},f=0;d.debug.set("forge.task","tasks",g);var c={};d.debug.set("forge.task","queues",c);var b={ready:{}};b.ready.stop="ready";b.ready.start="running";b.ready.cancel="done";b.ready.fail="error";b.running={};b.running.stop="ready";b.running.start="running";b.running.block="blocked";b.running.unblock="running";b.running.sleep="sleeping";b.running.wakeup="running";b.running.cancel="done";b.running.fail="error";b.blocked={};b.blocked.stop="blocked";b.blocked.start="blocked";
b.blocked.block="blocked";b.blocked.unblock="blocked";b.blocked.sleep="blocked";b.blocked.wakeup="blocked";b.blocked.cancel="done";b.blocked.fail="error";b.sleeping={};b.sleeping.stop="sleeping";b.sleeping.start="sleeping";b.sleeping.block="sleeping";b.sleeping.unblock="sleeping";b.sleeping.sleep="sleeping";b.sleeping.wakeup="sleeping";b.sleeping.cancel="done";b.sleeping.fail="error";b.done={};b.done.stop="done";b.done.start="done";b.done.block="done";b.done.unblock="done";b.done.sleep="done";b.done.wakeup=
"done";b.done.cancel="done";b.done.fail="error";b.error={};b.error.stop="error";b.error.start="error";b.error.block="error";b.error.unblock="error";b.error.sleep="error";b.error.wakeup="error";b.error.cancel="error";b.error.fail="error";var e=function(a){this.id=-1;this.name=a.name||"?";this.parent=a.parent||null;this.run=a.run;this.subtasks=[];this.error=!1;this.state="ready";this.blocks=0;this.userData=this.swapTime=this.timeoutId=null;this.id=f++;g[this.id]=this};e.prototype.debug=function(a){d.log.debug("forge.task",
a||"","[%s][%s] task:",this.id,this.name,this,"subtasks:",this.subtasks.length,"queue:",c)};e.prototype.next=function(a,b){"function"===typeof a&&(b=a,a=this.name);var d=new e({run:b,name:a,parent:this});d.state="running";d.type=this.type;d.successCallback=this.successCallback||null;d.failureCallback=this.failureCallback||null;this.subtasks.push(d);return this};e.prototype.parallel=function(a,b){d.util.isArray(a)&&(b=a,a=this.name);return this.next(a,function(c){c.block(b.length);for(var e=function(a,
e){d.task.start({type:a,run:function(a){b[e](a)},success:function(a){c.unblock()},failure:function(a){c.unblock()}})},f=0;f<b.length;f++)e(a+"__parallel-"+c.id+"-"+f,f)})};e.prototype.stop=function(){this.state=b[this.state].stop};e.prototype.start=function(){this.error=!1;this.state=b[this.state].start;"running"===this.state&&(this.start=new Date,this.run(this),h(this,0))};e.prototype.block=function(a){this.blocks+="undefined"===typeof a?1:a;0<this.blocks&&(this.state=b[this.state].block)};e.prototype.unblock=
function(a){this.blocks-="undefined"===typeof a?1:a;0===this.blocks&&"done"!==this.state&&(this.state="running",h(this,0));return this.blocks};e.prototype.sleep=function(a){this.state=b[this.state].sleep;var d=this;this.timeoutId=setTimeout(function(){d.timeoutId=null;d.state="running";h(d,0)},"undefined"===typeof a?0:a)};e.prototype.wait=function(a){a.wait(this)};e.prototype.wakeup=function(){"sleeping"===this.state&&(cancelTimeout(this.timeoutId),this.timeoutId=null,this.state="running",h(this,
0))};e.prototype.cancel=function(){this.state=b[this.state].cancel;this.permitsNeeded=0;null!==this.timeoutId&&(cancelTimeout(this.timeoutId),this.timeoutId=null);this.subtasks=[]};e.prototype.fail=function(a){this.error=!0;l(this,!0);if(a)a.error=this.error,a.swapTime=this.swapTime,a.userData=this.userData,h(a,0);else{if(null!==this.parent){for(a=this.parent;null!==a.parent;)a.error=this.error,a.swapTime=this.swapTime,a.userData=this.userData,a=a.parent;l(a,!0)}this.failureCallback&&this.failureCallback(this)}};
var k=function(a){a.error=!1;a.state=b[a.state].start;setTimeout(function(){"running"===a.state&&(a.swapTime=+new Date,a.run(a),h(a,0))},0)},h=function(a,b){var d=30<b||20<+new Date-a.swapTime,c=function(b){b++;if("running"===a.state)if(d&&(a.swapTime=+new Date),0<a.subtasks.length){var c=a.subtasks.shift();c.error=a.error;c.swapTime=a.swapTime;c.userData=a.userData;c.run(c);c.error||h(c,b)}else l(a),a.error||null===a.parent||(a.parent.error=a.error,a.parent.swapTime=a.swapTime,a.parent.userData=
a.userData,h(a.parent,b))};d?setTimeout(c,0):c(b)},l=function(a,b){a.state="done";delete g[a.id];null===a.parent&&(a.type in c?0===c[a.type].length?d.log.error("forge.task","[%s][%s] task queue empty [%s]",a.id,a.name,a.type):c[a.type][0]!==a?d.log.error("forge.task","[%s][%s] task not first in queue [%s]",a.id,a.name,a.type):(c[a.type].shift(),0===c[a.type].length?delete c[a.type]:c[a.type][0].start()):d.log.error("forge.task","[%s][%s] task queue missing [%s]",a.id,a.name,a.type),b||(a.error&&a.failureCallback?
a.failureCallback(a):!a.error&&a.successCallback&&a.successCallback(a)))};d.task=d.task||{};d.task.start=function(a){var b=new e({run:a.run,name:a.name||"?"});b.type=a.type;b.successCallback=a.success||null;b.failureCallback=a.failure||null;b.type in c?c[a.type].push(b):(c[b.type]=[b],k(b))};d.task.cancel=function(a){a in c&&(c[a]=[c[a][0]])};d.task.createCondition=function(){var a={tasks:{},wait:function(b){b.id in a.tasks||(b.block(),a.tasks[b.id]=b)},notify:function(){var b=a.tasks;a.tasks={};
for(var c in b)b[c].unblock()}};return a}}if("function"!==typeof define)if("object"===typeof module&&module.exports){var p=!0;define=function(d,g){g(require,module)}}else return"undefined"===typeof forge&&(forge={}),k(forge);var m,q=function(d,g){g.exports=function(f){var c=m.map(function(b){return d(b)}).concat(k);f=f||{};f.defined=f.defined||{};if(f.defined.task)return f.task;f.defined.task=!0;for(var b=0;b<c.length;++b)c[b](f);return f.task}},n=define;define=function(d,g){m="string"===typeof d?
g.slice(2):d.slice(2);if(p)return delete define,n.apply(null,Array.prototype.slice.call(arguments,0));define=n;return define.apply(null,Array.prototype.slice.call(arguments,0))};define(["require","module","./debug","./log","./util"],function(){q.apply(null,Array.prototype.slice.call(arguments,0))})})();
