(function(t){var n=null,p=0,q=null,k=null,d={},r=10;"undefined"===typeof forge&&(forge={});var u=forge.net,m=forge.http;forge.xhr={init:function(a){forge.log.debug("forge.xhr","initializing",a);p=a.policyPort||p;q=a.policyUrl||q;r=a.connections||r;n=u.createSocketPool({flashId:a.flashId,policyPort:p,policyUrl:q,msie:a.msie||!1});k=m.createClient({url:a.url||window.location.protocol+"//"+window.location.host,socketPool:n,policyPort:p,policyUrl:q,connections:a.connections||r,caCerts:a.caCerts,cipherSuites:a.cipherSuites,
persistCookies:a.persistCookies||!0,primeTlsSockets:a.primeTlsSockets||!1,verify:a.verify,getCertificate:a.getCertificate,getPrivateKey:a.getPrivateKey,getSignature:a.getSignature});d[k.url.full]=k;forge.log.debug("forge.xhr","ready")},cleanup:function(){for(var a in d)d[a].destroy();d={};k=null;n.destroy();n=null},setCookie:function(a){a.maxAge=a.maxAge||-1;if(a.domain)for(var g in d){var e=d[g];m.withinCookieDomain(e.url,a)&&e.secure===a.secure&&e.setCookie(a)}else k.setCookie(a)},getCookie:function(a,
g,e){var c=null;if(e)for(var h in d){var f=d[h];m.withinCookieDomain(f.url,e)&&(f=f.getCookie(a,g),null!==f&&(null===c?c=f:forge.util.isArray(c)?c.push(f):c=[c,f]))}else c=k.getCookie(a,g);return c},removeCookie:function(a,g,e){var c=!1;if(e)for(var h in d){var f=d[h];m.withinCookieDomain(f.url,e)&&f.removeCookie(a,g)&&(c=!0)}else c=k.removeCookie(a,g);return c},create:function(a){a=t.extend({logWarningOnError:!0,verbose:!1,logError:function(){},logWarning:function(){},logDebug:function(){},logVerbose:function(){},
url:null},a||{});var g=null,e=null,c=null,h=!1,f={error:a.logError||forge.log.error,warning:a.logWarning||forge.log.warning,debug:a.logDebug||forge.log.debug,verbose:a.logVerbose||forge.log.verbose},b={onreadystatechange:null,readyState:0,responseText:"",responseXML:null,status:0,statusText:""};if(null===a.url)g=k;else{var s=m.parseUrl(a.url);if(!s)throw{message:"Invalid url.",details:{url:a.url}};s.full in d?g=d[s.full]:(g=m.createClient({url:a.url,socketPool:n,policyPort:a.policyPort||p,policyUrl:a.policyUrl||
q,connections:a.connections||r,caCerts:a.caCerts,cipherSuites:a.cipherSuites,persistCookies:a.persistCookies||!0,primeTlsSockets:a.primeTlsSockets||!1,verify:a.verify,getCertificate:a.getCertificate,getPrivateKey:a.getPrivateKey,getSignature:a.getSignature}),d[s.full]=g)}b.open=function(a,c,f,v,w){switch(a){case "DELETE":case "GET":case "HEAD":case "OPTIONS":case "PATCH":case "POST":case "PUT":break;case "CONNECT":case "TRACE":case "TRACK":throw 18;default:throw 12;}h=!1;b.responseText="";b.responseXML=
null;b.status=0;b.statusText="";e=m.createRequest({method:a,path:c});b.readyState=1;if(b.onreadystatechange)b.onreadystatechange()};b.setRequestHeader=function(a,c){if(1!=b.readyState||h)throw 11;e.setField(a,c)};b.send=function(a){if(1!=b.readyState||h)throw 11;if(a&&"GET"!==e.method&&"HEAD"!==e.method)if("undefined"!==typeof XMLSerializer)if(a instanceof Document){var d=new XMLSerializer;e.body=d.serializeToString(a)}else e.body=a;else e.body="undefined"!==typeof a.xml?a.xml:a;h=!0;if(b.onreadystatechange)b.onreadystatechange();
var l={};l.request=e;l.headerReady=function(a){b.cookies=g.cookies;b.readyState=2;b.status=a.response.code;b.statusText=a.response.message;c=a.response;if(b.onreadystatechange)b.onreadystatechange();if(!c.aborted&&(b.readyState=3,b.onreadystatechange))b.onreadystatechange()};l.bodyReady=function(a){b.readyState=4;var c=a.response.getField("Content-Type");if(c&&(0===c.indexOf("text/xml")||0===c.indexOf("application/xml")||-1!==c.indexOf("+xml")))try{var d=new ActiveXObject("MicrosoftXMLDOM");d.async=
!1;d.loadXML(a.response.body);b.responseXML=d}catch(g){c=new DOMParser,b.responseXML=c.parseFromString(g.body,"text/xml")}c=0;null!==a.response.body&&(b.responseText=a.response.body,c=a.response.body.length);d=e;c=d.method+" "+d.path+" "+b.status+" "+b.statusText+" "+c+"B "+(a.request.connectTime+a.request.time+a.response.time)+"ms";l.verbose?(d=400<=b.status&&l.logWarningOnError?f.warning:f.verbose,d("forge.xhr",c,a,a.response.body?"\n"+a.response.body:"\nNo content")):(d=400<=b.status&&l.logWarningOnError?
f.warning:f.debug,d("forge.xhr",c));if(b.onreadystatechange)b.onreadystatechange()};l.error=function(a){var c=e;f.error("forge.xhr",c.method+" "+c.path,a);b.responseText="";b.responseXML=null;b.status=0;b.statusText="";b.readyState=4;if(b.onreadystatechange)b.onreadystatechange()};g.send(l)};b.abort=function(){e.abort();b.responseText="";b.responseXML=null;b.status=0;b.statusText="";c=e=null;if(4!==b.readyState&&0!==b.readyState&&(1!==b.readyState||h)&&(b.readyState=4,h=!1,b.onreadystatechange))b.onreadystatechange();
b.readyState=0};b.getAllResponseHeaders=function(){var a="";null!==c&&t.each(c.fields,function(b,c){t.each(c,function(c,d){a+=b+": "+d+"\r\n"})});return a};b.getResponseHeader=function(a){var b=null;null!==c&&a in c.fields&&(b=c.fields[a],forge.util.isArray(b)&&(b=b.join()));return b};return b}}})(jQuery);
