var randomString=function(b){for(var a="",c=0;c<b;c++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return a},Client=function(b){this.address=b;this.senders={};this.listeners={};this.callbacks={};this.directAccess=!1;this.sendMessage=function(a,b){void 0!==a.to&&this.senders[a.to]?("undefined"!==typeof b&&this.addCallbackListener(a,b),this.senders[a.to](a)):console.log("ERROR. No sender found for the message "+a.type+" from "+a.from+" to "+
a.to)};this.processIncoming=function(a){"console_log"!=a.type&&console.log(this.address+" has got "+(a.response?"response":"message")+' "'+a.type+'" from '+a.from);if(a.to===this.address)if(a.response&&a.id in this.callbacks)this.callbacks[a.id](a),delete this.callbacks[a.id];else{if(a.from in this.listeners)for(var b=this.listeners[a.from],d=0;d<b.length;d++)try{if(b[d]&&b[d](a))return!0}catch(e){console.log("ignoring bad event listener; exception:",e)}console.log("ERROR processing message. No handler found",
a)}else this.sendMessage(a)}};Client.prototype.settings={};Client.prototype.composeResponse=function(b,a){b.response=!0;var c=b.from;b.from=b.to;b.to=c;delete b.data;"function"===typeof b.sendResponse&&delete b.sendResponse;for(var d in a)b[d]=a[d];return b};Client.prototype.addSender=function(b,a){for(var c=this.forceArray(b),d=0;d<b.length;d++)void 0!==c[d]&&(this.senders[c[d]]=a)};Client.prototype.addCallbackListener=function(b,a){this.callbacks[b.id]=a};
Client.prototype.addListener=function(b,a){b=this.forceArray(b);for(var c=0;c<b.length;c++)this.listeners[b[c]]?this.listeners[b[c]].push(a):this.listeners[b[c]]=[a]};Client.prototype.dispatchMessage=function(b,a,c,d){b=this.composeMessage("background",b,a);a=function(a){a=a.data;"object"===typeof a&&"error"in a?"undefined"!==typeof d&&d(a.error):"undefined"!==typeof c&&c(a.data)};this.directAccess?this.background.processAPIMessage(b,a):this.sendMessage(b,a)};
Client.prototype.composeMessage=function(b,a,c){return{id:randomString(10),type:a,data:c,from:this.address,to:b}};
Client.prototype.initApiCalls=function(){this.doExtensionLogin=function(b){if(this.directAccess){var a=this;helper.isPopup(function(c){c?a.background.doLogin(b,999999999):helper.tabs.getSelected(function(c){a.background.doLogin(b,c.index+1)})})}else this.sendMessage(this.composeMessage("background","login",b))};this.getIdentity=function(b,a){this.dispatchMessage("getIdentity",null,b,a)};this.getLoginState=function(b,a){this.dispatchMessage("getLoginState",null,b,a)};this.mitroLogout=function(b,a){this.dispatchMessage("mitroLogout",
null,b,a)};this.getSiteSecretData=function(b,a,c){this.dispatchMessage("getSiteSecretData",b,a,c)};this.getSiteSecretDataForDisplay=function(b,a,c){this.dispatchMessage("getSiteSecretDataForDisplay",b,a,c)};this.addSecret=function(b,a,c,d,e){this.dispatchMessage("addSecret",{serverData:b,clientData:a,secretData:c},d,e)};this.addSecretToGroups=function(b,a,c){this.dispatchMessage("addSecretToGroups",b,a,c)};this.editSecret=function(b,a,c,d,e,f){this.dispatchMessage("editSecret",{secretId:b,serverData:a,
clientData:c,secretData:d},e,f)};this.removeSecret=function(b,a,c){this.dispatchMessage("removeSecret",b,a,c)};this.editSiteShares=function(b,a,c,d,e,f){this.dispatchMessage("editSiteShares",{secretId:b,groupIdList:a,identityList:c,orgGroupId:d},e,f)};this.listUsersGroupsAndSecrets=function(b,a){this.dispatchMessage("listUsersGroupsAndSecrets",null,b,a)};this.listGroups=function(b,a){this.dispatchMessage("listUsersGroupsAndSecrets",null,function(a){b(a.groups)},a)};this.listUsers=function(b,a){this.dispatchMessage("listUsersGroupsAndSecrets",
null,function(a){b(a.users)},a)};this.fetchServices=function(b,a){this.dispatchMessage("listUsersGroupsAndSecrets",null,function(a){b(a.secrets)},a)};this.getGroup=function(b,a,c){this.dispatchMessage("getGroup",b,a,c)};this.addGroup=function(b,a,c){this.dispatchMessage("addGroup",b,a,c)};this.removeGroup=function(b,a,c){this.dispatchMessage("removeGroup",b,a,c)};this.editGroup=function(b,a,c,d,e,f){this.dispatchMessage("editGroup",{groupId:b,name:a,groupIdList:c?[c]:null,identityList:d},e,f)};this.addIssue=
function(b,a,c,d,e,f){this.dispatchMessage("addIssue",{type:b,url:a,description:c,email:d},e,f)};this.getAuditLog=function(b,a,c,d,e,f,g){this.dispatchMessage("getAuditLog",{orgId:b,offset:a,limit:c,startTimeMs:d,endTimeMs:e},f,g)};this.createOrganization=function(b,a,c){this.dispatchMessage("createOrganization",b,a,c)};this.getOrganizationInfo=function(b,a){this.dispatchMessage("getOrganizationInfo",null,b,a)};this.getOrganization=function(b,a,c){this.dispatchMessage("getOrganization",b,a,c)};this.selectOrganization=
function(b,a,c){this.dispatchMessage("selectOrganization",b,a,c)};this.mutateOrganization=function(b,a,c,d,e,f,g){this.dispatchMessage("mutateOrganization",{orgId:b,membersToPromote:a,newMembers:c,adminsToDemote:d,membersToRemove:e},f,g)};this.changeRemotePassword=function(b,a,c){this.dispatchMessage("changeRemotePassword",b,a,c)}};
Client.prototype.processCallbacks=function(b){for(var a=b.data,c=0;c<a.length;c++)"string"===typeof a[c]&&0===a[c].indexOf("_callback_")&&(a[c]=function(){var d=a[c].substr(10);return function(a){b.sendResponse({data:{callback:d,data:a}})}}());return a};
Client.prototype.setMethod=function(b,a){var c=this;this[a]=this.directAccess?this[b][a]:function(){for(var d=Array.prototype.slice.call(arguments),e=[],f=0;f<d.length;f++)"function"===typeof d[f]&&(e.push(d[f]),d[f]="_callback_"+(e.length-1));d=c.composeMessage(b,a,d);c.sendMessage(d,function(a){e[a.data.callback](a.data.data)})}};Client.prototype.initRemoteCalls=function(b,a){a=this.forceArray(a);for(var c=0;c<a.length;c++)this.setMethod(b,a[c])};
Client.prototype.forceArray=function(b){switch(typeof b){case "object":return"[object Array]"===Object.prototype.toString.call(b)?b:[b];case "undefined":return[];default:return[b]}};Client.prototype.isLoggedIn=function(){try{if(this.background&&this.background.isLoggedIn())return!0}finally{return!1}};
Client.prototype.initRemoteExecution=function(b,a,c){var d=c?c:window;a=this.forceArray(a);b=this.forceArray(b);for(c=0;c<a.length;++c)d[a[c]]||console.log("WARNING: could not initRemoteExecution for method:",a[c]);var e=this;this.addListener(b,function(b){return function(b){var c=b.type;if(-1===a.indexOf(c))return!1;"console_log"!=c&&console.log("< remote_call > "+c);if(!d[c])return console.log("unknown method"+c),!1;b=e.processCallbacks(b);d[c].apply(null,b);return!0}}(this))};
"undefined"!==typeof exports&&(exports.Client=Client);
