RegExp.escape=function(b){return b.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")};
(function(b){b.csv={defaults:{separator:",",delimiter:'"',headers:!0},hooks:{castToScalar:function(f,a){if(isNaN(f))return f;if(/\./.test(f))return parseFloat(f);var e=parseInt(f);return isNaN(e)?null:e}},parsers:{parse:function(f,a){function e(){m=0;h="";if(a.start&&a.state.rowNum<a.start)d=[];else{if(void 0===a.onParseEntry)g.push(d);else{var c=a.onParseEntry(d,a.state);!1!==c&&g.push(c)}d=[];a.end&&a.state.rowNum>=a.end&&(p=!0)}a.state.rowNum++;a.state.colNum=1}function c(){if(void 0===a.onParseValue)d.push(h);
else{var c=a.onParseValue(h,a.state);!1!==c&&d.push(c)}h="";m=0;a.state.colNum++}var b=a.separator,l=a.delimiter;a.state.rowNum||(a.state.rowNum=1);a.state.colNum||(a.state.colNum=1);var g=[],d=[],m=0,h="",p=!1,n=RegExp.escape(b),r=RegExp.escape(l),q=/(D|S|\n|\r|[^DS\r\n]+)/,q=q.source,q=q.replace(/S/g,n),q=q.replace(/D/g,r),q=RegExp(q,"gm");f.replace(q,function(d){if(!p)switch(m){case 0:if(d===b){h+="";c();break}if(d===l){m=1;break}if("\n"===d){c();e();break}if(/^\r$/.test(d))break;h+=d;m=3;break;
case 1:if(d===l){m=2;break}h+=d;m=1;break;case 2:if(d===l){h+=d;m=1;break}if(d===b){c();break}if("\n"===d){c();e();break}if(/^\r$/.test(d))break;throw Error("CSVDataError: Illegal State [Row:"+a.state.rowNum+"][Col:"+a.state.colNum+"]");case 3:if(d===b){c();break}if("\n"===d){c();e();break}if(/^\r$/.test(d))break;if(d===l)throw Error("CSVDataError: Illegal Quote [Row:"+a.state.rowNum+"][Col:"+a.state.colNum+"]");throw Error("CSVDataError: Illegal Data [Row:"+a.state.rowNum+"][Col:"+a.state.colNum+
"]");default:throw Error("CSVDataError: Unknown State [Row:"+a.state.rowNum+"][Col:"+a.state.colNum+"]");}});0!==d.length&&(c(),e());return g},splitLines:function(b,a){function e(){g=0;if(a.start&&a.state.rowNum<a.start)d="";else{if(void 0===a.onParseEntry)l.push(d);else{var c=a.onParseEntry(d,a.state);!1!==c&&l.push(c)}d="";a.end&&a.state.rowNum>=a.end&&(m=!0)}a.state.rowNum++}var c=a.separator,k=a.delimiter;a.state.rowNum||(a.state.rowNum=1);var l=[],g=0,d="",m=!1,h=RegExp.escape(c),p=RegExp.escape(k),
n=/(D|S|\n|\r|[^DS\r\n]+)/,n=n.source,n=n.replace(/S/g,h),n=n.replace(/D/g,p),n=RegExp(n,"gm");b.replace(n,function(b){if(!m)switch(g){case 0:if(b===c){d+=b;g=0;break}if(b===k){d+=b;g=1;break}if("\n"===b){e();break}if(/^\r$/.test(b))break;d+=b;g=3;break;case 1:if(b===k){d+=b;g=2;break}d+=b;g=1;break;case 2:var n=d.substr(d.length-1);if(b===k&&n===k){d+=b;g=1;break}if(b===c){d+=b;g=0;break}if("\n"===b){e();break}if("\r"===b)break;throw Error("CSVDataError: Illegal state [Row:"+a.state.rowNum+"]");
case 3:if(b===c){d+=b;g=0;break}if("\n"===b){e();break}if("\r"===b)break;if(b===k)throw Error("CSVDataError: Illegal quote [Row:"+a.state.rowNum+"]");throw Error("CSVDataError: Illegal state [Row:"+a.state.rowNum+"]");default:throw Error("CSVDataError: Unknown state [Row:"+a.state.rowNum+"]");}});""!==d&&e();return l},parseEntry:function(b,a){function e(){if(void 0===a.onParseValue)l.push(d);else{var c=a.onParseValue(d,a.state);!1!==c&&l.push(c)}d="";g=0;a.state.colNum++}var c=a.separator,k=a.delimiter;
a.state.rowNum||(a.state.rowNum=1);a.state.colNum||(a.state.colNum=1);var l=[],g=0,d="";if(!a.match){var m=RegExp.escape(c),h=RegExp.escape(k),p=/(D|S|\n|\r|[^DS\r\n]+)/.source,p=p.replace(/S/g,m),p=p.replace(/D/g,h);a.match=RegExp(p,"gm")}b.replace(a.match,function(b){switch(g){case 0:if(b===c){d+="";e();break}if(b===k){g=1;break}if("\n"===b||"\r"===b)break;d+=b;g=3;break;case 1:if(b===k){g=2;break}d+=b;g=1;break;case 2:if(b===k){d+=b;g=1;break}if(b===c){e();break}if("\n"===b||"\r"===b)break;throw Error("CSVDataError: Illegal State [Row:"+
a.state.rowNum+"][Col:"+a.state.colNum+"]");case 3:if(b===c){e();break}if("\n"===b||"\r"===b)break;if(b===k)throw Error("CSVDataError: Illegal Quote [Row:"+a.state.rowNum+"][Col:"+a.state.colNum+"]");throw Error("CSVDataError: Illegal Data [Row:"+a.state.rowNum+"][Col:"+a.state.colNum+"]");default:throw Error("CSVDataError: Unknown State [Row:"+a.state.rowNum+"][Col:"+a.state.colNum+"]");}});e();return l}},toArray:function(f,a,e){a=void 0!==a?a:{};var c={};c.callback=void 0!==e&&"function"===typeof e?
e:!1;c.separator="separator"in a?a.separator:b.csv.defaults.separator;c.delimiter="delimiter"in a?a.delimiter:b.csv.defaults.delimiter;a={delimiter:c.delimiter,separator:c.separator,onParseEntry:a.onParseEntry,onParseValue:a.onParseValue,state:void 0!==a.state?a.state:{}};f=b.csv.parsers.parseEntry(f,a);if(c.callback)c.callback("",f);else return f},toArrays:function(f,a,e){a=void 0!==a?a:{};var c={};c.callback=void 0!==e&&"function"===typeof e?e:!1;c.separator="separator"in a?a.separator:b.csv.defaults.separator;
c.delimiter="delimiter"in a?a.delimiter:b.csv.defaults.delimiter;e=[];a={delimiter:c.delimiter,separator:c.separator,onParseEntry:a.onParseEntry,onParseValue:a.onParseValue,start:a.start,end:a.end,state:{rowNum:1,colNum:1}};e=b.csv.parsers.parse(f,a);if(c.callback)c.callback("",e);else return e},toObjects:function(f,a,e){a=void 0!==a?a:{};var c={};c.callback=void 0!==e&&"function"===typeof e?e:!1;c.separator="separator"in a?a.separator:b.csv.defaults.separator;c.delimiter="delimiter"in a?a.delimiter:
b.csv.defaults.delimiter;c.headers="headers"in a?a.headers:b.csv.defaults.headers;a.start="start"in a?a.start:1;c.headers&&a.start++;a.end&&c.headers&&a.end++;var k=[];e=[];a={delimiter:c.delimiter,separator:c.separator,onParseEntry:a.onParseEntry,onParseValue:a.onParseValue,start:a.start,end:a.end,state:{rowNum:1,colNum:1},match:!1};var k=b.csv.parsers.splitLines(f,{delimiter:c.delimiter,separator:c.separator,start:1,end:1,state:{rowNum:1,colNum:1}}),l=b.csv.toArray(k[0],a),k=b.csv.parsers.splitLines(f,
a);a.state.colNum=1;a.state.rowNum=l?2:1;f=0;for(var g=k.length;f<g;f++){var d=b.csv.toArray(k[f],a),m={},h;for(h in l)m[l[h]]=d[h];e.push(m);a.state.rowNum++}if(c.callback)c.callback("",e);else return e},fromArrays:function(f,a,e){a=void 0!==a?a:{};var c={};c.callback=void 0!==e&&"function"===typeof e?e:!1;c.separator="separator"in a?a.separator:b.csv.defaults.separator;c.delimiter="delimiter"in a?a.delimiter:b.csv.defaults.delimiter;c.escaper="escaper"in a?a.escaper:b.csv.defaults.escaper;c.experimental=
"experimental"in a?a.experimental:!1;if(!c.experimental)throw Error("not implemented");a=[];for(i in f)a.push(f[i]);if(c.callback)c.callback("",a);else return a},fromObjects2CSV:function(f,a,e){a=void 0!==a?a:{};var c={};c.callback=void 0!==e&&"function"===typeof e?e:!1;c.separator="separator"in a?a.separator:b.csv.defaults.separator;c.delimiter="delimiter"in a?a.delimiter:b.csv.defaults.delimiter;c.experimental="experimental"in a?a.experimental:!1;if(!c.experimental)throw Error("not implemented");
a=[];for(i in f)a.push(arrays[i]);if(c.callback)c.callback("",a);else return a}};b.csvEntry2Array=b.csv.toArray;b.csv2Array=b.csv.toArrays;b.csv2Dictionary=b.csv.toObjects})(jQuery);
