(function(){$(document).ready(function(){var k=$("#add-members-modal"),m=k.find(".member-list");initAddAcl(m,k.find(".search"));var n=decodeQueryString(window.location.search.slice(1));if("id"in n){var f=parseInt(n.id,10),e=null,t=0,u=showSpinny($(".team-member-list")),v=showSpinny($(".team-secret-list")),p=function(a){for(var b=0;b<a.length;++b){var c=a[b];c.renderedTitle=getRenderedTitle(c);c.host=getCanonicalHost(c.clientData.loginUrl);c.icon=c.hints&&c.hints.icons&&0<c.hints.icons.length?c.hints.icons[0]:
EMPTY_IMAGE}return a};mitro.loadUserDataAndGroup(f,function(a,b){e=a;hideSpinny($(".team-member-list"),u);hideSpinny($(".team-secret-list"),v);if(b){var c;c="number"===typeof b.owningOrgId?[{id:b.owningOrgId,name:b.owningOrgName}]:e.getOrganizations();initOrgDropdown($(".org-dropdown-group"),c,b.owningOrgId);c=e.getSecretsForGroup(f);var d=$(".large-team-icon");d.attr("data-icon-text",b.name);d.attr("src",EMPTY_IMAGE);replaceBlankImages(d);d=$("#team-info-form");d.find('input[name="name"]').val(b.name);
d.find('input[name="description"]').val(b.description);var d=processUsersForRendering(userIdsToUserMap(b.users)),g=$(".team-member-list");g.html(templates["team-members-template"].render({members:d}));replaceBlankImages(g.find(".member-icon"));c=p(c);c.sort(secretSortFunc);d=$(".team-secret-list");d.html(templates["team-secrets-template"].render({secrets:c}));replaceBlankImages(d.find(".secret-icon"))}else showErrorDialog("Invalid group id: "+f)},onBackgroundError);$("#team-info-form").submit(function(){var a=
$("#team-info-form"),b=a.find('input[name="name"]').val();if(!b)return showErrorDialog("Team name cannot be empty"),!1;a.find('input[name="description"]').val();var a=getOrgDropdownId($(".org-dropdown")),c=e.getGroup(f);background.editGroup(c.groupId,b,a,c.users,reload,onBackgroundError);return!1});$(".delete-team-link").click(function(){var a='Really delete team "'+e.getGroup(f).name+'"?';showDeleteDialog("Delete Team",a,function(){showSpinny($(this));background.removeGroup(f,function(){helper.setLocation("teams.html")},
onBackgroundError)})});$("#add-members-button").click(function(){var a=userIdsToUserMap(e.getUsersVisibleToGroup(f)),b=userIdsToUserMap(e.getGroup(f).users),c;for(c in b)a[c]=b[c];a=processUsersForRendering(a,b);m.html(templates["add-members-template"].render({users:a}));replaceBlankImages($(".member-icon"));showModal(k)});$(document).on("click",".remove-user",function(a){a=$(a.target).closest(".member").attr("data-id");var b="Remove "+a+" from team?",c=$("#delete-confirm-modal");c.find(".delete-message").text(b);
c.find('input[name="email"]').val(String(a));c.modal("show");return!1});var q=function(a,b){var c=[],d;for(d in a)a.hasOwnProperty(d)&&(b.hasOwnProperty(d)||c.push(a[d]));return c},r=function(a,b){for(var c={},d=0;d<a.length;++d)c[a[d][b]]=a[d];return c};$("#save-members-button").click(function(){showSpinny($(this));var a=$(this).closest(".modal").find('input[type="checkbox"]:checked'),a=_.map(a.toArray(),function(a){return $(a).closest(".member").attr("data-user-id")}),b=e.getGroup(f);background.editGroup(b.groupId,
b.name,b.owningOrgId,a,reload,onBackgroundError)});$("#remove-user-button").click(function(a){var b=$(a.target).closest(".modal").find('input[name="email"]').val();console.log("removing user "+b+" from team");a=e.getGroup(f);b=_.without(a.users,b);background.editGroup(a.groupId,a.name,a.owningOrgId,b,reload,onBackgroundError);showSpinny($(".spinny"))});var s=function(a,b){var c=$("#add-secrets-modal"),d=c.find(".secret-list");a=e.getGroup(f);b=e.getSecretsVisibleToGroup(f);b=p(b);b.sort(secretSortFunc);
for(var g=b,w=a,l=0;l<g.length;++l){var h=g[l];h.checkboxId="checkbox"+t++;-1!==h.groups.indexOf(w.groupId)?h.checked="checked":h.checked=""}d.html(templates["add-secrets-template"].render({secrets:b}));replaceBlankImages(d.find(".secret-icon"));showModal(c)};$("#add-secrets-button").click(function(){var a=e.getGroup(f);e.userBelongsToSameOrgAsGroup(f)?background.getOrganization(a.owningOrgId,function(b){s(a,e.getOrganizationSecrets(a.owningOrgId,b))},onBackgroundError):s(a,e.secrets)});$("#save-secrets-button").click(function(){showSpinny($(this));
var a=$(this).closest(".modal").find('input[type="checkbox"]:checked'),a=_.map(a.toArray(),function(a){a=$(a).closest(".secret");a=parseInt(a.attr("data-id"),10);return e.getSecret(a)}),b=e.getSecretsForGroup(f),b=r(b,"secretId"),a=r(a,"secretId"),c=q(b,a),d=q(a,b),g=function(){if(0===d.length)if(0===c.length)reload();else{var a=c.pop(),b=e.getGroup(f),h=g,k=onBackgroundError,b=_.without(a.groups,b.groupId);background.editSiteShares(a.secretId,b,a.users,a.owningOrgid,h,k)}else b=e.getGroup(f),a=d.pop(),
h=g,k=onBackgroundError,b=[b.groupId].concat(a.groups),background.editSiteShares(a.secretId,b,a.users,a.owningOrgid,h,k)};g()});$(document).on("click",".remove-secret",function(a){a=$(a.target).closest(".secret");var b=parseInt(a.attr("data-id"),10);a=e.getGroup(f);var b=e.getSecret(b),c=reload,d=onBackgroundError;a=_.without(b.groups,a.groupId);background.editSiteShares(b.secretId,a,b.users,b.owningOrgid,c,d)});registerLiveSearch($("#add-secrets-modal .search"),".secret-list > .secret");registerLiveSearch($("#add-members-modal .search"),
".member-list > .acl-item")}else showErrorDialog("Missing group id parameter")})})();
