var scrollPane=null,SCROLLPANE_OPTIONS={mouseWheelSpeed:30,horizontalGutter:5,verticalGutter:0,showArrows:!1},LOAD_ICONS_DELAY_MS=400,secretMap={},selectedSecretIndex=0,visibleServicesLength=0,SELECTED_CLASS="selected",highlightSecret=function(a){$("#context .secret-item."+SELECTED_CLASS).removeClass(SELECTED_CLASS);var b=$("#context .secret-item:visible");(visibleServicesLength=b.length)&&b[a]&&(a=$(b[a]),a.addClass(SELECTED_CLASS),scrollPane.scrollToElement(a,!1))},getSecretById=function(a){return secretMap[a]},
getSecretForItem=function(a){return getSecretById(a.attr("data-secret-id"))},populateServiceList=function(a){for(var b=0;b<a.length;++b){var c=a[b];processServiceInstanceForRendering(c);c.action===SecretAction.VIEW.action&&"note"!==c.clientData.type&&(c.buttonLabel=SecretAction.COPY.label,c.action=SecretAction.COPY.action,c.buttonImage=SecretAction.COPY.image);c.iconUrl=a[b].icon;c.icon="";secretMap[c.secretId]=c;c.isNote="note"===c.clientData.type?!0:!1}disambiguateTitles(a);a.sort(secretSortFunc);
a=templates["popup-service-template"].render({services:a,hasNoTeam:!1});$("#context").append(a);replaceBlankImages($(".organization"));scrollPane=$(".pane2").jScrollPane(SCROLLPANE_OPTIONS);scrollPane=scrollPane.data("jsp");highlightSecret(selectedSecretIndex);setTimeout(function(){$("#context .secret-item").each(function(){var a=$(this),b=getSecretForItem(a);a.find(".service-icon").attr("src",b.iconUrl)});replaceBlankImages($(".secret-item .service-icon"))},LOAD_ICONS_DELAY_MS)},renderActiveSecret=
function(a,b){processServiceInstanceForRendering(a);var c=b.parent(".pane"),c=c.length&&"invite"===c.data("pane")?templates["popup-invite-member-template"].render(a):templates["popup-active-service-template"].render(a);b.html(c);replaceBlankImages($(".member-icon"))};
$(document).ready(function(){registerLiveSearch($("#secret-filter-string"),".jspPane > .secret-item",$("#secret-filter-clear"));$(document).on("popup_pane_changed",function(a){"secrets"===a.originalEvent.detail.newPane&&(popupInitialFocus($("#secret-filter-string")),highlightSecret(selectedSecretIndex))});$('div[data-pane="secrets"]').keyup(function(a){a.keyCode===KeyCodes.UP?0<selectedSecretIndex&&(selectedSecretIndex--,highlightSecret(selectedSecretIndex),$(".item-actions").slideUp("fast")):a.keyCode===
KeyCodes.DOWN?selectedSecretIndex<visibleServicesLength-1&&(selectedSecretIndex++,highlightSecret(selectedSecretIndex),$(".item-actions").slideUp("fast")):a.keyCode===KeyCodes.RETURN&&(a=$(".secret-item."+SELECTED_CLASS).first(),a.length&&(a=getSecretForItem(a),executeSecretAction(a)))});$("#secret-filter-string").keyup(function(a){scrollPane.reinitialise();scrollPane.scrollToX(0,!1);a.keyCode>=KeyCodes.KEY_0&&a.keyCode<=KeyCodes.KEY_Z&&(selectedSecretIndex=0);highlightSecret(selectedSecretIndex)});
$(document).on("click",".secret-default-action",function(){$(".copied").removeClass("copied");var a=$(this).closest(".secret-item"),b=a.find(".item-actions"),c=$(this).closest("#context");selectedSecretIndex=$(".item.secret-item:visible").index(a);b.length&&(b.is(":hidden")?($(".item-actions").slideUp("fast"),$(".secret-item").removeClass(SELECTED_CLASS),a.addClass(SELECTED_CLASS),b.slideDown(300,function(){var a=c.height(),d=b.offset().top-c.offset().top+b.height();d>a&&scrollPane.scrollByY(d-a,
!0);scrollPane.reinitialise()})):b.slideUp(300,function(){scrollPane.reinitialise()}))});$(document).on("click",".secret-edit-action",function(){var a=$(this).closest(".secret-item"),a=getSecretForItem(a);openManageSecretPage(a)});$(document).on("click",".item-actions li",function(){$(".copied").removeClass("copied");var a=$(this),b=a.closest(".secret-item"),c=a.data("item-action"),b=getSecretForItem(b);switch(c){case "launch":executeSecretAction(b);break;case "copy-user":copyText(b.clientData.username,
function(){a.find(".copy-msg").addClass("copied")});break;case "copy-pw":copyPassword(b,function(){a.find(".copy-msg").addClass("copied")});break;case "edit-secret":openManageSecretPage(b)}})});
