var mitro=mitro||{},kew=kew||require("../../../../api/js/cli/kew");(function(){if(!("loadOrganizationInfo"in mitro)){var e=require("./org-info.js"),a;for(a in e)mitro[a]=e[a]}})();var assert=assert||require("../../../common/utils").assert,assertIsNumber=assertIsNumber||require("../../../common/utils").assertIsNumber,dictValues=dictValues||require("../../../common/utils").dictValues;
(function(){mitro.UserData=function(){this.users=this.groups=this.organization=this.orgId=this.organizationInfo=this.secrets=null};mitro.UserData.prototype.getGroup=function(a){if(!this.groups)throw Error("groups must not be null: UserData uninitialized");assertIsNumber(a);return a in this.groups?this.groups[a]:this.organization&&a in this.organization.groups?this.organization.groups[a]:null};mitro.UserData.prototype.getSecret=function(a){assertIsNumber(a);for(var b=0;b<this.secrets.length;b++){var c=
this.secrets[b];if(c.secretId===a)return c}return null};mitro.UserData.prototype.getSecretsForGroup=function(a){var b=[this.secrets];this.organization&&b.push(dictValues(this.organization.orgSecretsToPath));for(var c={},d=0;d<b.length;d++)for(var f=b[d],h=0;h<f.length;++h)for(var g=f[h],e=0;e<g.groups.length;++e)if(g.groups[e]===a){c[g.secretId]=g;break}return dictValues(c)};mitro.UserData.prototype.userBelongsToOrg=function(a){return void 0!==a&&null!==a&&null!==this.organizationInfo.getOrganization(a)};
mitro.UserData.prototype.getGroupsVisibleToSecret=function(){return null===this.orgId?this.groups:this.userBelongsToOrg(this.orgId)?this.organization.groups:[]};mitro.UserData.prototype.getUsersVisibleToSecret=function(){return null===this.orgId?this.users:this.userBelongsToOrg(this.orgId)?this.organization.members:[]};mitro.UserData.prototype.getUsersVisibleToGroup=function(){return null===this.orgId?this.users:this.userBelongsToOrg(this.orgId)?this.organization.members:[]};mitro.UserData.prototype.getSecretsVisibleToGroup=
function(){return null===this.orgId?this.secrets:this.userBelongsToOrg(this.orgId)?this.getOrganizationSecrets(this.orgId,this.organization):[]};mitro.UserData.prototype.userBelongsToSameOrgAsGroup=function(a){var b=this.getGroup(a);if(null===b)throw Error("group does not exist; id: "+a);return this.userBelongsToOrg(b.owningOrgId)};mitro.UserData.prototype.userBelongsToSameOrgAsSecret=function(a){var b=this.getSecret(a);if(null===b)throw Error("secret does not exist; id: "+a);return this.userBelongsToOrg(b.owningOrgId)};
mitro.UserData.prototype.getOrganizationSecrets=function(a,b){var c=[];if(b&&this.organizationInfo)if(this.organizationInfo.isOrgAdminFor(a))c=dictValues(b.orgSecretsToPath);else for(var d=0;d<this.secrets.length;d++){var f=this.secrets[d];f.owningOrgId===a&&c.push(f)}return c};mitro.UserData.prototype.getSelectedOrganizationSecrets=function(){return this.organizationInfo.getSelectedOrganization()?this.getOrganizationSecrets(this.orgId,this.organization):[]};mitro.UserData.prototype.getOrganizations=
function(){return this.organizationInfo.getOrganizations()};mitro.UserData.prototype.getOrganization=function(a){return this.organizationInfo.getOrganization(a)};mitro.UserData.prototype.getAllOrganizationInfo=function(){return this.organizationInfo};var e=function(a,b,c){var d=new kew.Promise,f=Array.prototype.slice.call(arguments,2);f.push(function(a){d.resolve(a)});f.push(function(a){d.reject(a)});b.apply(a,f);return d};mitro.loadUserDataPromise=function(){var a=new mitro.UserData,b=e(background,
background.listUsersGroupsAndSecrets),c=e(null,mitro.loadOrganizationInfo);c.then(function(b){a.organizationInfo=b});return kew.all([b,c]).then(function(b){a.secrets=b[0].secrets;a.groups=b[0].groups;a.users=b[0].users;return a})};mitro.loadUserData=function(a,b){mitro.loadUserDataPromise().then(a).fail(b)};mitro.loadOrganizationPromise=function(a,b){assertIsNumber(b);return e(background,background.getOrganization,b).then(function(c){a.orgId=b;return a.organization=c})};mitro.loadOrganization=function(a,
b,c,d){mitro.loadOrganizationPromise(a,b).then(c).fail(d)};mitro.getCompleteSecretPromise=function(a){assertIsNumber(a);return e(background,background.getSiteData,a)};mitro.loadUserDataAndSecret=function(a,b,c){assertIsNumber(a);var d=mitro.loadUserDataPromise();a=mitro.getCompleteSecretPromise(a);kew.all([d,a]).then(function(a){var d=a[0],c=a[1];a=null;null!==c&&d.userBelongsToOrg(c.owningOrgId)?a=mitro.loadOrganizationPromise(d,c.owningOrgId):(a=new kew.Promise,a.resolve(null));return a.then(function(){b(d,
c)})}).fail(c)};mitro.loadUserDataAndGroup=function(a,b,c){assert("number"===typeof a);var d=null;mitro.loadUserDataPromise().then(function(a){d=a;return null!==d.organizationInfo.selectedOrgId?mitro.loadOrganizationPromise(d,d.organizationInfo.selectedOrgId):null}).then(function(c){c=d.getGroup(a);b(d,c)}).fail(c)};mitro.hackBackgroundForTest=function(a){background=a;mitro.hackOrgInfoBackgroundForTest(a)};"undefined"!==typeof module&&module.exports&&(module.exports=mitro)})();
